### ISSUE TITLE
doesn't work with loading from app bundle (with ~ prefix)

### ISSUE THREAD

**Issue by naderio** [NativeScript/nativescript-dev-webpack#1]
breaks when [loading from app bundle](https://docs.nativescript.org/runtimes/require.html#loading-files-from-the-app-bundle).

it seems to work by addling the following webpack resolve configuration

```
var bundler = require("nativescript-dev-webpack");

var path = require("path");

module.exports = bundler.getConfig({
    root: path.resolve(__dirname),
    alias: {
      '~': 'app',
    },
    // or just 
    alias: {
      '~': path.resolve(__dirname, 'app'),
    },
  }
});
```

**Comment by hdeshev** [comment]
Well, this is just the way webpack works -- it intercepts all `require` calls. Another way to work around the problem would be to use a relative import.

**Comment by naderio** [comment]
@hdeshev relative import is not practical and can easily becomes confusing at some scale.
anyway, the solution mentioned above do not work by its own, some changes on nativescript-dev-webpack' code made it work perfectly.
I'll try to reproduce the changes and make a PR...

**Comment by naderio** [comment]
@hdeshev please check PR #3
