### ISSUE TITLE
Lazyloading problems

### ISSUE THREAD

**Issue by patrickpereira** [NativeScript/nativescript-dev-webpack#100]
Hi Nativescript team!

After lots of tries I finally managed to bundling my app, when I'm running the app which includes lazyloaded modules. I get the following error, while trying to lazyload a module:

CONSOLE ERROR file:///app/vendor.js:57290:22: Error: Uncaught (in promise): Error: Cannot find module './pages/home/home.module.ngfactory'.

There's prob some specific settings that needs to be done, when using lazyloaded modules and webpack. Does anybody have an idea what I need to do?

**Comment by sis0k0** [comment]
General guidelines for using lazy loading with `nativescript-angular`:

You need to provide the NativeScript module loader in your root module:
``` ts
import { NSModuleFactoryLoader } from "nativescript-angular/router";
...
@NgModule({
    providers: [
        { provide: NgModuleFactoryLoader, useClass: NSModuleFactoryLoader }
    ]
})
```

When defining the paths to the lazy loaded modules, they should be relative to the current file. For example, if you have a module `LazyModule` in `app/lazy/lazy.module.ts`, then your routing configuration in the file `app/app-routing.ts` should look like this:
``` ts
const routes = [
    {
        path: "lazy",
        loadChildren: "./lazy/lazy.module#LazyModule",
    },
];
...
```

**Comment by sis0k0** [comment]
Hey @patrickpereira, do you still have issues when using `nativescript-dev-webpack` with lazy-loading?

**Comment by jfturcot** [comment]
Sorry about commenting on a closed issue, but I just want to note that if anyone run into this error using Angular 4.0 and nativescript-angular 1.5, make sure @ngtools/webpack is at version 1.2.13. I was using 1.2.10 and had the "Cannot find module" problem.

I haven't tried later version of @ngtools/webpack, but @sis0k0 mentioned on another issue (#106) that there currently were some problems with @ngtools/webpack 1.2.14+

I hope this helps someone else and saves him/her the hours I lost trying to figure this out :)
