### ISSUE TITLE
Snapshot fails on macOS Catalina

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-dev-webpack#1038]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.0
 - Cross-platform modules: 6.1.0
 - Android Runtime: 6.1.0 
 - iOS Runtime: 6.1.0 
 - Plugin(s): Not applicable
 - Node.js: 10.15.3
 - nativescript-dev-webpack: 1.2.0

 - [ ] Please, attach your package.json and webpack.config.js as these configurations are usually critical for investigating issues with webpack
 

**Describe the bug**
Running `tns build android --release --env.snapshot --keyStorePath...` fails on macOS Catalina with error: 

**To Reproduce**
Just try to use snapshot on macOS Catalina.

**Expected behavior**
Snapshot to succeed.

**Sample project**

**Additional context**
In order to generate snapshots for x86 and armv7 architectures, we need to start the snapshot tool for them. The tool itself is a 32-bit process. On macOS Catalina 32-bit processes are no longer supported and that causes the issue.

**Comment by DimitarTachev** [comment]
AC:

- [ ] starting from macOS Catalina, a Docker usage message should be shown
- [ ] starting from macOS Catalina without Docker, the process should exit with a Docker installation error
- [ ] starting from macOS Catalina without running Docker server, the process should exit with a missing Docker server error
- [ ] starting from macOS Catalina with running Docker server, the command should run successfully without any additional actions.
- [ ] before macOS Catalina (e.g. on macOS Mojave) with/without Docker, the command should run without any Docker usage and messages.
- [ ] before macOS Catalina (e.g. on macOS Mojave), when the local mksnapshot tools are not available (`mksnapshot --help` is failing), the command should fallback to Docker and follow the Catalina flow.
- [ ] on Linux, when the local mksnapshot tools are not available (`mksnapshot --help` is failing), the command should fallback to Docker and follow the Catalina flow. This should be reproducible on Linux without 32-bit processes support. (https://askubuntu.com/questions/1023962/how-to-install-libc6i386-on-16-04-4-64bit will fix the local setup)
- [ ] an integration test with the Android Runtime should be added, ensuring that the latest version of the Docker image is compatible with the latest version of the snapshot tools of the runtime (new snapshot tools are built on each V8 update).
- [ ] add some tests validating the `nativescript/v8-snapshot` Docker image size. The current size should be ~13MB. E.g test for < 20MB.
- [ ] the cloud builds should not be affected by the changes (they should not require Docker installation on any OS)
