### ISSUE TITLE
Uglify option prevents the generation of java class

### ISSUE THREAD

**Issue by mrpaaske** [NativeScript/nativescript-dev-webpack#1039]
**Environment**
tns info

✔ Component nativescript has 6.1.0 version and is up to date.
✔ Component tns-core-modules has 6.1.0 version and is up to date.
✔ Component tns-android has 6.1.0 version and is up to date.
✔ Component tns-ios has 6.1.0 version and is up to date.

node -v
v12.8.0

Relvant section of webpack.config.js

```
    // Add your custom Activities, Services and other Android app components here.
    const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        resolve(__dirname, "src/app/call-state-listener.ts"),
    ];
```

call-state-listener.ts:

```
@JavaProxy('com.company.BroadcastReceiver.CallStateListener')
export class CallStateListener extends android.content.BroadcastReceiver {

  constructor() {
    super();
    global.__native(this); // necessary in TS constructors if extending native class
  }

  public onReceive(context: android.content.Context, intent: android.content.Intent) {
  }
}
```

AndroidManifest.xml

```
		<receiver android:name="com.company.BroadcastReceiver.CallStateListener">
			<intent-filter>
				<action android:name="android.intent.action.PHONE_STATE" />
				<action android:name="android.intent.action.PHONE_STATE_CHANGED" />
				<action android:name="android.intent.action.NEW_OUTGOING_CALL" />
			</intent-filter>
		</receiver>
	</application>
</manifest>
```
**Describe the bug**

When using the --env.uglify flag, the generated .class-file is missing from the apk-file.
Without the flag, it works fine.

Might be related to #564

**Comment by RadouaneRoufid** [comment]
Any news on this ? 
I had opened https://github.com/NativeScript/nativescript-dev-webpack/issues/564 and still having the problem in tns 6.1.2

**Comment by RadouaneRoufid** [comment]
I found the solution. `"noEmitHelpers": true`, must be present in `compilerOptions` in t`sconfig.json` while build with `env.uglify` with custom activity.
