### ISSUE TITLE
Setting iOS Capabilities

### ISSUE THREAD

**Issue by ls-spavel** [NativeScript/nativescript-dev-webpack#104]
I have the need to set a couple capabilities on my xcodeproj (specifically "Push Notifications" and "Keychain Sharing". I can't seem to figure out how to do this while webpacking.

Normally my process would look like the following: 
1) Prepare iOS (`tns prepare ios` )
2) Open the project in xcode
3) Set the capabilities I need
4) Build ios for release with capabilities set

The problem is that now when I webpack the entire build process is bundled up automatically. I don't have the opportunity to set those capabilities. How does one go about doing this?

**Comment by sis0k0** [comment]
Hey @ls-spavel,

Sorry for the late reply. You can prepare the project using webpack and then set the capabilities. If you don't have webpack installed globally, you can add the following build script in your package.json:

```
"scripts": {
    "webpack": "webpack --config=webpack.ios.js --progress"
}
```

So the first step will be:
`npm run webpack`

The rest should be the same. Let me know if that helped!
