### ISSUE TITLE
Release mode

### ISSUE THREAD

**Issue by danieloprado** [NativeScript/nativescript-dev-webpack#105]
How to run a release build?
The command below is not working:
```bash
npm run ns-bundle --android --build-app -- --release --key-store-path keys/release.keystore --key-store-password 123 --key-store-alias alias --key-store-alias-password 123 --copy-to=release.apk
```
Just bundle the code but not call the **tns build**

**Comment by sis0k0** [comment]
Hey @danieloprado,

Check out the [docs](https://docs.nativescript.org/tooling/bundling-with-webpack#bundling) if you haven't already. You can bundle for release with the following command:

```
npm run build-android-bundle -- --release --key-store-path keys/release.keystore --key-store-password 123 --key-store-alias alias --key-store-alias-password 123 --copy-to=release.apk
```

As you can see in the `package.json`, `build-android-bundle` actually calls `npm run ns-bundle --android --start-app`. When you add the two dashes (`--`) before `--release`, the rest of the args (`--release --key-store-path...`) will be passed to the inner command - `npm run ns-bundle --android --start-app`.
With that being said, if you want to use `ns-bundle` directly, you don't need the escaping dashes. So the other valid way to bundle for release looks like:

```
npm run ns-bundle --android --build-app --release --key-store-path keys/release.keystore --key-store-password 123 --key-store-alias alias --key-store-alias-password 123 --copy-to=release.apk
```

Hope that helps. If you still have problems, don't hesitate to write!

**Comment by danieloprado** [comment]
Thanks @sis0k0, it worked!
