### ISSUE TITLE
Support V8 Snapshots on Windows

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-dev-webpack#1054]
**Is your feature request related to a problem? Please describe.**
The `--env.snapshot` flag is not supported and throwing an exception on Windows.

**Describe the solution you'd like**
As we already have [snapshots generation in a Docker container ](https://github.com/NativeScript/nativescript-dev-webpack/pull/1048)for macOS Catalina, we could reuse the same approach on Windows.

**Comment by endarova** [comment]
Acceptance criteria:
- [ ] when executing build with --env.snapshot flag on windows, a Docker usage message should be shown
- [ ] when executing build with --env.snapshot flag on windows without Docker, the process should exit with a Docker installation error
- [ ] when executing build with --env.snapshot flag on windows without running Docker server, the process should exit with a missing Docker server error
- [ ] when executing build with --env.snapshot flag on windows with running Docker server, the command should run successfully without any additional actions.
- [ ] with nativescript@6.1 and nativescript-dev-webpack@1.2.1 and earlier when executing build with --env.snapshot flag on windows message that snapshot flag is skipped should be shown
