### ISSUE TITLE
Error with webpack

### ISSUE THREAD

**Issue by mlusca** [NativeScript/nativescript-dev-webpack#1061]
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: ReferenceError: window is not defined
System.err: File: (file:///node_modules\phaser\src\polyfills\AudioContextMonkeyPatch.js:60:0)
System.err: 
System.err: StackTrace:
System.err:     (file:///node_modules\phaser\src\polyfills\AudioContextMonkeyPatch.js:60:0)
System.err:     at ../node_modules/phaser/src/polyfills/AudioContextMonkeyPatch.js(file:///node_modules\phaser\src\polyfills\AudioContextMonkeyPatch.js:181:1)      
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/phaser/src/polyfills/index.js(file:///node_modules\phaser\src\polyfills\index.js:3:0)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at (file:///node_modules\phaser\src\phaser.js:7:0)
System.err:     at ../node_modules/phaser/src/phaser.js(file:///data/data/org.nativescript.gfrontend11/files/app/vendor.js:195989:30)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at ./app/game/game.component.ts(file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:619:64)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at ./app/app.module.tns.ts(file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:121:78)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:916:77)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:985:30)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file:///src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: ReferenceError: window is not defined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function  
System.err: ReferenceError: window is not defined
System.err: File: (file:///node_modules\phaser\src\polyfills\AudioContextMonkeyPatch.js:60:0)
System.err:
System.err: StackTrace: 
System.err:     (file:///node_modules\phaser\src\polyfills\AudioContextMonkeyPatch.js:60:0)
System.err:     at ../node_modules/phaser/src/polyfills/AudioContextMonkeyPatch.js(file:///node_modules\phaser\src\polyfills\AudioContextMonkeyPatch.js:181:1)      
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/phaser/src/polyfills/index.js(file:///node_modules\phaser\src\polyfills\index.js:3:0)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at (file:///node_modules\phaser\src\phaser.js:7:0)
System.err:     at ../node_modules/phaser/src/phaser.js(file:///data/data/org.nativescript.gfrontend11/files/app/vendor.js:195989:30)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at ./app/game/game.component.ts(file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:619:64)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at ./app/app.module.tns.ts(file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:121:78)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:916:77)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:985:30)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file:///src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: ReferenceError: window is not defined
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:199)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function
System.err: ReferenceError: window is not defined
System.err: File: (file:///node_modules\phaser\src\polyfills\AudioContextMonkeyPatch.js:60:0)
System.err:
System.err: StackTrace:
System.err:     (file:///node_modules\phaser\src\polyfills\AudioContextMonkeyPatch.js:60:0)
System.err:     at ../node_modules/phaser/src/polyfills/AudioContextMonkeyPatch.js(file:///node_modules\phaser\src\polyfills\AudioContextMonkeyPatch.js:181:1)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at ../node_modules/phaser/src/polyfills/index.js(file:///node_modules\phaser\src\polyfills\index.js:3:0)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at (file:///node_modules\phaser\src\phaser.js:7:0)
System.err:     at ../node_modules/phaser/src/phaser.js(file:///data/data/org.nativescript.gfrontend11/files/app/vendor.js:195989:30)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at ./app/game/game.component.ts(file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:619:64)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at ./app/app.module.tns.ts(file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:121:78)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at fn(file:///src\webpack\bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:916:77)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:985:30)
System.err:     at __webpack_require__(file:///src\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file:///src\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///src\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.gfrontend11/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: ReferenceError: window is not defined
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:662)
System.err:     at com.tns.Runtime.run(Runtime.java:654)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
System.err:     ... 8 more

Configs:
Angular 8,
"nativescript-angular": "~8.0.1",
    "nativescript-theme-core": "~1.0.4",
    "phaser": "^3.19.0",

 over the web, it works normally.
Helpe me.

**Comment by Fatme** [comment]
@mlusca,

It seems you have a code shared application that is using [phaser](https://github.com/photonstorm/phaser) framework. As it is a  `HTML5 game framework`, you should ensure that it is required/imported only in the web part of your application. It shouldn't be required/imported from mobile part of the app.

**Comment by LucasMotaRodrigues** [comment]
I did not understand.
Can't import it in the mobile part?
So I can't use it on the mobile part?

**Comment by LucasMotaRodrigues** [comment]
@Fatme 
I did not understand.
Can't import it in the mobile part?
So I can't use it on the mobile part?

**Comment by mlusca** [comment]
@Fatme 
I did not understand.
Can't import it in the mobile part?
So I can't use it on the mobile part?

**Comment by NickIliev** [comment]
@mlusca you can't use an NPM library that uses DOM in a mobile application. The thing is that the mobile world is not using DOM but its own APIs (iOS API or Android SDK) so objects used in DOM (like `window` for example) are just not making sense. There are some NPM libraries made for NativeScript that are using polyfills but this is not the case with the phaser framework which is made with DOM in mind. 

SO the short answer is - No, you can't use phaser within the mobile part of your application.
