### ISSUE TITLE
move share.module in vendor.js

### ISSUE THREAD

**Issue by bagnos** [NativeScript/nativescript-dev-webpack#1074]
Hi,

I'm using the latest version of nativescript-dev-webpack, I see that the plugin imported are now moved automatically in vendor.js .
There's non need to create src/vendor.ts and put the import in it.
I have a Module shared between the feature modules, how can I move it to vendor.js?
I tried to create the src/vendor.ts but by webpack analyzer I keep seeing them in the feature modules.

Can you help me?

**Comment by Fatme** [comment]
@bagnos,

The `bundle.js` and `vendor.js` files inside platforms directory are automatically generated files by webpack compilation. All modules from application are produced in `bundle.js` file and all modules from `node_modules` e.g all dependencies of the application are outputted in `vendor.js`.

> I have a Module shared between the feature modules, how can I move it to vendor.js?

Why do you need to move the module to `vendor.js`? Can you give us more details about your particular use case?

**Comment by bagnos** [comment]
hi,

the shared module is imported in all of the feature modules, so in the
chunks I can see that module many times, see below.
If I could move it to vendor.js I improved size e boot time (snapshot)
I see that in this old link https://www.youtube.com/watch?v=7rHnLb-2tZ4.


[image: image.png]

**Comment by edusperoni** [comment]
You can change this in your `webpack.config.json` (https://github.com/NativeScript/nativescript-dev-webpack/blob/master/demo/AngularApp/webpack.config.js#L169). If that test returns true for your file it gets bundled in vendor.js

**Comment by bagnos** [comment]
Thanks so much @edusperoni ! 

It works.
