### ISSUE TITLE
Remove platform-css-loader

### ISSUE THREAD

**Issue by ishitatsuyuki** [NativeScript/nativescript-dev-webpack#108]
This just makes the code less standard compliant.

Instead, let's correct the docs and blueprints to let users import with the tilde mark.

CC https://github.com/toddanglin/nativescript-dev-sass/issues/24

**Comment by sis0k0** [comment]
Hey @ishitatsuyuki,

You can use the newly supported syntax both with and without that loader. If we remove the loader, we'll introduce a breaking change. I prefer to avoid that and support the old syntax instead.
