### ISSUE TITLE
Built App XML Page code-behind not executing

### ISSUE THREAD

**Issue by eldadj** [NativeScript/nativescript-dev-webpack#110]
I have slowly managed to tame Webpack for NS - Typscript! (Its been a battle - will do a how-to once I can figure out this issue)
My webpacked NS application is loading and showing the XML UI, but the code behind ts/js files are not being executed.

What I have done

global.registerModule("dotell", () => require("./pages/dotell"));
I can actually see the ts/js files in the bundle.js
Issue is that all/any code that should run when the UI shows is not running. And no errors whatsoever. Just like the UI is not auto-loading the code behind.

```
"copy-webpack-plugin": "~3.0.1",
"extract-text-webpack-plugin": "~2.0.0-beta.4",
"lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "^0.3.7",
    "nativescript-dev-webpack": "^0.3.6",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "webpack": "^2.3.2",
    "webpack-sources": "~0.1.3"
```

###tns info
```
nativescript: 2.5.3
tns-core-modules: 2.5.2
tns-android: 2.5.0
```

Any help???

**Comment by eldadj** [comment]
@sis0k0 @tjvantoll @burkeholland
Please you guys help with this? Its currently a major deal-breaker for me.
Thanks.

**Comment by sis0k0** [comment]
Hey @eldadj,

Sorry for the late reply. I can't really understand what causes your problem. Can you send us a sample project that we can debug it?
Also, you can check out [this](https://github.com/NickIliev/NativeScript-Cosmos-Databank) awesome @NickIliev's project which is configured to work with webpack and especially the [bundle-config](https://github.com/NickIliev/NativeScript-Cosmos-Databank/blob/master/app/bundle-config.ts) file. Thank you for your patience!

**Comment by sis0k0** [comment]
@eldadj, did you manage to resolve your problem?

**Comment by sis0k0** [comment]
Please, feel free to reopen this issue if you are still experiencing problems with the plugin.

**Comment by eldadj** [comment]
@sis0k0 sorry have not responded since. I actually re-wrote the app using Ionic (since trying to figure out which part was giving me issues was proving difficult and would entail yanking out everything and re-adding) and have released it to the Google Play Store. I still prefer using NS, so am writing the administrative/back office portion of the app using NS 3.0. I plan on using webpack from the very beginning so that I can properly catch any errors upfront. 
Will document my experience using Ionic to re-write an NS app, but I confess I prefer NS even if Ionic feels prettier!
