### ISSUE TITLE
Release mode errors

### ISSUE THREAD

**Issue by patrickpereira** [NativeScript/nativescript-dev-webpack#115]
Hi Nativescript,

I keep getting errors trying to upload the .ipa to itunes connect, what are the build.xcconfig settings and the command that should be used, currently I'm having this in build.xcconfig:

CODE_SIGN_IDENTITY = iPhone Distribution 

DEVELOPMENT_TEAM = XXXXXXXX
OR
PROVISIONING_PROFILE = XXXXXXXX

I've tried both DEVELOPMENT_TEAM & PROVISIONING_PROFILE

If I'm using DEVELOPMENT_TEAM I get the following error from application loader:

ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle app.nurt.kcal [Payload/Kcal.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."

If I'm using PROVISIONING_PROFILE, I'm unable to build it and get the following error from the CLI:

Check dependencies
Kcal has conflicting provisioning settings. Kcal is automatically signed, but provisioning profile XC iOS: app.nurt.kcal has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'
Code signing is required for product type 'Application' in SDK 'iOS 10.2'
Code signing is required for product type 'Application' in SDK 'iOS 10.2'
Code signing is required for product type 'Application' in SDK 'iOS 10.2'

I know the provisioning profile is valid, since I'm able to do the release through xcode if I compile the ipa there. But for some reason that ipa file is almost twice the size of the one created by the CLI.

The command I'm using in the CLI is: npm run build-ios-bundle -- --release --for-device

Furthermore I'm using tns-ios 2.5.

Hope you can help me ( @sis0k0 ) :-)

**Comment by sis0k0** [comment]
This issue was moved to NativeScript/nativescript-cli#2716
