### ISSUE TITLE
npm run build-ios-bundle – --release --copy-to HelloWorld.ipa FAILED

### ISSUE THREAD

**Issue by hugoploeg** [NativeScript/nativescript-dev-webpack#117]
Hello,

When I try to run the command to copy the app to .ipa, it fails. 
`npm run build-ios-bundle – --release --copy-to HelloWorld.ipa FAILED`

When I try to run the `tns run ios` it succeed.
I hope you can help. See the logs below and also the Debug log.

##LOG

`> testapp@0.1.0 build-ios-bundle /Users/Hugo/Desktop/testapp`
`> npm run ns-bundle --ios --build-app "–" "HalloWorld.ipa"`

`> testapp@0.1.0 ns-bundle /Users/Hugo/Desktop/testapp`
`> ns-bundle "–" "HalloWorld.ipa"`

`Running webpack for ios...`
`/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:14552`
`            var sourceFile = new SourceFileConstructor(261 /* SourceFile */, /*pos*/ 0, /* end */ sourceText.length);`
                                                                                                            ^

`TypeError: Cannot read property 'length' of undefined`
`    at createSourceFile (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:14552:109)`
`    at parseSourceFileWorker (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:14484:26)`
`    at Object.parseSourceFile (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:14433:26)`
`    at Object.createSourceFile (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:14288:29)`
`    at WebpackCompilerHost.getSourceFile (/Users/Hugo/Desktop/testapp/node_modules/@ngtools/webpack/src/compiler_host.js:209:27)`
`    at findSourceFile (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:63453:29)`
`    at processSourceFile (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:63384:27)`
`    at /Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:63494:17`
`    at Object.forEach (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:1293:30)`
`    at processReferencedFiles (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:63492:16)`
`    at findSourceFile (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:63477:21)`
`    at processSourceFile (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:63384:27)`
`    at processRootFile (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:63271:13)`
`    at /Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:62620:60`
`    at Object.forEach (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:1293:30)`
`    at Object.createProgram (/Users/Hugo/Desktop/testapp/node_modules/typescript/lib/typescript.js:62620:16)`
`child process exited with code 1`

`npm ERR! Darwin 16.5.0`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ns-bundle" "--ios" "--build-app" "–" "HalloWorld.ipa"`
`npm ERR! node v6.10.2`
`npm ERR! npm  v3.10.10`
`npm ERR! code ELIFECYCLE`
`npm ERR! testapp@0.1.0 ns-bundle: `ns-bundle "–" "HalloWorld.ipa"`
`npm ERR! Exit status 1`
`npm ERR! `
`npm ERR! Failed at the testapp@0.1.0 ns-bundle script 'ns-bundle "–" "HalloWorld.ipa"'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the testapp package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     ns-bundle "–" "HalloWorld.ipa"`
`npm ERR! You can get information on how to open an issue for this project with:`
`npm ERR!     npm bugs testapp`
`npm ERR! Or if that isn't available, you can get their info via:`
`npm ERR!     npm owner ls testapp`
`npm ERR! There is likely additional logging output above.`
`npm ERR! Please include the following file with any support request:`
`npm ERR!     /Users/Hugo/Desktop/testapp/npm-debug.log`
`npm ERR! Darwin 16.5.0`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-ios-bundle" "–" "--release" "--copy-to" "HalloWorld.ipa"`
`npm ERR! node v6.10.2`
`npm ERR! npm  v3.10.10`
`npm ERR! code ELIFECYCLE`
`npm ERR! testapp@0.1.0 build-ios-bundle: `npm run ns-bundle --ios --build-app "–" "HalloWorld.ipa"`
`npm ERR! Exit status 1`
`npm ERR! `
`npm ERR! Failed at the testapp@0.1.0 build-ios-bundle script 'npm run ns-bundle --ios --build-app "–" "HalloWorld.ipa"'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the testapp package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     npm run ns-bundle --ios --build-app "–" "HalloWorld.ipa"`
`npm ERR! You can get information on how to open an issue for this project with:`
`npm ERR!     npm bugs testapp`
`npm ERR! Or if that isn't available, you can get their info via:`
`npm ERR!     npm owner ls testapp`
`npm ERR! There is likely additional logging output above.`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     /Users/Hugo/Desktop/testapp/npm-debug.log`

##DEBUG LOG

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-ios-bundle',
1 verbose cli   '–',
1 verbose cli   '--release',
1 verbose cli   '--copy-to',
1 verbose cli   'HalloWorld.ipa' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prebuild-ios-bundle',
4 verbose run-script   'build-ios-bundle',
4 verbose run-script   'postbuild-ios-bundle' ]
5 info lifecycle testapp@0.1.0~prebuild-ios-bundle: testapp@0.1.0
6 silly lifecycle testapp@0.1.0~prebuild-ios-bundle: no script for prebuild-ios-bundle, continuing
7 info lifecycle testapp@0.1.0~build-ios-bundle: testapp@0.1.0
8 verbose lifecycle testapp@0.1.0~build-ios-bundle: unsafe-perm in lifecycle true
9 verbose lifecycle testapp@0.1.0~build-ios-bundle: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Hugo/Desktop/testapp/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle testapp@0.1.0~build-ios-bundle: CWD: /Users/Hugo/Desktop/testapp
11 silly lifecycle testapp@0.1.0~build-ios-bundle: Args: [ '-c',
11 silly lifecycle   'npm run ns-bundle --ios --build-app "–" "HalloWorld.ipa"' ]
12 silly lifecycle testapp@0.1.0~build-ios-bundle: Returned: code: 1  signal: null
13 info lifecycle testapp@0.1.0~build-ios-bundle: Failed to exec build-ios-bundle script
14 verbose stack Error: testapp@0.1.0 build-ios-bundle: `npm run ns-bundle --ios --build-app "–" "HalloWorld.ipa"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid testapp@0.1.0
16 verbose cwd /Users/Hugo/Desktop/testapp
17 error Darwin 16.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-ios-bundle" "–" "--release" "--copy-to" "HalloWorld.ipa"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error testapp@0.1.0 build-ios-bundle: `npm run ns-bundle --ios --build-app "–" "HalloWorld.ipa"`
22 error Exit status 1
23 error Failed at the testapp@0.1.0 build-ios-bundle script 'npm run ns-bundle --ios --build-app "–" "HalloWorld.ipa"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the testapp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run ns-bundle --ios --build-app "–" "HalloWorld.ipa"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs testapp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls testapp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Regards,
Hugo

**Comment by sis0k0** [comment]
We'll provide a fix for this in a few days. Can you try the following workaround:

```
tns platform remove ios
tns platform add ios
npm run build-ios-bundle – --release --copy-to HelloWorld.ipa
```

Also can you share your package.json, too?

**Comment by hugoploeg** [comment]
Hello sis0K0,

Thanks for your quick response. I have run your workaround, still got the error. I have attached the json file/ error log and debug log.

[error.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/923449/error.txt)

[npm-debug_log.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/923456/npm-debug_log.txt)

[package_json.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/923455/package_json.txt)

**Comment by sis0k0** [comment]
Hello @hugoploeg,

Unfortunatelly, I couldn't reproduce the error using just the `package.json`, which means that the issue is caused by some file in the project. I'll need your help on this one :)

If you could attach the project, that will be great. But if it's private, you can try some of the following:
- comment out `webpack.common.js:119` - the `nativescript-dev-webpack/platform-css-loader`. If that solves the issue, please let me know. We had issues with that loader, but we could have missed something.
- open `node_modules/typescript/lib/typescript.js` and add `console.log(fileName)` to line 14553 - that way we can find out the file causing the error.

Thank you in advance!

**Comment by hugoploeg** [comment]
Hello @sis0k0,

I have send the project by email (wetransfer) to you. Thank you in advance for the help!

Regards,
Hugo

**Comment by sis0k0** [comment]
Hello @hugoploeg,

Are you sure this is the right project? Seems like a plain JS NativeScript project but it has dependencies on TypeScript and Angular. If it's plain JS, you don't need these. Also they are messing up your webpack configuration.

**Comment by hugoploeg** [comment]
Hello @sis0k0,

Yes, it is the right project but to test I have copied the .json from another project to test if that was working. Finally we are going to use it also fir this project. I have tried to  delete them and run it again but without luck.

Regards,

**Comment by sis0k0** [comment]
You can remove all `@angular` and `typescript` packages from your package.json, also delete your `webpack.common.js` file and all `app/vendor*` files. After that, when you reinstall `nativescript-dev-webpack`, it should bring the correct configurations.

**Comment by hugoploeg** [comment]
@sis0k0,

I have done what you said in the above comment, see the log below actually no errors only 2 warnings css. but also there is no .ipa created.

[log2.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/929142/log2.txt)

Regards,

**Comment by sis0k0** [comment]
Oh, I just now saw there's also a typo in the command you are running.
Instead of:
```
npm run build-ios-bundle – --release --copy-to HelloWorld.ipa FAILED
```
it should be:
```
npm run build-ios-bundle -- --release --copy-to HelloWorld.ipa FAILED
```

There should be two dashes before `--release` instead of one.

**Comment by hugoploeg** [comment]
Hmm, does make no sense same message.

**Comment by hugoploeg** [comment]
@sis0k0,

Ok, run the command again and the build folder is made in ios, and filled with the following.

testapp-Prefix-eboijzofqkawbseddcxbfmnhlmyg
testapp-Prefix-aklniojjeubapjdwmxvhhwboekez

But also the npm errors, see 
[log3.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/929297/log3.txt)

the log attached.

**Comment by sis0k0** [comment]
If you are using nativescript@2.5, this is probably related to: https://github.com/NativeScript/nativescript-cli/issues/2357.

Try building without `--copy-to`.

**Comment by hugoploeg** [comment]
@sis0k0,

Try building without --copy-to. //this is not fixing it. And yes we are using nativescript@2.5.

Regards,

**Comment by sis0k0** [comment]
Are the errors the same as before?

**Comment by hugoploeg** [comment]
@sis0k0,

this is the log.

[log4.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/929836/log4.txt)

**Comment by sis0k0** [comment]
You need to remove `HelloWorld.ipa` from the command, too.

**Comment by hugoploeg** [comment]
@sis0k0,
That works.

** BUILD SUCCEEDED **
Project successfully built.

Only what stays open is the creating of the ipa.

**Comment by sis0k0** [comment]
It should be located in `platforms/ios/build/device/AppName.ipa'

**Comment by dudanogueira** [comment]
@sis0k0 , this did the trick for me:

```
tns platform remove ios
tns platform add ios
```

looks like after running the tns run android, the npm run start-android-bundle, sometimes, stop building, presents almost no error, more than: 

> var sourceFile = new SourceFileConstructor(261 /* SourceFile */, /*pos*/ 0, /* end */ sourceText.length);                                                                                                          ^
> 
> TypeError: Cannot read property 'length' of undefined

at the docs, it suggest to run:

`npm run webpack-android -- --display-error-details`

with no luck:

> npm ERR! missing script: webpack-android


I am new to this nativescript / webpack / angular world, and I could notice that with webpack the start time at android was considerably lower than regular tns run android, so I decided to give it a try.

Anyway, thanks for your help and support!!!

**Comment by hugoploeg** [comment]
@sis0k0,

Yes it should be there, this is my result,

<img width="255" alt="screen shot 2017-04-18 at 20 19 15" src="https://cloud.githubusercontent.com/assets/3809136/25146551/98e45c72-2474-11e7-9127-9bcd497f771f.png">

**Comment by sis0k0** [comment]
@hugoploeg,

Try adding `--for-device` flag too.

**Comment by sis0k0** [comment]
@dudanogueira,

Can you try adding the following properties to your `tsconfig.aot.json` file?

```
"exclude": [
    "node_modules",
     "platforms"
]
```

**Comment by hugoploeg** [comment]
@sis0k0,

added the flag but give me a lot of errors as before, it looks like everything I am typing after the 
--release  is failing.

**Comment by sis0k0** [comment]
@hugoploeg,

You probably need to provide team id or provisioning profile (with `--teamId` or `--provision` respectively).

**Comment by dudanogueira** [comment]
@sis0k0 , just did. Interesting to note that I removed the ItemListComponent from my references (Router, NgModule, etc), so I could start coding, and the build failed pointing to those files, even when they were not metioned on other files. After I removed them completely, the entire item folder the build was OK again...

```
ERROR in Cannot determine the module for class ItemDetailComponent in /home/dudanogueira/dev/unimed/MyProject/app/item/item-detail.component.ts! Add ItemDetailComponent to the NgModule to fix it.
Cannot determine the module for class ItemsComponent in /home/dudanogueira/dev/unimed/MyProject/app/item/items.component.ts! Add ItemsComponent to the NgModule to fix it.

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/home/dudanogueira/dev/unimed/MyProject/app'
 @ ./main.aot.ts 4:29-62
```
Also, I am getting some WARNINGS:

```
WARNING in ./app.css
  resolve-url-loader cannot operate: CSS error
  /home/dudanogueira/dev/unimed/MyProject/app/app.css:6:45: property missing ':'
  at error (/home/dudanogueira/dev/unimed/MyProject/node_modules/css/lib/parse/index.js:62:15)

```
the plus side: everything is building fine after your tip, going back and forth from **tns run android** and the **npm run start-android-bundle**

Thanks!!!

**Comment by sis0k0** [comment]
@hugoploeg,

Here's how we use the command to build for iOS release:

```
npm run build-ios-bundle -- --release --forDevice --teamId TEAM_ID
```

**Comment by hugoploeg** [comment]
@sis0k0,

Many thanks for the support! I can now buiold locally build the .IPA what fixed it was the following we added the certificates in xcode and after that we run:
`npm run build-ios-bundle -- --release --forDevice`
