### ISSUE TITLE
Custom Fonts don't work with Webpack on ios devices

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/nativescript-dev-webpack#12]
At the function `registerCustomFonts()`, there's a `fontsFolderPath` which is trying to find the `/tns_modules` path. However, `/tns_modules` is not included in the `_dirname` path when we bundle.

[/tns-core-modules/ui/styling/font.ios.ts](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/styling/font.ios.ts#L319)
```javascript
var fontsFolderPath = fs.path.join(__dirname.substring(0, __dirname.indexOf("/tns_modules")), "fonts");
```

@domgaud and I have a temporary fix for that:

```javascript
var fontsFolderPath = fs.path.join(__dirname.substring(0, __dirname.indexOf("/tns_modules")), "fonts");

// Try from root as well for webpack bundle.js
if (!fs.Folder.exists(fontsFolderPath)) {
    fontsFolderPath = fs.path.join(__dirname, "fonts");
}

if (fs.Folder.exists(fontsFolderPath)) {
...
```

Someone with a better fix or should we send a PR?

**Comment by NathanaelA** [comment]
@leocaseiro - Nice I just traced the exact same issue down myself.  Was about to post a bug report.

My "temporary" solution to work around it was:
```
if (global.NSObject && global.NSString) {
  var font = require('ui/styling/font');
  font.ios.registerFont('fontawesome-webfont.ttf');
}
```
