### ISSUE TITLE
Unable to build to device - dyld: Library not loaded: @rpath/Bolts.framework/Bolts

### ISSUE THREAD

**Issue by SamuelReeder** [NativeScript/nativescript-dev-webpack#121]
I have been trying to get webpack to work for IOS for about 4 days now. Throughout this time I have gone through a lot of errors and have finally found n I am unable to figure out.

When i run the command  `npm run ns-bundle --ios --start-app` The build works, the archive works and the export works. However as soon as it hits the device it will crash and display 1 of two errors.
The most common of the two is `dyld: Library not loaded: @rpath/Bolts.framework/Bolts`.
The next is `child process exited with code 1` (thats all it will throw).

I have tried to look at my device logs but there never seems to be one when the second error is thrown.

I can run in a emulator without issue.

here is my package.json 

`{
  "description": "MyName",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "MyName",
  "repository": "myRepo",
  "nativescript": {
    "id": "org.nativescript.MyName",
    "tns-android": {
      "version": "2.5.0"
    },
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.0.2",
    "@angular/common": "~4.0.2",
    "@angular/compiler": "~4.0.2",
    "@angular/core": "~4.0.2",
    "@angular/forms": "~4.0.2",
    "@angular/http": "~4.0.2",
    "@angular/platform-browser": "~4.0.2",
    "@angular/platform-browser-dynamic": "~4.0.2",
    "@angular/platform-server": "~4.0.2",
    "@angular/router": "~4.0.2",
    "acorn-dynamic-import": "^2.0.2",
    "email-validator": "^1.0.7",
    "nativescript-angular": "1.5.1",
    "nativescript-angular-snapshot": "1.5.0-5.5.372.32",
    "nativescript-camera": "0.0.8",
    "nativescript-drop-down": "^1.3.3",
    "nativescript-loading-indicator": "^2.2.2",
    "nativescript-permissions": "^1.2.1",
    "nativescript-plugin-firebase": "3.11.3",
    "nativescript-telerik-ui": "1.6.2",
    "nativescript-toasty": "^1.1.0",
    "nativescript-videoplayer": "^2.4.0",
    "nativescript-videorecorder": "^1.3.6",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "^2.5.2",
    "zone.js": "^0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.0.2",
    "@ngtools/webpack": "1.2.13",
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "filewalker": "0.1.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.5",
    "nativescript-dev-webpack": "^0.3.7",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "typescript": "~2.1.0",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3",
    "css-loader": "~0.26.0"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
` 
I have tried every solution I have found online, to no avail. If anyone has an idea as to what could be causing this / how to fix. I would really appreciate it.

If you need me to post any other files please let me know!

(device is running 10.3.1, xcode is Version 8.3.1 (8E1000a) )

**Comment by PanayotCankov** [comment]
Hi,
I have failed to reproduce the issue with both Xcode 8.2.1 and 8.3.2. Maybe I am missing something. Would you be so kind to also share the firebase.nativescript.json? Could you send us an app that can reproduces the problem? Perhaps there is some specific JavaScript code that has to execute to ask for the Bolts to load?

**Comment by SamuelGRwebfab** [comment]
@PanayotCankov sure thing,

Here is my firebase.nativescript.json file

`{
    "using_ios": true,
    "using_android": true,
    "remote_config": true,
    "messaging": true,
    "storage": true,
    "facebook_auth": true,
    "google_auth": true
}`

As for an app that reproduces the issue, I will start to make it now

**Comment by SamuelGRwebfab** [comment]
@PanayotCankov I ahve recreated the issue here https://github.com/SamuelGRwebfab/nativescript-ios-Bolts-issue

**Comment by vchimev** [comment]
I'm closing this stale issue. Please reopen if encounter it with recent versions of NativeScript.
