### ISSUE TITLE
Issue with parameter with space

### ISSUE THREAD

**Issue by kofrimpong** [NativeScript/nativescript-dev-webpack#123]
My keystore alias is a space-separated value. Webpack is unable to pass the parameter to tns build command. When I remove the space, it works alright but fails when it tries to verify the keystore. How do you pass space separated parameter.
I have tried both single and double quotes, but none has worked.

When I run tns build with the alias in quotes, it works, but not for webpack.

Using @ngtools/webpack 1.2.3 with tns-core-module 2.5.2

**Comment by sis0k0** [comment]
Hey @kofrimpong,

Can you post the exact command that you are trying to build with and the error log that you get?

**Comment by sis0k0** [comment]
Never mind, I saw that spawning a child process doesn't escape the passed arguments automatically. We'll fix soon. Thank you!
