### ISSUE TITLE
npm run start-ios-bundle reports a warning in terminal

### ISSUE THREAD

**Issue by gaurav-chandra** [NativeScript/nativescript-dev-webpack#130]
```npm run start-ios-bundle``` shows the following warning
![nswebpack](https://cloud.githubusercontent.com/assets/3168243/25324837/c54dad98-28e5-11e7-812f-ceb4c6947a10.png)

is this something we should be concerned about?

**Comment by sis0k0** [comment]
No, this won't cause the bundle to fail. I agree it's not nice to see warnings while building. Let's keep this issue open and we'll address this problem.

**Comment by sis0k0** [comment]
Fixes with 0.5.0
