### ISSUE TITLE
Remove comments and minify

### ISSUE THREAD

**Issue by lukashlobil** [NativeScript/nativescript-dev-webpack#131]
I am webpacking the app and it has reduced app size from 21MB to 14MB and slightly decreased loading time. 
I feel there are more time and size savings there. I want to introduce comment removal and minification, but webpack seems to be ignoring minify and remove comments flags. I even followed this guide https://medium.com/@enchev/minify-uglify-and-bundle-your-javascript-in-nativescript-angular-2-app-aabf84f47fbb, but it didn't accomplish anything.
Can someone please provide webpack config with working minification and remove comments?

**Comment by sis0k0** [comment]
You enable minification with `uglify` by passing the flag `--uglify` to the building command. For example:

```
npm run build-android-bundle --uglify
```

**Comment by lukashlobil** [comment]
Thanks, that seems to be doing something, it gets stuck on local storage plugin though.

> ERROR in bundle.js from UglifyJs
> Unexpected token: name (localStorageData) [bundle.js:75239,8]

It's the let localStorageData = {}; line in code below. I know you are not responsible for the plugin, but any hints what I have to do

```
const FileSystemAccess = __webpack_require__(/*! file-system/file-system-access */ 262).FileSystemAccess;

if (!global.localStorage) {
    let localStorageData = {};
    let localStorageTimeout = null;

    const internalSaveData = function() {
        let fsa = new FileSystemAccess();
        let fileName = fsa.getDocumentsFolderPath() + "/localStorage.db";
        try {
            fsa.writeText(fileName, JSON.stringify(localStorageData));
        } catch (err) {
            // This should never happen on normal data, but if they tried to put non JS stuff it won't serialize
            console.log("localStorage: unable to write storage, error: ", err);
        }
    };
```

**Comment by sis0k0** [comment]
That's weird.. I just tested it on a hello-world project (ng, tsc, plain js) and it works. Can you share some details about your project? `package.json` and `webpack.config.js` would be helpful.

**Comment by lukashlobil** [comment]
Sure: https://gist.github.com/lukashlobil/e7e81852cdc9e746fa7e79ac03cc6545
the webpack config is the default one though. 
The local storage plugin was recently updated to be webpack-ready, so I don't know, what's wrong. https://github.com/NathanaelA/nativescript-localstorage

**Comment by sis0k0** [comment]
I tried the provided package.json and the bundling worked like charm. I don't know what's causing the problem. You can try to upgrade `nativescript-dev-webpack` to 0.4.0 and then update the dependencies with the `./node_modules/.bin/update-ns-webpack` script. But it works fine with the current dependencies as well.

**Comment by lukashlobil** [comment]
Bundling works fine for me as well, when I provide the --uglify, it fails. I'll try your suggestion. Is there also a flag for comment removal?

**Comment by sis0k0** [comment]
I meant bundling with uglify worked for me. For the comments - they'll be removed by uglify if it's not configured otherwise in the webpack.config.js.

**Comment by lukashlobil** [comment]
I found the issue - it works now with a workaround. Thank you for the hint with uglify. The problem is my "javascript" version I had to replace the "let" keyword with "var" in the plugin's code. The weird thing is I use "let" in my code as well - seems like the plugin is compiled differently. I updated the gist my tsconfig and here is the code for the plugin: https://github.com/NathanaelA/nativescript-localstorage/blob/master/localstorage.js

**Comment by sis0k0** [comment]
It can be something with your typescript configuration. I'm glad you found a solution that worked for you. Can we close this now?

**Comment by lukashlobil** [comment]
I'll close, but please try to hint, which tsconfig do I look at? Only this plugin throws this error, others have "let" keyword as well.

**Comment by sis0k0** [comment]
It can be in both because the `aot` one extends the other. Do you have the same issue on a newly created project with the same plugin? Also are you building for iOS or Android?
