### ISSUE TITLE
bundling worker: "TypeError: Cannot read property 'newLine' of undefined"

### ISSUE THREAD

**Issue by m-abs** [NativeScript/nativescript-dev-webpack#139]
I'm trying to bundle a worker in our project, but I keep getting this error:
```bash
    ERROR in ../~/nativescript-dev-webpack/tns-aot-loader.js!../~/@ngtools/webpack/src!./worker.ts
    Module build failed: TypeError: Cannot read property 'newLine' of undefined
        at Object.getNewLineCharacter (/home/mabs/project/ns-debugging/bundle-worker/node_modules/typescript/lib/typescript.js:9426:20)
        at Object.createCompilerHost (/home/mabs/project/ns-debugging/bundle-worker/node_modules/typescript/lib/typescript.js:62475:26)
        at Object.ngcLoader (/home/mabs/project/ns-debugging/bundle-worker/node_modules/@ngtools/webpack/src/loader.js:338:33)
```

I've created a demo project here:
https://github.com/m-abs/ns-debugging/tree/master/bundle-worker

It's a very simple worker as you can see here: https://github.com/m-abs/ns-debugging/blob/master/bundle-worker/app/worker.ts

I'm using @triniwiz's [worker-loader](https://github.com/triniwiz/worker-loader) and test for `global.TNS_WEBPACK` as suggested in https://github.com/NativeScript/nativescript-dev-webpack/issues/86#issuecomment-282814229
Like this: https://github.com/m-abs/ns-debugging/blob/master/bundle-worker/app/app.module.ts#L32-L48

What am I doing wrong?

**Comment by m-abs** [comment]
Update:
If I transpile the worker's TS to JS myself, I can run the worker.
The resulting `[hash].worker.js` in my built is rather large after I had to import 'global' but it's progress.

I think it would be better if I could get webpack to transpile my worker.ts file for me.
Is this possible?

**Comment by hypery2k** [comment]
any workarounds? I'm getting this issue too

**Comment by m-abs** [comment]
Only the one I mentioned :) 

If you use `nativescript-dev-typescript` you might be able to get that to transpile it by running `tns prepare android` or `tns prepare ios` before running the build process.

**Comment by hypery2k** [comment]
doesn't for me with TNS3

**Comment by m-abs** [comment]
What if you require the worker from vendor.ts?

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by triniwiz** [comment]
@m-abs try https://github.com/TeamMaestro/nativescript-pspdfkit/blob/master/src/ios/pspdfkit.ts#L50-L56
