### ISSUE TITLE
Integration with i18n plugin fails

### ISSUE THREAD

**Issue by manojdcoder** [NativeScript/nativescript-dev-webpack#141]
@sis0k0 Here is the sample [project](https://github.com/manojdcoder/nativescript-webpack-sass/commit/52f21b2c04bffc27006c51db4db7c509dfb27be6) with i18n plugin integrated. Can you please take quick look and help us to find what is causing the issue.

```
ERROR in Error encountered resolving symbol values statically. Reference to a non-exported class L. Consider exporting the class (position 15:1 in the original .ts file), resolving symbol NativeScriptI18nModule in /Users/manojkumar/Backup/NativeScript_Workspace/nativescript-webpack-sass/node_modules/nativescript-i18n/angular.ts

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/Users/manojkumar/Backup/NativeScript_Workspace/nativescript-webpack-sass/app'
 @ ./main.aot.ts 5:29-62
```

**Comment by manojdcoder** [comment]
@sis0k0 Did you get a chance to look at this issue, can you please help me to understand whether it is a issue with plugin / web-pack?

**Comment by sis0k0** [comment]
Yes, the plugin doesn't have generated metadata for the exported NgModule and doesn't support AoT. Please open an issue in the plugin's repo.
