### ISSUE TITLE
Tracking issue for dirty (mixed) build failures

### ISSUE THREAD

**Issue by ishitatsuyuki** [NativeScript/nativescript-dev-webpack#145]
This is the tracking issue for gradlew failure on `:asbg:generateBindings`.

Workaround found:
```
rm platforms/android/build-tools/android-static-binding-generator/*.txt
```

The aim of this issue is to resolve the root cause of the problem. The check of duplicate entries was introduced in https://github.com/NativeScript/android-runtime/commit/53cc589822ef0395297d3120dec795737c698829.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#759
