### ISSUE TITLE
after installation webpack not found error

### ISSUE THREAD

**Issue by gaurav-chandra** [NativeScript/nativescript-dev-webpack#146]
After following instructions from here: https://docs.nativescript.org/tooling/bundling-with-webpack , whenever I do ```$ npm run build-android-bundle``` I get the following error:
![webpackerror](https://cloud.githubusercontent.com/assets/3168243/25793906/354d7996-33ec-11e7-8301-96aa3f0f36fd.png)
I have to manually install webpack and other dependencies for the ns webpack to run or I have to do ```npm install``` for it to run.

**Comment by sis0k0** [comment]
It's mentioned in the [README](https://github.com/NativeScript/nativescript-dev-webpack#usage). We'll update the documentation, too. Thank you!
