### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by SamuelGRwebfab** [NativeScript/nativescript-dev-webpack#158]
I just recently updated to NS 3.0. Doing so broke my webpack. I have tried to replicate the issue with another project using the exact same package.json. To no avail. I have seen issues similar to this one but none of the fixes worked for me.

Here is the full error 

`K:\apps\challengeApp\challengeApp\node_modules\typescript\lib\typescript.js:1487
6
            var sourceFile = new SourceFileConstructor(263 /* SourceFile */, /*p
os*/ 0, /* end */ sourceText.length);

                            ^

TypeError: Cannot read property 'length' of undefined
    at createSourceFile (K:\apps\challengeApp\challengeApp\node_modules\typescri
pt\lib\typescript.js:14876:109)
    at parseSourceFileWorker (K:\apps\challengeApp\challengeApp\node_modules\typ
escript\lib\typescript.js:14808:26)
    at Object.parseSourceFile (K:\apps\challengeApp\challengeApp\node_modules\ty
pescript\lib\typescript.js:14757:26)
    at Object.createSourceFile (K:\apps\challengeApp\challengeApp\node_modules\t
ypescript\lib\typescript.js:14612:29)
    at WebpackCompilerHost.getSourceFile (K:\apps\challengeApp\challengeApp\node
_modules\@ngtools\webpack\src\compiler_host.js:210:27)
    at findSourceFile (K:\apps\challengeApp\challengeApp\node_modules\typescript
\lib\typescript.js:64751:29)
    at processSourceFile (K:\apps\challengeApp\challengeApp\node_modules\typescr
ipt\lib\typescript.js:64682:27)
    at K:\apps\challengeApp\challengeApp\node_modules\typescript\lib\typescript.
js:64792:17
    at Object.forEach (K:\apps\challengeApp\challengeApp\node_modules\typescript
\lib\typescript.js:1398:30)
    at processReferencedFiles (K:\apps\challengeApp\challengeApp\node_modules\ty
pescript\lib\typescript.js:64790:16)
    at findSourceFile (K:\apps\challengeApp\challengeApp\node_modules\typescript
\lib\typescript.js:64775:21)
    at processSourceFile (K:\apps\challengeApp\challengeApp\node_modules\typescr
ipt\lib\typescript.js:64682:27)
    at processRootFile (K:\apps\challengeApp\challengeApp\node_modules\typescrip
t\lib\typescript.js:64570:13)
    at K:\apps\challengeApp\challengeApp\node_modules\typescript\lib\typescript.
js:63919:60
    at Object.forEach (K:\apps\challengeApp\challengeApp\node_modules\typescript
\lib\typescript.js:1398:30)
    at Object.createProgram (K:\apps\challengeApp\challengeApp\node_modules\type
script\lib\typescript.js:63919:16)
child process exited with code 1`

so it seems it has something to do with my typescript dependency. I have tried all sorts of version but have had no luck.

My package.json

`{
  "description": "myApp",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "Challenger",
  "repository": "myRepo",
  "nativescript": {
    "id": "org.nativescript.myApp",
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/platform-browser-dynamic": "~4.1.0",
    "@angular/platform-server": "~4.1.0",
    "@angular/router": "~4.1.0",
    "acorn-dynamic-import": "^2.0.2",
    "email-validator": "^1.0.7",
    "nativescript-angular": "^3.0.0",
    "nativescript-camera": "3.0.0",
    "nativescript-drop-down": "^3.0.1",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-firebase": "^3.11.4",
    "nativescript-telerik-ui": "2.0.1",
    "nativescript-toasty": "^1.1.5",
    "nativescript-videoplayer": "^3.0.5",
    "nativescript-videorecorder": "1.4.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "^3.0.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.0",
    "@ngtools/webpack": "1.3.1",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "css-loader": "~0.26.0",
    "extract-text-webpack-plugin": "~2.1.0",
    "filewalker": "0.1.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.4.0",
    "nativescript-dev-webpack": "^0.5.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "typescript": "~2.2.1",
    "webpack": "~2.5.1",
    "webpack-sources": "~0.2.3"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
`

If anyone has any idea what could be going on I would really appreciate it!

If you need any more info please let me know

**Comment by SamuelGRwebfab** [comment]
sorry I can never seem to get these code blocks right :/

**Comment by sis0k0** [comment]
Hey,
Please share the tsconfig.aot and webpack config, too.

**Comment by SamuelGRwebfab** [comment]
@sis0k0 

tsconfig.aot
`{
  "extends": "./tsconfig",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "ui/*": [ "node_modules/tns-core-modules/ui/*" ],
      "platform": [ "node_modules/tns-core-modules/platform" ],
      "image-source": [ "node_modules/tns-core-modules/image-source" ],
      "xml": [ "node_modules/tns-core-modules/xml" ],
      "xhr": [ "node_modules/tns-core-modules/xhr" ],
      "text": [ "node_modules/tns-core-modules/text" ],
      "data": [ "node_modules/tns-core-modules/data" ],
      "fetch": [ "node_modules/tns-core-modules/fetch" ],
      "trace": [ "node_modules/tns-core-modules/trace" ],
      "fps-meter": [ "node_modules/tns-core-modules/fps-meter" ],
      "color": [ "node_modules/tns-core-modules/color" ],
      "application-settings": [ "node_modules/tns-core-modules/application-settings" ],
      "http": [ "node_modules/tns-core-modules/http" ],
      "camera": [ "node_modules/tns-core-modules/camera" ],
      "console": [ "node_modules/tns-core-modules/console" ],
      "timer": [ "node_modules/tns-core-modules/timer" ],
      "utils": [ "node_modules/tns-core-modules/utils" ],
      "location": [ "node_modules/tns-core-modules/location" ],
      "file-system": [ "node_modules/tns-core-modules/file-system" ],
      "application": [ "node_modules/tns-core-modules/application" ],
      "image-asset": [ "node_modules/tns-core-modules/image-asset" ],
      "connectivity": [ "node_modules/tns-core-modules/connectivity" ],
      "globals": [ "node_modules/tns-core-modules/globals" ]
    }
  },
  "exclude": [
    "node_modules",
    "platforms"
  ],
  "angularCompilerOptions": {
    "skipMetadataEmit": true,
    "genDir": "./"
  }
}
`
webpack config


`const { resolve, join  } = require("path");

const webpack = require("webpack");
const nsWebpack = require("nativescript-dev-webpack");
const nativescriptTarget = require("nativescript-dev-webpack/nativescript-target");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const ExtractTextPlugin = require("extract-text-webpack-plugin");

const { AotPlugin } = require("@ngtools/webpack");

const mainSheet = `app.css`;

module.exports = env => {
    const platform = getPlatform(env);

    // Default destination inside platforms/<platform>/...
    const path = resolve(nsWebpack.getAppPath(platform));

    const entry = {
        // Discover entry module from package.json
        bundle: `./${nsWebpack.getEntryModule()}`,

        // Vendor entry with third-party libraries
        vendor: `./vendor`,

        // Entry for stylesheet with global application styles
        [mainSheet]: `./${mainSheet}`,
    };

    const rules = getRules();
    const plugins = getPlugins(platform, env);
    const extensions = getExtensions(platform);

    return {
        context: resolve("./app"),
        target: nativescriptTarget,
        entry,
        output: {
            pathinfo: true,
            path,
            libraryTarget: "commonjs2",
            filename: "[name].js",
        },
        resolve: {
            extensions,

            // Resolve {N} system modules from tns-core-modules
            modules: [
                "node_modules/tns-core-modules",
                "node_modules",
            ]
        },
        node: {
            // Disable node shims that conflict with NativeScript
            "http": false,
            "timers": false,
            "setImmediate": false,
            "fs": "empty",
        },
        module: { rules },
        plugins,
    };
};


function getPlatform(env) {
    return env.android ? "android" :
        env.ios ? "ios" :
        () => { throw new Error("You need to provide a target platform!") };
}

function getRules() {
    return [
        {
            test: /\.html$|\.xml$/,
            use: [
                "raw-loader",
            ]
        },
        // Root stylesheet gets extracted with bundled dependencies
        {
            test: new RegExp(mainSheet),
            use: ExtractTextPlugin.extract([
                {
                    loader: "resolve-url-loader",
                    options: { silent: true },
                },
                "nativescript-css-loader",
                "nativescript-dev-webpack/platform-css-loader",
            ]),
        },
        // Other CSS files get bundled using the raw loader
        {
            test: /\.css$/,
            exclude: new RegExp(mainSheet),
            use: [
                "raw-loader",
            ]
        },
        // SASS support
        {
            test: /\.scss$/,
            use: [
                "raw-loader",
                "resolve-url-loader",
                "sass-loader",
            ]
        },


        // Compile TypeScript files with ahead-of-time compiler.
        {
            test: /\.ts$/,
            loaders: [
                "nativescript-dev-webpack/tns-aot-loader",
                "@ngtools/webpack",
            ]
        }

    ];
}

function getPlugins(platform, env) {
    let plugins = [
        new ExtractTextPlugin(mainSheet),

        // Vendor libs go to the vendor.js chunk
        new webpack.optimize.CommonsChunkPlugin({
            name: ["vendor"],
        }),

        // Define useful constants like TNS_WEBPACK
        new webpack.DefinePlugin({
            "global.TNS_WEBPACK": "true",
        }),

        // Copy assets to out dir. Add your own globs as needed.
        new CopyWebpackPlugin([
            { from: mainSheet },
            { from: "css/**" },
            { from: "fonts/**" },
            { from: "**/*.jpg" },
            { from: "**/*.png" },
            { from: "**/*.xml" },
        ], { ignore: ["App_Resources/**"] }),

        // Generate a bundle starter script and activate it in package.json
        new nsWebpack.GenerateBundleStarterPlugin([
            "./vendor",
            "./bundle",
        ]),

        // Angular AOT compiler
        new AotPlugin({
            tsConfigPath: "tsconfig.aot.json",
            entryModule: resolve(__dirname, "app/app.module#AppModule"),
            typeChecking: false
        }),

        // Resolve .ios.css and .android.css component stylesheets
        new nsWebpack.StyleUrlResolvePlugin({platform}),

    ];
    
    if (env.uglify) {
        plugins.push(new webpack.LoaderOptionsPlugin({ minimize: true }));

        // Work around an Android issue by setting compress = false
        const compress = platform !== "android";
        plugins.push(new webpack.optimize.UglifyJsPlugin({
            mangle: { except: nsWebpack.uglifyMangleExcludes },
            compress,
        }));
    }

    return plugins;
}

// Resolve platform-specific modules like module.android.js
function getExtensions(platform) {
    return Object.freeze([
        `.${platform}.ts`,
        `.${platform}.js`,
        ".aot.ts",
        ".ts",
        ".js",
        ".css",
        `.${platform}.css`,
    ]);
}
`

I havent touched the webpack config since I was building for 2.5. Might b e the issue but im not quite sure what to change

**Comment by SamuelGRwebfab** [comment]
I tried to create a new porject to replicate this issue. However, using the same package.json, the same .aot files and the same config files I was unable to reproduce the issue in the new app. Do you have any idea what files I should be looking in to solve this issue?

**Comment by SamuelGRwebfab** [comment]
Ok so I managed to fix the issue. The way I did it makes zero sense to me but it may help others in the future so I will post it here.

First a made a new blank project and webpacked it.

Next i slowly brought over all of my dependencies but in the end I just copied all dependencies from my package.json.

That built just fine. This next step is where I am getting confused.

To makes things clear, my project that was not building will be called app1. The new empty project will be app2.

I copied app1's app folder and pasted it inside of app2, overwriting everything.

Next I deleted the app folder from app1. Tested webpacking app2 (it worked)

Then i copied the app folder from app2 (yes same code as it was in app1) then I pasted it back into app1.

After theses steps I am suddenly able to webpack my app. This makes zero sense to me but it worked. If anyone might know why this worked I would love to get to the bottom of it.

Hope this helps someone out!

**Comment by sean-perkins** [comment]
For future people that run into this problem (like myself), the issue is with the `references.d.ts` file. In my case, I had copied a section I had found online for applying typings for platform related things (iOS and Android).

Well.. they don't exist anymore in:
```
/// <reference path="./node_modules/tns-core-modules/lib.core.d.ts" />
```

And that was causing the exception to be thrown. You can find the problematic "typings file" causing the issue by logging the file name out in the line number given in the typescript stacktrace.
