### ISSUE TITLE
Unable to build on Win32 - Removing "gradle.properties" 

### ISSUE THREAD

**Issue by wanadu66** [NativeScript/nativescript-dev-webpack#161]
Hello, maybe there's already a fix to this issue but I couldn't find one.

The problem occurs when running "npm run start-android-bundle" or "npm run build-android-bundle".
Because the first action is always : 
"$>Removing platform android...
 $>Adding platform android@3.0.0..."
The consequence is a deletion of the configured "gradle.properties" and a replacement with a new one with default options ("org.gradle.jvmargs=-Xmx16384M"). The problem is that users on Win32 have to use a specific Gradle config for the JVM : 
"org.gradle.jvmargs=-Xms512M -Xmx1024M"
Other way it will land to the classic error : "Invalid maximum heap size: -Xmx16384M"

Maybe I'm not aware of a specific command to avoid removing platform ? Or any way to keep my gradle config ?

**Comment by sis0k0** [comment]
Workaround until 0.5.1 is released:

```
./node-modules/.bin/webpack --progress --env.android (or --env.ios)
tns run android/ios
```

**Comment by sis0k0** [comment]
Platforms are no longer removed with `0.6.0`.
