### ISSUE TITLE
getting an error module not found: using nativescript-cache while bundling

### ISSUE THREAD

**Issue by spmamidi** [NativeScript/nativescript-dev-webpack#162]
we are using this plugin - https://github.com/pocketsmith/nativescript-cache, every thing works fine with tns run android.

when to try to bundle using nativescript-dev-webpack getting following error.
Module not found: Error: Can't resolve 'nativescript-cache' in 'Y:\github\test-mobile\test\app\common'

Here is my code:
var cache = require("nativescript-cache");
cache.set("key1", "val1");

**Comment by sis0k0** [comment]
This needs to be fixed in the plugin: https://docs.nativescript.org/tooling/bundling-with-webpack#referencing-platform-specific-modules-from-packagejson

Open issue/PR in the plugin's repo.
