### ISSUE TITLE
start-[platform]-app scripts are wrong

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-dev-webpack#172]
On a brand new project if you add the webpack plugin and try to do `npm run start-android-app` it will fail, because it tries to execute `tns start` which is an invalid command. The scripts should be changed to the following values:
```
"start-[PLATFORM]-bundle": "npm run ns-bundle --[PLATFORM] --run-app"
```

**Comment by sis0k0** [comment]
10x, @PeterStaev

**Comment by luchillo17** [comment]
Just to show what the bug says:
![image](https://cloud.githubusercontent.com/assets/9698639/26793201/cb03eea0-49e2-11e7-8502-ebada4fa9bd1.png)

**Comment by luchillo17** [comment]
Any ETA on release? or just install from repo branch in github?

**Comment by sis0k0** [comment]
@luchillo17, it's already in npm (0.6.2). For existing affected projects you'll have to remove the `start-android/ios-bundle` scripts from your package.json and install the plugin anew. Then it will add the correct scripts.

**Comment by luchillo17** [comment]
How do you run AOT?
