### ISSUE TITLE
Release build parameters

### ISSUE THREAD

**Issue by mcrvaz** [NativeScript/nativescript-dev-webpack#177]
version: "nativescript-dev-webpack": "^0.6.1",
Just updated to the latest version and can't execute a release build with webpack anymore.
I'm running the following command:
`npm run build-android-bundle -- --release --keyStorePath my-app.keystore --keyStorePassword mypassword --keyStoreAlias my-alias --keyStoreAliasPassword mypassword`
It gives me this error: **The option 'keyStoreAlias' requires non-empty value.**

It works perfeclty with:
`tns build android --release --key-store-path my-app.keystore --key-store-password mypassword --key-store-alias my-alias --key-store-alias-password mypassword`

Also works with:
`npm start build-android-bundle`

**Comment by mcrvaz** [comment]
Seems to be an issue with aliases containing "-", it works with `--key-store-alias "myapp"` but not working with `--key-store-alias "my-app"`

**Comment by sis0k0** [comment]
I couldn't reproduce the issue. Can you please send the full log after executing the command?

**Comment by mcrvaz** [comment]
Here it is:
[npm-debug.log](https://gist.github.com/mcrvaz/9648d9b0d416673c780103927542d1fc)
It also happens on Ubuntu.

Other dependencies that were updated:
    "@ngtools/webpack": "1.4.0",
    "webpack": "2.6.1",
    "webpack-sources": "~1.0.1",

**Comment by sis0k0** [comment]
Great, but that won't be enough. We'll need everything printed on the console.

**Comment by mcrvaz** [comment]
Ok, this should do [console-log.txt](https://gist.github.com/mcrvaz/aa6c2ae3f778efbc464c0343b53cf730)

**Comment by ludcila** [comment]
Hi, I am trying to upgrade from NS 2.5 to 3.0, and I am also getting this error when I use a keystore alias that contains a dash.  Were you able to make it work?

**Comment by ludcila** [comment]
I think the problem is with aliases that end with *-app (that is my case).  They are parsed as tns commands:
https://github.com/NativeScript/nativescript-dev-webpack/commit/8e7a1b36ac1229b35fbb7ef120a921ffc6f66250

**Comment by mcrvaz** [comment]
I changed the alias and removed the dash, then it worked.

**Comment by ludcila** [comment]
Ok, thanks @mcrvaz :)
