### ISSUE TITLE
sass support it's broken

### ISSUE THREAD

**Issue by henrychavez** [NativeScript/nativescript-dev-webpack#178]
Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.0.3           │ 3.0.3          │ Up to date  │
│ tns-core-modules │ 3.0.1           │ 3.0.1          │ Up to date  │
│ tns-android      │ 3.0.1           │ 3.0.1          │ Up to date  │
│ tns-ios          │ 3.0.1           │ 3.0.1          │ Up to date  │

doesn't execute dev-sass hook before-prepare when I run the command npm run start-android-bundle

**Comment by DickSmith** [comment]
I've had this issue for some months, my workaround was to run `node -e 'require(\"./node_modules/nativescript-dev-sass/lib/converter.js\").convert(console, \".\");'` before a webpack.

**Comment by PeterStaev** [comment]
This seems was an issue introduced with 3.0. I managed tackle this with a custom setting for the `CopyWebpackPlugin` that copies and compiles SASS files (note, this is for non-Angular app):

```js
const sass = require("node-sass");
// .....

function getPlugins(platform, env) {
    let plugins = [
        new ExtractTextPlugin("[name].css"),

        // Vendor libs go to the vendor.js chunk
        new webpack.optimize.CommonsChunkPlugin({
            name: ["vendor"],
        }),

        // Define useful constants like TNS_WEBPACK
        new webpack.DefinePlugin({
            "global.TNS_WEBPACK": "true",
        }),

        // Copy assets to out dir. Add your own globs as needed.
        new CopyWebpackPlugin([
            // { from: mainSheet },
            { from: "fonts/**" },
            { from: "**/*.jpg" },
            { from: "**/*.png" },
            { from: "**/*.xml" },
            {
                from: "**/*.scss",
                to: "[path][name].css",
                ignore:["**/*.android.scss", "**/*.ios.scss", "**/_*.scss"],
                transform: transformSass,
            },
            {
                from: `**/*.${platform}.scss`,
                to: "[path][name].css",
                transform: transformSass,
            },            
        ], { ignore: ["App_Resources/**"] }),

        // Generate a bundle starter script and activate it in package.json
        new nsWebpack.GenerateBundleStarterPlugin([
            "./vendor",
            "./bundle",
        ]),
    ];
    
    // .......
    return plugins;
}

function transformSass(content, path) {
    return sass.renderSync({
        file: path,
        sourceMap: false,
        outputStyle: "compressed"
    }).css
}
```

**Comment by mn-martin** [comment]
The actual issue is not that the before-prepare hook is not running. That's intended. Also there's no additional work to be done in order to have Sass support. That's built in. What is actually going painfully wrong is that the app.css file simply does not exist at the time webpack is looking for it if you're following the official naming conventions from https://docs.nativescript.org/angular/ui/theme.html#sass-usage

A simple fix is:

move your app/app.ios.scss and app/app.android.scss files into a styles directory. Add a new file app/app.css with the following content:

```css
@import "styles/app.css";
```

Now run tns build android --clean && npm run start-android-bundle for example and everything should be working fine.

**Comment by aldo-roman** [comment]
Hi everyone,

In any case, the ideal scenario would be to have an "AngularCLI-like" experience. I speak coming from Angular-for-web usage, exploring Angular-for-mobile here.

The steps would be:

0. create the app with `tns create my-app`
1. run `tns install sass`
2. rename `app.css` → `app.scss`
3. within the components
`styleUrls: ['./my.component.css']` → `styleUrls: ['./my.component.scss']`

For most of us, Webpack is a must, so giving Webpack + SASS support out-of-the-box would be awesome.

I've been trying to get this running and cannot get this running yet.

Thanks!

**Comment by sis0k0** [comment]
The issue should be resolved with v0.9.0. For scss usage, you can check out the demo apps in the repo: https://github.com/NativeScript/nativescript-dev-webpack/tree/master/demo

**Comment by gsmedley** [comment]
I'm seeing the same thing - scss files not compiled when using the --bundle option, css not applied to running application.

**Comment by DickSmith** [comment]
@gsmedley 

For the latest webpack and sass plugins, I have more or less:

`app/scss/` with all the `_*.scss` files in it including a `_index.scss` that imports most the other `_*.scss` and then a platform specific `_overrides.(android|ios).scss`

`app/app.android.scss`:
``` scss
@import 'scss/index';
@import 'scss/overrides.android';
```
`app/app.android.scss`:
``` scss
@import 'scss/index';
@import 'scss/overrides.ios';
```

That should work both with and without the `--bundle` option without any additional changes.

**Comment by gsmedley** [comment]
@DickSmith  Thanks - this is now working for me as well. Not sure exactly what I changed, but getting scss compiled and css files installed.

**Comment by davorpeic** [comment]
I think this is still the issue, using latest dev/sass `tns run ios` works fine, `tns run ios --bundle` doesn't build component scss->css
