### ISSUE TITLE
Problem with android aot compilation

### ISSUE THREAD

**Issue by naturalfreak** [NativeScript/nativescript-dev-webpack#183]
I got this error during Android AOT compilation

> Project successfully created.
> Running webpack for android...
>  10% building modules 0/2 modules 2 active ...ove/Improve-application/app/vendor.ts(node:1263) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
> parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
> Hash: b6a781e2b537589be250                                                               
> Version: webpack 2.6.1
> Time: 24696ms
>                           Asset       Size  Chunks                    Chunk Names
>                       bundle.js    3.03 MB       0  [emitted]  [big]  bundle
>                      app.css.js  267 bytes       1  [emitted]         app.css
>                       vendor.js    2.96 MB       2  [emitted]  [big]  vendor
>                         app.css    1.46 kB       1  [emitted]         app.css
>               fonts/icomoon.ttf     130 kB          [emitted]         
>   fonts/fontawesome-webfont.ttf     166 kB          [emitted]         
> fonts/MaterialIcons-Regular.ttf     128 kB          [emitted]         
>                    package.json   25 bytes          [emitted]         
>                      starter.js   41 bytes          [emitted]         
>             tns-java-classes.js    0 bytes          [emitted]         
>    [1] ../~/@angular/core/@angular/core.es5.js 468 kB {2} [built]
>    [3] ../~/@angular/router/@angular/router.es5.js 211 kB {2} [built]
>   [10] ../~/@angular/common/@angular/common.es5.js 130 kB {2} [built]
>   [12] ./config.ts 3.42 kB {0} [built]
>   [14] ../~/tns-core-modules/platform/platform.android.js 5.75 kB {2} [built]
>   [18] ../~/@angular/forms/@angular/forms.es5.js 203 kB {2} [built]
>   [57] ../~/@angular/http/@angular/http.es5.js 74.7 kB {2} [built]
>   [63] ../~/@angular/platform-browser/@angular/platform-browser.es5.js 142 kB {2} [built]
>  [100] ../~/reflect-metadata/Reflect.js 48 kB {2} [built]
>  [290] ./app.module.ngfactory.ts 49.3 kB {0} [built]
>  [291] ./vendor-platform.android.ts 1.06 kB {2} [built]
>  [293] ./app.css 41 bytes {1} [built]
>  [311] ./main.aot.ts 515 bytes {0} [built]
>  [376] ./vendor.ts 394 bytes {2} [built]
>  [729] ../~/nativescript-css-loader/lib/css-base.js 1.51 kB [built]
>     + 715 hidden modules
> Child app/app.html:
>        [0] ./app.html 6.04 kB {0} [built]
> Child app/pages/Main/index.html:
>        [0] ./pages/Main/index.html 14.7 kB {0} [built]
> Child app/pages/SignIn/index.html:
>        [0] ./pages/SignIn/index.html 3.04 kB {0} [built]
> Child app/pages/SignUp/index.html:
>        [0] ./pages/SignUp/index.html 10.6 kB {0} [built]
> Child app/pages/UserInfo/index.html:
>        [0] ./pages/UserInfo/index.html 506 bytes {0} [built]
> Child app/pages/Places/index.html:
>        [0] ./pages/Places/index.html 542 bytes {0} [built]
> Child app/pages/CreateReport/index.html:
>        [0] ./pages/CreateReport/index.html 5.54 kB {0} [built]
> Child app/pages/PlaceInfo/index.html:
>        [0] ./pages/PlaceInfo/index.html 1.1 kB {0} [built]
> Child app/pages/UpdatePlan/index.html:
>        [0] ./pages/UpdatePlan/index.html 6.28 kB {0} [built]
> Child app/pages/BusinessPanel/index.html:
>        [0] ./pages/BusinessPanel/index.html 429 bytes {0} [built]
> Child app/pages/BusinessCreateVoucher/index.html:
>        [0] ./pages/BusinessCreateVoucher/index.html 3.51 kB {0} [built]
> Child app/pages/Report/index.html:
>        [0] ./pages/Report/index.html 12.8 kB {0} [built]
> Child app/pages/BusinessProfilePicture/index.html:
>        [0] ./pages/BusinessProfilePicture/index.html 379 bytes {0} [built]
> Child app/pages/Performers/index.html:
>        [0] ./pages/Performers/index.html 4.23 kB {0} [built]
> Child app/pages/UserProfile/index.html:
>        [0] ./pages/UserProfile/index.html 4.67 kB {0} [built]
> Child app/pages/UserSettings/index.html:
>        [0] ./pages/UserSettings/index.html 19.6 kB {0} [built]
> Child app/pages/UserVouchers/index.html:
>        [0] ./pages/UserVouchers/index.html 2.67 kB {0} [built]
> Child app/pages/UserPOIS/index.html:
>        [0] ./pages/UserPOIS/index.html 2.36 kB {0} [built]
> Child app/pages/BusinessStatistics/index.html:
>        [0] ./pages/BusinessStatistics/index.html 6.23 kB {0} [built]
> Child app/pages/BusinessListPlaces/index.html:
>        [0] ./pages/BusinessListPlaces/index.html 1.26 kB {0} [built]
> Child app/pages/BusinessPlaces/index.html:
>        [0] ./pages/BusinessPlaces/index.html 4.52 kB {0} [built]
> Child app/pages/BusinessListVouchers/index.html:
>        [0] ./pages/BusinessListVouchers/index.html 3.13 kB {0} [built]
> Child app/pages/BusinessReports/index.html:
>        [0] ./pages/BusinessReports/index.html 7.87 kB {0} [built]
> Child app/pages/BusinessSendVoucher/index.html:
>        [0] ./pages/BusinessSendVoucher/index.html 2.86 kB {0} [built]
> Child app/pages/BusinessListPosts/index.html:
>        [0] ./pages/BusinessListPosts/index.html 1.42 kB {0} [built]
> Child app/pages/BusinessCreatePost/index.html:
>        [0] ./pages/BusinessCreatePost/index.html 828 bytes {0} [built]
> Child app/pages/BusinessMenu/index.html:
>        [0] ./pages/BusinessMenu/index.html 567 bytes {0} [built]
> Child app/pages/Notifications/index.html:
>        [0] ./pages/Notifications/index.html 2.24 kB {0} [built]
> Child app/pages/CreateReportGM/index.html:
>        [0] ./pages/CreateReportGM/index.html 13.2 kB {0} [built]
> Child app/pages/NoInternetConnection/index.html:
>        [0] ./pages/NoInternetConnection/index.html 863 bytes {0} [built]
> Child app/pages/Main/style.css:
>        [0] ./pages/Main/style.css 2.81 kB {0} [built]
> Child app/pages/SignIn/style.css:
>        [0] ./pages/SignIn/style.css 1.03 kB {0} [built]
> Child app/pages/SignUp/style.css:
>        [0] ./pages/SignUp/style.css 1.87 kB {0} [built]
> Child app/pages/UserInfo/style.css:
>        [0] ./pages/UserInfo/style.css 1.25 kB {0} [built]
> Child app/pages/Places/style.css:
>        [0] ./pages/Places/style.css 19 bytes {0} [built]
> Child app/pages/CreateReport/style.css:
>        [0] ./pages/CreateReport/style.css 2.72 kB {0} [built]
> Child app/pages/PlaceInfo/style.css:
>        [0] ./pages/PlaceInfo/style.css 19 bytes {0} [built]
> Child app/pages/UpdatePlan/style.css:
>        [0] ./pages/UpdatePlan/style.css 1.24 kB {0} [built]
> Child app/pages/BusinessPanel/style.css:
>        [0] ./pages/BusinessPanel/style.css 19 bytes {0} [built]
> Child app/pages/BusinessCreateVoucher/style.css:
>        [0] ./pages/BusinessCreateVoucher/style.css 2.06 kB {0} [built]
> Child app/pages/Report/style.css:
>        [0] ./pages/Report/style.css 3.25 kB {0} [built]
> Child app/pages/BusinessProfilePicture/style.css:
>        [0] ./pages/BusinessProfilePicture/style.css 19 bytes {0} [built]
> Child app/pages/Performers/style.css:
>        [0] ./pages/Performers/style.css 1.19 kB {0} [built]
> Child app/pages/UserProfile/style.css:
>        [0] ./pages/UserProfile/style.css 1.84 kB {0} [built]
> Child app/pages/UserSettings/style.css:
>        [0] ./pages/UserSettings/style.css 1.27 kB {0} [built]
> Child app/pages/UserVouchers/style.css:
>        [0] ./pages/UserVouchers/style.css 1.01 kB {0} [built]
> Child app/pages/UserPOIS/style.css:
>        [0] ./pages/UserPOIS/style.css 705 bytes {0} [built]
> Child app/pages/BusinessStatistics/style.css:
>        [0] ./pages/BusinessStatistics/style.css 872 bytes {0} [built]
> Child app/pages/BusinessListPlaces/style.css:
>        [0] ./pages/BusinessListPlaces/style.css 530 bytes {0} [built]
> Child app/pages/BusinessPlaces/style.css:
>        [0] ./pages/BusinessPlaces/style.css 763 bytes {0} [built]
> Child app/pages/BusinessListVouchers/style.css:
>        [0] ./pages/BusinessListVouchers/style.css 983 bytes {0} [built]
> Child app/pages/BusinessReports/style.css:
>        [0] ./pages/BusinessReports/style.css 1.36 kB {0} [built]
> Child app/pages/BusinessSendVoucher/style.css:
>        [0] ./pages/BusinessSendVoucher/style.css 1.01 kB {0} [built]
> Child app/pages/BusinessListPosts/style.css:
>        [0] ./pages/BusinessListPosts/style.css 617 bytes {0} [built]
> Child app/pages/BusinessCreatePost/style.css:
>        [0] ./pages/BusinessCreatePost/style.css 634 bytes {0} [built]
> Child app/pages/BusinessMenu/style.css:
>        [0] ./pages/BusinessMenu/style.css 196 bytes {0} [built]
> Child app/pages/Notifications/style.css:
>        [0] ./pages/Notifications/style.css 1.08 kB {0} [built]
> Child app/pages/CreateReportGM/style.css:
>        [0] ./pages/CreateReportGM/style.css 3.43 kB {0} [built]
> Child app/pages/NoInternetConnection/style.css:
>        [0] ./pages/NoInternetConnection/style.css 734 bytes {0} [built]
> Child extract-text-webpack-plugin:
>        [0] ../~/nativescript-css-loader/lib/css-base.js 1.51 kB {0} [built]
>        [1] ../~/resolve-url-loader?{"silent":true,"absolute":false,"sourceMap":false,"fail":false,"keepQuery":false,"debug":false,"root":null}!../~/nativescript-css-loader?{"minimize":false}!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css 1.76 kB {0} [built]
> Running tns start...
> Unknown command 'start'. Use 'tns help' for help.
> Did you mean?
> 	appstore
> 	create
> 	install
> 	platform

package.json

> "dependencies": {
>     "@angular/animations": "^4.1.3",
>     "@angular/common": "^4.1.3",
>     "@angular/compiler": "^4.1.3",
>     "@angular/core": "^4.1.3",
>     "@angular/forms": "^4.1.3",
>     "@angular/http": "^4.1.3",
>     "@angular/platform-browser": "^4.1.3",
>     "@angular/platform-browser-dynamic": "^4.1.3",
>     "@angular/router": "^4.1.3",
>     "ios-uuid": "./packages/ios-uuid-1.0.0.tgz",
>     "loading-indicator": "./packages/loading-indicator-1.0.0.tgz",
>     "nativescript-angular": "^3.0.0",
>     "nativescript-camera": "^3.0.0",
>     "nativescript-facebook": "^2.0.0",
>     "nativescript-fresco": "^3.0.2",
>     "nativescript-geolocation": "^3.0.0",
>     "nativescript-google-maps-sdk": "^2.1.3",
>     "nativescript-imagepicker": "^3.0.1",
>     "nativescript-iqkeyboardmanager": "^1.0.1",
>     "nativescript-push-notifications": "^0.1.3",
>     "nativescript-socket.io": "^0.5.1",
>     "nativescript-telerik-ui": "^2.0.1",
>     "nativescript-telerik-ui-pro": "./packages/nativescript-ui-pro.tgz",
>     "reflect-metadata": "^0.1.10",
>     "rxjs": "~5.4.0",
>     "tns-core-modules": "^3.0.1",
>     "zone.js": "~0.8.11"
>   },
>   "devDependencies": {
>     "@angular/compiler-cli": "~4.1.3",
>     "@ngtools/webpack": "1.4.0",
>     "babel-traverse": "6.24.1",
>     "babel-types": "6.24.1",
>     "babylon": "6.17.0",
>     "codelyzer": "^3.0.0",
>     "copy-webpack-plugin": "~4.0.1",
>     "extract-text-webpack-plugin": "~2.1.0",
>     "filewalker": "^0.1.3",
>     "jasmine-core": "^2.4.1",
>     "karma": "^1.6.0",
>     "karma-jasmine": "^1.0.2",
>     "karma-nativescript-launcher": "^0.4.0",
>     "lazy": "1.0.11",
>     "nativescript-css-loader": "~0.26.1",
>     "nativescript-dev-typescript": "^0.4.5",
>     "nativescript-dev-webpack": "^0.6.2",
>     "raw-loader": "~0.5.1",
>     "resolve-url-loader": "~2.0.2",
>     "tslint": "^5.3.2",
>     "typescript": "^2.3.4",
>     "webpack": "~2.6.1",
>     "webpack-sources": "~0.2.3"
>   }
> 

webpack.config.js

```
const { resolve, join  } = require("path");

const webpack = require("webpack");
const nsWebpack = require("nativescript-dev-webpack");
const nativescriptTarget = require("nativescript-dev-webpack/nativescript-target");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const ExtractTextPlugin = require("extract-text-webpack-plugin");

const { AotPlugin } = require("@ngtools/webpack");

const mainSheet = `app.css`;

module.exports = env => {
    const platform = getPlatform(env);

    // Default destination inside platforms/<platform>/...
    const path = resolve(nsWebpack.getAppPath(platform));

    const entry = {
        // Discover entry module from package.json
        bundle: `./${nsWebpack.getEntryModule()}`,

        // Vendor entry with third-party libraries
        vendor: `./vendor`,

        // Entry for stylesheet with global application styles
        [mainSheet]: `./${mainSheet}`,
    };

    const rules = getRules();
    const plugins = getPlugins(platform, env);
    const extensions = getExtensions(platform);

    return {
        context: resolve("./app"),
        target: nativescriptTarget,
        entry,
        output: {
            pathinfo: true,
            path,
            libraryTarget: "commonjs2",
            filename: "[name].js",
        },
        resolve: {
            extensions,

            // Resolve {N} system modules from tns-core-modules
            modules: [
                "node_modules/tns-core-modules",
                "node_modules",
            ]
        },
        node: {
            // Disable node shims that conflict with NativeScript
            "http": false,
            "timers": false,
            "setImmediate": false,
            "fs": "empty",
        },
        module: { rules },
        plugins,
    };
};


function getPlatform(env) {
    return env.android ? "android" :
        env.ios ? "ios" :
        () => { throw new Error("You need to provide a target platform!") };
}

function getRules() {
    return [
        {
            test: /\.html$|\.xml$/,
            use: [
                "raw-loader",
            ]
        },
        // Root stylesheet gets extracted with bundled dependencies
        {
            test: new RegExp(mainSheet),
            use: ExtractTextPlugin.extract([
                {
                    loader: "resolve-url-loader",
                    options: { silent: true },
                },
                {
                    loader: "nativescript-css-loader",
                    options: { minimize: false }
                },
                "nativescript-dev-webpack/platform-css-loader",
            ]),
        },
        // Other CSS files get bundled using the raw loader
        {
            test: /\.css$/,
            exclude: new RegExp(mainSheet),
            use: [
                "raw-loader",
            ]
        },
        // SASS support
        {
            test: /\.scss$/,
            use: [
                "raw-loader",
                "resolve-url-loader",
                "sass-loader",
            ]
        },


        // Compile TypeScript files with ahead-of-time compiler.
        {
            test: /\.ts$/,
            loaders: [
                "nativescript-dev-webpack/tns-aot-loader",
                "@ngtools/webpack",
            ]
        }

    ];
}

function getPlugins(platform, env) {
    let plugins = [
        new ExtractTextPlugin(mainSheet),

        // Vendor libs go to the vendor.js chunk
        new webpack.optimize.CommonsChunkPlugin({
            name: ["vendor"],
        }),

        // Define useful constants like TNS_WEBPACK
        new webpack.DefinePlugin({
            "global.TNS_WEBPACK": "true",
        }),

        // Copy assets to out dir. Add your own globs as needed.
        new CopyWebpackPlugin([
            { from: mainSheet },
            { from: "css/**" },
            { from: "fonts/**" },
            { from: "**/*.jpg" },
            { from: "**/*.png" },
            { from: "**/*.xml" },
        ], { ignore: ["App_Resources/**"] }),

        // Generate a bundle starter script and activate it in package.json
        new nsWebpack.GenerateBundleStarterPlugin([
            "./vendor",
            "./bundle",
        ]),

        // Angular AOT compiler
        new AotPlugin({
            tsConfigPath: "tsconfig.aot.json",
            entryModule: resolve(__dirname, "app/app.module#AppModule"),
            typeChecking: false
        }),

        // Resolve .ios.css and .android.css component stylesheets, and .ios.html and .android component views
        new nsWebpack.UrlResolvePlugin({
            platform: platform,
            resolveStylesUrls: true,
            resolveTemplateUrl: true
        }),

    ];
    
    if (env.uglify) {
        plugins.push(new webpack.LoaderOptionsPlugin({ minimize: true }));

        // Work around an Android issue by setting compress = false
        const compress = platform !== "android";
        plugins.push(new webpack.optimize.UglifyJsPlugin({
            mangle: { except: nsWebpack.uglifyMangleExcludes },
            compress,
        }));
    }

    return plugins;
}

// Resolve platform-specific modules like module.android.js
function getExtensions(platform) {
    return Object.freeze([
        `.${platform}.ts`,
        `.${platform}.js`,
        ".aot.ts",
        ".ts",
        ".js",
        ".css",
        `.${platform}.css`,
    ]);
}

```

tsconfig.json

> {
>     "compilerOptions": {
>         "module": "commonjs",
>         "target": "es5",
>         "experimentalDecorators": true,
>         "emitDecoratorMetadata": true,
>         "noEmitHelpers": true,
>         "noEmitOnError": true,
>         "lib": [
>             "es6",
>             "dom",
>             "es2015.iterable"
>         ],
>         "baseUrl": ".",
>         "paths": {
>             "*": [
>                 "./node_modules/tns-core-modules/*",
>                 "./node_modules/*"
>             ]
>         }
>     },
>     "exclude": [
>         "node_modules",
>         "platforms",
>         "**/*.aot.ts"
>     ]
> }

tsconfig.aot.json

> 
> {
>   "extends": "./tsconfig",
>   "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "application": ["node_modules/tns-core-modules/application"],
>       "application-settings": ["node_modules/tns-core-modules/application-settings"],
>       "camera": ["node_modules/tns-core-modules/camera"],
>       "color": ["node_modules/tns-core-modules/color"],
>       "connectivity": ["node_modules/tns-core-modules/connectivity"],
>       "console": ["node_modules/tns-core-modules/console"],
>       "data/*": ["node_modules/tns-core-modules/data/*"],
>       "fetch": ["node_modules/tns-core-modules/fetch"],
>       "file-system": ["node_modules/tns-core-modules/file-system"],
>       "fps-meter": ["node_modules/tns-core-modules/fps-meter"],
>       "globals": ["node_modules/tns-core-modules/globals"],
>       "http": ["node_modules/tns-core-modules/http"],
>       "image-asset": ["node_modules/tns-core-modules/image-asset"],
>       "image-source": ["node_modules/tns-core-modules/image-source"],
>       "location": ["node_modules/tns-core-modules/location"],
>       "platform": ["node_modules/tns-core-modules/platform"],
>       "text": ["node_modules/tns-core-modules/text"],
>       "timer": ["node_modules/tns-core-modules/timer"],
>       "trace": ["node_modules/tns-core-modules/trace"],
>       "ui/*": ["node_modules/tns-core-modules/ui/*"],
>       "utils/*": ["node_modules/tns-core-modules/utils/*"],
>       "xhr": ["node_modules/tns-core-modules/xhr"],
>       "xml": ["node_modules/tns-core-modules/xml"]
>     },
>     "skipLibCheck": true
>   },
>   "exclude": [
>     "node_modules",
>     "platforms"
>   ],
>   "angularCompilerOptions": {
>     "skipMetadataEmit": true,
>     "genDir": "./"
>   }
> }
> 
>

**Comment by danielgek** [comment]
@naturalfreak take a look at #172
