### ISSUE TITLE
Cannot find module 'shelljs'

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-dev-webpack#2]
On a newly created app, if I run `tns install webpack`, and then `tns build android --bundle`, I get an error about a missing 'shelljs' module. If I `npm install shelljs --save-dev` the problem goes away.

**Comment by tjvantoll** [comment]
Actually this is almost certainly unrelated to this plugin. Should the CLI install a package’s `devDependencies` when you run `tns install`. If so I’ll move this issue there.

**Comment by hdeshev** [comment]
Fixed in 0.0.14
