### ISSUE TITLE
How best to handle Angular Directive, Pipe, Component with .ios or .android suffix?

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-dev-webpack#200]
I encountered this today and was not sure the best way forward. Curious if the core team has encountered this and how best things like this should be handled with AoT and Angular:
<img width="939" alt="screen shot 2017-06-27 at 1 35 12 pm" src="https://user-images.githubusercontent.com/457187/27608809-ac165cbe-5b3d-11e7-9ce3-51296c1a89bd.png">
<img width="1013" alt="screen shot 2017-06-27 at 1 35 24 pm" src="https://user-images.githubusercontent.com/457187/27608808-ac156e6c-5b3d-11e7-88da-094a429bcf28.png">

Here the `.d.ts` is merely used to satisfy the TypeScript compiler for the imports. In development, {N} builds the `.ios` and `.android` files into `.js` for the platform and causes no issue. However when run through this webpack plugin with AoT, this error is seen:

> ERROR in Cannot determine the module for class SlimSliderDirective in /MyApp/app/modules/player/directives/slider.directive.android.ts! Add SlimSliderDirective to the NgModule to fix it.
Cannot determine the module for class SlimSliderDirective in /MyApp/app/modules/player/directives/slider.directive.ios.ts! Add SlimSliderDirective to the NgModule to fix it.

Stumped. Any ideas? 

/cc @vakrilov @sis0k0 @hdeshev @vchimev @ivanbuhov @PeterStaev

**Comment by rowandh** [comment]
Similar issue with files ending in .debug and .release

**Comment by sis0k0** [comment]
Heya,

Here's an idea how to fix this - tell the tsc/ngc compiler which files to compile. It would be enough to only specify the bootstrapping file - in most cases `./app/main.ts`. You'll need to specify that in `tsconfig.aot.json` since that's the configuration used when building with webpack:

``` tsconfig.aot.json
{
  "extends": "./tsconfig",
  "compilerOptions": {
    ...
  },
  ...
  "files": "./app/main.ts"
}
```
* you can drop the 'exclude' option from the config. 

Give it a try :)
We'll consider including this setting by default in the tsconfig.aot.json ;)

**Comment by NathanWalker** [comment]
@sis0k0 brilliant idea :)  I will try this soon and let ya' know and close this ticket if that does it - thank you once again!

**Comment by NathanWalker** [comment]
@sis0k0 it worked :) One important thing to keep in mind and should be documented somewhere (I'll actually be writing about this in an upcoming book to be published this summer) but when using:
```
"files": [
  "./app/main.ts"
]
```
If the app contains lazy loaded routes, those will throw new webpack errors like this:
```
ERROR in .. lazy
Module not found: Error: Can't resolve '/path/to/YourApp/app/modules/lazy.module.ngfactory.ts' in '/path/to/YourApp'
 @ .. lazy
 @ ../~/@angular/core/@angular/core.es5.js
 @ ./vendor.ts
```
This will require additions to files to include those of lazy loaded modules as well like this:
```
"files": [
  "./app/main.ts",
  "./app/modules/lazy.module.ts"
]
```
That will solve the above.
Then of course if any native api's are being used then they likely will also need to add those definitions:
```
"files": [
   "./app/main.ts",
    "./app/modules/lazy.module.ts"
    "./node_modules/tns-platform-declarations/ios.d.ts",
    "./node_modules/tns-platform-declarations/android.d.ts"
]
```

Since you have posted a PR (https://github.com/NativeScript/nativescript-dev-webpack/pull/205) to set a reasonable default to use "files" instead of "exculde", I'll let that PR close this issue.

Thanks again and perhaps the above could be added to the documentation somewhere to be clear.

**Comment by NathanWalker** [comment]
Well @sis0k0 perhaps I spoke too soon - that helps the app actually build successfully using webpack however when it is run I know see this and the app crashes:
```
JS ERROR Error: No NgModule metadata found for 'AppModule'.
```
Hmm.

**Comment by NathanWalker** [comment]
@sis0k0 Turns out my app was missing the `main.aot.ts` file. I was under impression that installing this plugin would automatically add that file however I went ahead and added it manually and that fixed the above error. I now have things bundling and it will run however the `slider.directive` functionality is completely ignored so the platform specific `.ios` and `.android` implementations are not used so this is still an issue unfortunately. Does anyone have any thoughts on how to solve this or is there a better way to setup platform specific components/directives with Angular which will work well with AoT?

**Comment by sis0k0** [comment]
@NathanWalker,

Yep, you're right. The above suggestion helps with ngc ignoring the files that are not used. But it looks like ngc doesn't use the resolve strategy that we provide in the [webpack config](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/templates/webpack.angular.js#L213-L224) but instead uses the default TypeScript [resolve method](https://github.com/angular/angular/blob/3097083277954e5f9917aee69ea05d4d8ffd12d0/packages/compiler-cli/src/compiler_host.ts#L73-L93).

What we can do in that case - create a custom webpack plugin that will find all imports and append some extension where necessary. For example:
```js
// webpack.config
new ImportReplacePlugin({ extensions: [ "android", "native" ] })
```

Then, if we have the following:
```
project/
    app/
        app.module.ts
        app.component.android.ts
        app.component.ios.ts
```

And we import the AppComponent in the AppModule like that:
```js
import { AppComponent } from './app.component';
```
Then the plugin should append `.android` to the import. What do you think?
@NathanWalker, @vakrilov

**Comment by vakrilov** [comment]
If I understand correctly - the real problem is ngc not using the webpack's resolve strategy. I think the petter approach would be to open and issue in on the `ngtools` repo to see what the angular team thinks about it.

Creating a "replace in files" plugin is always a solution, but usually not a sustainable one.

**Comment by NathanWalker** [comment]
Thank you @sis0k0 and @vakrilov - Agreed on the longterm solution of `ngtools` however short term solutions are great as well. This is an issue that will hold up an anticipated book release :)

**Comment by NathanWalker** [comment]
I have created a plugin to handle this case here:
https://github.com/NathanWalker/nativescript-webpack-import-replace
It parses the imports properly but I'm not doing the `node.text` replacement right.
Anyone have a small hint to finish this? (my first webpack plugin)
https://github.com/NathanWalker/nativescript-webpack-import-replace/blob/master/lib/ImportReplacePlugin.js#L81

**Comment by NathanWalker** [comment]
@vakrilov @sis0k0 this can now be resolved with this plugin:
https://github.com/NathanWalker/nativescript-webpack-import-replace
https://twitter.com/wwwalkerrun/status/885616481639088128
🎉 
Thank all for the help!
