### ISSUE TITLE
Support passing env variables to Webpack

### ISSUE THREAD

**Issue by rowandh** [NativeScript/nativescript-dev-webpack#203]
I have a scenario where I need to make 3 different builds with different configs:
- Developer build, use developer endpoint
- QA build, use QA endpoint and --release flags
- Prod build, use prod endpoint and --release flags

This is not going to be possible with the way ns-bundle is currently set up.

One solution would be to allow a different webpack.*.js path to be passed in to ns-bundle.

Another solution is for ns-bundle to parse --env.abc flags and pass them directly to webpack.config.js. In webpack.config it's then possible to do different things based on what env flags are set.

I'm not a heavy webpack user, so I'm not sure what the ideal solution is here.

**Comment by rowandh** [comment]
I created a PR at #204 to illustrate what I'm talking about. I've been using a variation of this ns-bundle locally to create different builds.

**Comment by sis0k0** [comment]
Merged with 49213211d9dafe97486db25ec4961bc8f4fb1444 . Will be release in the next patch version :)
