### ISSUE TITLE
Errors after upgrade

### ISSUE THREAD

**Issue by lukashlobil** [NativeScript/nativescript-dev-webpack#206]
I had a working configuration with nativescript 2.5.* and nativescript-dev-webpack 0.4.2. I have upgraded my the application to nativescript 3.1 and nativescript-dev-webpack 0.6.3. I changed angular and other dependencies to the ones mentione when you create new application with --ng flag. 
I made zero changes to actual code, just bumped up the dependencies. Now I get ton of errors - some are legit (typescript) and will be fixed, some are in ngFactories, some are in html templates like this:

> ERROR in /project/page1.component.ngfactory.ts (151,30): Property 'article' does not exist on type 'Page1'.

> ERROR in ng:///project/page1.component.ts.Page1.html (2,1): Property 'article' does not exist on type 'Page1'.

> ERROR in /project/page1.component.ts (21,36): Cannot find name 'java'.

These errors are only thrown when trying to use webpack after the upgrade. Upgraded app runs ok with tns run android. 

My package.json and tsconfig from last running webpack configuration: https://gist.github.com/lukashlobil/e7e81852cdc9e746fa7e79ac03cc6545
Now:
https://gist.github.com/lukashlobil/1ffe378bcd1ad2603d7f9919906caba8

Is there a way to skip over those errors? I can fix like 80% of them, but not all.
The build ends with 'child process exited with code 2'. Display-error-details doesn't give me anything either.

**Comment by sis0k0** [comment]
Hey @lukashlobil,

They are related to some additional checks that the Angular AoT compiler performs. I'm not sure if you can disable them, but here's how you can fix the above mentioned:

1. Private property
```
ERROR in ng:///project/page1.component.ts.Page1.html (2,1): Property 'article' does not exist on type 'Page1'.
```
Define the 'article' property as public in the component class, so you can access it from the template.

2. Undefined variable
```
ERROR in /project/page1.component.ts (21,36): Cannot find name 'java'.
```
Add typing for 'java'. The easiest way to solve: `declare var java`. Another way, probably better - include [tns-platform-declarations](https://www.npmjs.com/package/tns-platform-declarations) (there's a java module in the typings there).

Write back if you encounter another AoT errors :)

**Comment by lukashlobil** [comment]
Thank you @sis0k0 I will go through the list - good to know what is throwing the errors.
Most of it is basic and will be easy to handle.
Lot of it is moving stuff like 'page' from 'ui/page' to tns-core-modules'.

Currently stuck on this: ImageSourceModule.fromNativeSource(res);

**Comment by sis0k0** [comment]
Hey @lukashlobil, can you share more info about that error? The whole file would be perfect. Thanks :)
