### ISSUE TITLE
Error when executing "npm run build-android-bundle" with 3.1.1 on a project that is located in a directory path with "spaces"

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-dev-webpack#209]
When I run: "npm run build-android-bundle", I see following error:

Project successfully prepared (android)
Executing after-prepare hook from /Users/mivanova/Documents/Telerik/UI for NativeScript 3.0.1.304/Examples/SDKAngular/hooks/after-prepare/nativescript-unit-test-runner.js
/bin/sh: /Users/mivanova/Documents/Telerik/UI: No such file or directory
child process exited with code 127
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nativescript-telerik-ui-sdk-angular-examples@3.0.0 ns-bundle: `ns-bundle`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nativescript-telerik-ui-sdk-angular-examples@3.0.0 ns-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mivanova/.npm/_logs/2017-07-03T12_08_18_366Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-telerik-ui-sdk-angular-examples@3.0.0 build-android-bundle: `npm run ns-bundle --android --build-app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativescript-telerik-ui-sdk-angular-examples@3.0.0 build-android-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Here is my **package.json** file: 
"dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "nativescript-angular": "~3.1.0",
    "nativescript-fresco": "^3.0.2",
    "nativescript-intl": "^3.0.0",
    "nativescript-telerik-ui-pro": "../../packages/nativescript-ui-pro.tgz",
    "nativescript-unit-test-runner": "^0.3.2",
    "rxjs": "~5.3.0",
    "tns-core-modules": "3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.0.0",
    "@ngtools/webpack": "~1.4.0",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "chai": "^3.5.0",
    "codelyzer": "^3.0.0",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "filewalker": "0.1.3",
    "karma": "^1.6.0",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^1.3.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "mocha": "^3.3.0",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "^0.5.0",
    "nativescript-dev-webpack": "0.7.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "tns-platform-declarations": "~3.1.0",
    "tslint": "^5.1.0",
    "typescript": "~2.3.2",
    "webpack": "~3.0.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "tslint": "tslint --project tsconfig.json --config tslint.json",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }

**Comment by ivanpadavan** [comment]
I've got the same on ubuntu
