### ISSUE TITLE
Android: ClassNotFoundException NativeScriptActivity on newest NS version + newly created sample app

### ISSUE THREAD

**Issue by creambyemute** [NativeScript/nativescript-dev-webpack#21]
Hi there,

We were updating our Project to @angular 2.1.2 and @angular/router 3.1.2 and nativescript-angular 1.1.2 and also switched to the @next version of NativeScript.

The Webpack build runs fine on iOS but doesn't start on Android (immediate crash ClassNotFoundException: com.tns.NativeScriptActivity).

My tns info output:
┌──────────────────┬────────────────────────────┬────────────────┬─────────────┐
│ Component            │ Current version            │ Latest version │ Information │
│ nativescript            │ 2.5.0-2016-10-31-6971      │ 2.3.0          │ Up to date  │
│ tns-core-modules │ 2.5.0-2016-10-31-4629      │ 2.3.0          │ Up to date  │
│ tns-android            │ 2.5.0-next-2016-10-31-1332 │ 2.3.0          │ Up to date  │
│ tns-ios                    │ 2.5.0-2016-10-31-1         │ 2.3.0          │ Up to date  │
└──────────────────┴────────────────────────────┴────────────────┴─────────────┘

In order to verify it's not our project's fault (misconfiguration or whatever) I created a new sample app after I had updated to @next (2.5.0) version.

The problem is easily **reproducible** by doing the following:
1. tns create myWebpackSampleApp --ng
2. tns platform add ios && tns platform add android
3. Open package.json and specify tns-ios/tns-android version as "next" and add tns-core-modules dependency with version "next"
4. tns install webpack
5. Try to get the project running with Webpack, it'll always crash after startup with "ClassNotFoundException: com.tns.NativeScriptActivity"

My package.json of the sample app:
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.MySampleApp",
    "tns-ios": {
      "version": "2.5.0-2016-10-31-1"
    },
    "tns-android": {
      "version": "2.5.0-next-2016-10-31-1332"
    }
  },
  "dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "nativescript-angular": "1.1.2",
    "nativescript-theme-core": "^0.1.3",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "next"
  },
  "devDependencies": {
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "0.0.2",
    "nativescript-dev-typescript": "^0.3.2",
    "nativescript-dev-webpack": "0.0.20",
    "typescript": "^2.0.6",
    "zone.js": "~0.6.21"
  }
}

**Comment by creambyemute** [comment]
So we investigated further as it apparently worked on a colleagues computer and here are our findings:

The culprit actually was my gradle.properties file I had under /Users/myUser/.gradle/ and my content was the following:
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048M
org.gradle.configureondemand=true
org.gradle.parallel=true

I haven't tested yet which of these settings actually cause this problem but it's one of those.

Maybe add this as a warning to the README so that people are aware that their modified gradle.properties may break the build process and results in an malfunctioning app.

Cheers,

**Comment by PieterAelse** [comment]
Thanks, saved my day!
