### ISSUE TITLE
Upgrade to use Uglify-es branch

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-dev-webpack#212]
Please upgrade the nativescript-webpack code to use the ES code branch:

https://github.com/noBlubb/uglify-es-webpack-plugin

The issue is that if you used any ES6 code; and then attempt to use the `--uglify` flag; it will fail because uglify (non-es) doesn't support es6 constructs.

Some of my plugins are written as pure ES6, and so they cannot be webpacked with --uglify because of this issue...  In addition if TypeScript is set to emit ES6 code; this issue will also occur.

**Comment by terreb** [comment]
Any progress with this guys? I came across an issue when trying to use typescript powered Nativescript app + some plugins. Is there a recommended workaround to uglify es6 code until official support for es6+uglify is added?

**Comment by gabitoesmiapodo** [comment]
Any news on this?

If someone could share a workaround in the meantime, it would be nice.
