### ISSUE TITLE
use RadSideDrawerComponent for webpack project

### ISSUE THREAD

**Issue by behi1ty** [NativeScript/nativescript-dev-webpack#215]
hi
ERROR in Unexpected directive 'RadSideDrawerComponent in .../node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts' impor
ted by the module 'AppModule in .../app/app.module.ts'. Please add a @NgModule annotation.

import { SIDEDRAWER_DIRECTIVES, RadSideDrawerComponent } from "nativescript-telerik-ui/sidedrawer/angular";

 imports: [
...
        RadSideDrawerComponent
....
    ],
declarations: [
....
        SIDEDRAWER_DIRECTIVES,
....
]

**Comment by behi1ty** [comment]
help ...

**Comment by sis0k0** [comment]
Hey @behi1ty,

You will need to import the `NativeScriptUISideDrawerModule` instead of the `SIDEDRAWER_DIRECTIVES`. Here's how:

``` js
// ./app/app.module.ts

import { NativeScriptUISideDrawerModule } from "nativescript-telerik-ui-pro/sidedrawer/angular";
...
@NgModule({
    imports: [
       NativeScriptUISideDrawerModule,   
    ],
})
export class AppModule {...}

```

You can also check out the [NativeScript UI Plugin Documentation](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/getting-started).
