### ISSUE TITLE
support for both tns run android and npm run start-android-bundle

### ISSUE THREAD

**Issue by dvdbrk** [NativeScript/nativescript-dev-webpack#217]
Any ideas how to have a child routes loaded in a way that works with both `tns run android` and `npm run start-android-bundle --aot`?

In my app I can load a lazy module from one sub directory level only, but any subsequent sub directories can not be found.

For example, in `app-routing` I have default route:

```
  {
    path: "",
    loadChildren: "./level1/level1.module#Level1Module"
  },
```

Then in `level1-routing`:

```
{
  path: "level-2",
  loadChildren: "./level2/level2.module#Level2Module"
},
```

So this reports an error when using `tns run android`: 
`JS: ERROR Error: Uncaught (in promise): Error: com.tns.NativeScriptException: Failed to find module: "/data/data/org.test.app/files/app/./level2/level2.module", relative to: app//`

When running `npm run start-android-bundle --aot` the above paths work well.

To fix this for the `tns run android` I need to use absolute paths - and then it works (but fails for webpack build). Any ideas?

**Comment by sis0k0** [comment]
Hey @dvdbrk,

You need to use the `NSModuleFactoryLoader` distributed by `nativescript-angular` instead of the built-in `SystemJSModuleLoader` from `@angular`. You should provide the loader in your root module (let's say that's the `AppModule`) like that:

``` js
// ./app/app.module.ts
import { NSModuleFactoryLoader } from "nativescript-angular/router";
...

@NgModule({
   providers: [
        { provide: NgModuleFactoryLoader, useClass: NSModuleFactoryLoader }
    ]
...
})
export class AppModule { ... }
```

Here's an example project demonstrating the above solution - https://github.com/sis0k0/lazyNinjas/tree/aot (make sure you look at the `aot` branch).

Feel free to reopen if you still have issues with lazy-loading and webpack :)

**Comment by pako8x** [comment]
I would like to reopen the issue because the **sis0k0** solution is valid when we only have one child module level. Creating a child module of 'ninjas.module.ts' (related 'lazyNinjas' example), the problem is reproduced.

**Comment by dvdbrk** [comment]
Yes, my experience is the same, the proposed solution does not work.

**Comment by sis0k0** [comment]
Hey, @dvdbrk @pako8x ! Can you share a sample app with reproduction of the problem? Also you can check out the [nested lazy modules branch](https://github.com/sis0k0/lazyNinjas/tree/nested-lazy-modules) of the above repo.

**Comment by pako8x** [comment]
Ok, i succeeded in reproducing the problem by changing the following classes to the lazyNinjas project:

## **Case 1 - absolute path**
**app/ninjas/ninjas.routes.ts** - modified

```
import { NinjasComponent } from "./ninjas.component";

export const routes = [
    {
        path: "",
        component: NinjasComponent,
        children: [

            {
                path: '',
                loadChildren: './ninjas/ninjas-child/ninjas-child.module#NinjasChildModule'
            },
        ],
    }
];
```

**app/ninjas/ninjas.component.ts** - modified

```
import { Component } from "@angular/core";

@Component({
    template: `        
        <StackLayout>
            <Label text="Ninjas!" class="h1 text-center"></Label>
                <router-outlet></router-outlet>
            <Button text="Go back home" class="btn btn-primary btn-active"
                [nsRouterLink]="['/']"></Button>
        </StackLayout>
    `
})
export class NinjasComponent {
}
```

**app/ninjas/ninjas-child/ninjas-child.component.ts** - created

```
import {Component} from "@angular/core";

@Component ({

    template: `<Label text="Ninjas Children!!!" class="h1 text-center"></Label>`

})

export class NinjasChildComponent {
}
```

**app/ninjas/ninjas-child/ninjas-child.module.ts** - created

```
import { NgModule } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import {NinjasChildComponent} from "./ninjas-child.component";

const routes = [
    { path: '', component: NinjasChildComponent }
];

@NgModule({

    imports: [
        NativeScriptModule,
        NativeScriptRouterModule,
        NativeScriptRouterModule.forChild(routes)
    ],
    declarations: [NinjasChildComponent]
})
export class NinjasChildModule { }
```

Using `tns run android` the app starts and works fine, 
While `npm run start-android-bundle` returns this error message:

> ERROR in Could not resolve "./ninjas/ninjas-child/ninjas-child.module" from "C:/Users/pako8/Documents/IdeaProjects/{NS}/lazyNinjas/app/ninjas/ninjas.module.ts"

## **Case 2 - relative path** 

changing the module path in:
**app/ninjas/ninjas.routes.ts**
`loadChildren: './ninjas/ninjas-child/ninjas-child.module#NinjasChildModule'`

In this case `npm run start-android-bundle` the app starts and works fine, 
while `tns run android` the app crashes in runtime when I click the button **LOAD THE LAZY NINJAS MODULE**  returning the error:

> ERROR Error: Uncaught (in promise): Error: com.tns.NativeScriptException: Failed to find module: "/data/data/org.nativescript.lazyNinjas/files/app/./ninjas-child/ninjas-child.module", relative to: app//

**Comment by pako8x** [comment]
Ok, I found this work around awaiting a better solution. Certainly it isn't the most elegant method, but for now it works...
I applied this solution to the lazyNinjas project already modified by me above...

**app/services/environment.service.ts** - created

```
import {Injectable, Input} from '@angular/core';

export const env = {

    relativeModulePath: './',
    absoluteModulePath: './ninjas/'

};

@Injectable()
export class isWebpackBuild {

    static status: boolean = true;
}
```
**app/ninjas/ninjas.routes.ts** - modified

```
import { NinjasComponent } from "./ninjas.component";
import {env, isWebpackBuild} from "../services/environment.service";

const path = isWebpackBuild.status ? env.relativeModulePath : env.absoluteModulePath;

export const routes = [
    {
        path: "",
        component: NinjasComponent,
        children: [

            {
                path: '',
                loadChildren: path + 'ninjas-child/ninjas-child.module#NinjasChildModule'
            },
        ],
    }
];
```
**app/main.ts** - modified

```
import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import { AppModule } from "./app.module";
import { isWebpackBuild } from "./services/environment.service";

isWebpackBuild.status = false;

const platform = platformNativeScriptDynamic();
platform.bootstrapModule(AppModule);
```

in this way you can take advantage of the fact that while `tns run <platform>` uses main.ts as entry point, `npm run start-android-bundle`  uses main.aot.ts.

I hope this can help.... regards

**Comment by dvdbrk** [comment]
@pako8x amazing, thank you, gonna try it now.

Any ideas how to make this work for many nested levels? `absoluteModulePath: './ninjas/'` only helps with first nested route, what about `./ninjas/child-of-ninja/` case (cause it will also fail)?

**Comment by pako8x** [comment]
@dvdbrk sure... what I did is just be able to intercept the type of build from inside the app.
