### ISSUE TITLE
Support webpack 2

### ISSUE THREAD

**Issue by nakedcity** [NativeScript/nativescript-dev-webpack#22]
Solved by adjusting webpack configuration and after-prepare hook

Here you have it fully working https://github.com/camiloazula/sample-native-babel

**Comment by hdeshev** [comment]
We'll release an update for the plugin for the NativeScript 2.4 release that will use webpack 2 by default.

**Comment by nakedcity** [comment]
Thanks, I saw it already  in an upcoming branch. Have you scheduled it in any milestone yet?

**Comment by hdeshev** [comment]
Released today as 0.2.11. Please check the updated [documentation article](http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html) since the new version is not backwards compatible.
