### ISSUE TITLE
Release builds failing on both iOS and Android

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-dev-webpack#220]
I’ve stumbled upon a fairly odd problem that’s unfortunately preventing me from performing release builds. Here’s the app: https://github.com/tjvantoll/pokemon-types.

Building the app using this repo’s webpack plugin works.

```
npm run ns-bundle --android --build-app --snapshot --uglify
```

And building the app in release mode works as well.

```
tns build android --release --key-store-path ~/Dropbox/Mobile-config/tjvantoll.jks --key-store-password myPassword --key-store-alias Pokemontypes --key-store-alias-password myPassword
```

However, building with the webpack plugin AND release mode... fails with no obvious error.

```
npm run ns-bundle --android --build-app --snapshot --uglify --release --key-store-path ~/Dropbox/Mobile-config/tjvantoll.jks --key-store-password myPassword --key-store-alias Pokemontypes --key-store-alias-password myPassword
```

* Here’s a log of the failing run: https://gist.github.com/tjvantoll/4c4bb2cbe8b8907c2297ff4e96987295
* And here’s a log of that run with trace debugging on: https://gist.github.com/tjvantoll/733bced3ceb1bfd68a434dfe46be8f26

Any idea what the problem might be here? I’ve looked through similar issues and can’t find anything that works. I have the same problem doing iOS release builds. I’ve also tried deleting my `platforms` folder before trying these runs. You can use [my app’s repo](https://github.com/tjvantoll/pokemon-types) to recreate this problem.

Any help would be greatly appreciated. Thanks!

**Comment by ju4nj3** [comment]
+1

A simple project with two pages is not working if I put second page under folder /views.

I register the module as it says this page and this sample configuration:
https://docs.nativescript.org/best-practices/bundling-with-webpack#debugging-bundling-errors
https://github.com/NickIliev/NativeScript-Cosmos-Databank/blob/master/app/bundle-config.ts

My bundle-config.js:
global.registerModule("pages/main-page", function () { return require("./pages/main-page"); });
global.registerModule("views/second", () => require("./views/second"));

Also I removed in webpack.config.js the CSS bundle to get the individual CSS files to pages working.

But javascript breaks. The only way to get it working is moving the files up to /app folder.

Any thoughts?

**Comment by sis0k0** [comment]
Thanks for the report, guys! Can you share what OS are you building on and also the used versions of node and npm?

**Comment by tjvantoll** [comment]
Hey @sis0k0,

I’m on...

* macOS—10.12.5
* Node—6.9.1
* npm—3.10.8

**Comment by ju4nj3** [comment]
Hi @sis0k0 

I use two platforms regularly. Tested on both with same results:

- Windows 10 1703
- node 6.11.0
- npm 3.10.10

- Mac OS 10.12.5
- node 6.11.0
- npm 3.10.10

**Comment by Cayan** [comment]
I'm having the exactly same problem.
TNS builds with a keystore are working fine.
Webpack is working fine.
When I try to create a release with both, webpack + keystore release it crashes without any info.

Node version: v7.10.1
Npm version: v4.2.0
OS: Linux Mint 18.2

The build error log:
https://gist.github.com/Cayan/ad1216876cdda08d0d2a07aaccc14595

Yarn.lock:
https://gist.github.com/Cayan/e5d975e3a1622cf34ca40a7f29564701

**Comment by spike1292** [comment]
I have the same problem, but I think I found root cause for the problem:
the tns args are escaped twice, see https://github.com/NativeScript/nativescript-dev-webpack/blob/master/bin/ns-bundle#L25 and here https://github.com/NativeScript/nativescript-dev-webpack/blob/master/bin/ns-bundle#L213

Output for `escapedArgs` on line 213
```javascript
[ '"prepare"',
  '"ios"',
  '"--bundle"',
  '"--disable-npm-install"',
  '""--for-device""',
  '""--team-id""',
  '""22WTPDX2ZZ""',
  '""--provision""',
  '""match""',
  '""Development""',
  '""nl.energiedirect.selfserviceapp""' ]
```

If I remove the `.map(escapeWithQuotes)` from line 25 it works fine for me.

**Comment by Cayan** [comment]
The problem is still happening for me, same output. I have manually applied this patch and I also tried with the next version, both with the same output.

**Comment by tjvantoll** [comment]
Just tried the patch out and it works great for me. Thanks @sis0k0! 🎉 

@Cayan Did you make sure to remove your `platforms` folder before trying this again? Here’s a built version of the plugin that includes the patch: https://www.dropbox.com/s/ohavq4n92fo7zxf/nativescript-dev-webpack.tgz?dl=0. Use `npm install --save /path/to/nativescript-dev-webpack.tgz` to give it a shot.

**Comment by spike1292** [comment]
Awesome! works like a charm😉

**Comment by Cayan** [comment]
Thanks @tjvantoll 
With the next version:
diff -r package/ ~/Documents/mobile/node_modules/nativescript-dev-webpack
Only in /home/cayan/Documents/mobile/node_modules/nativescript-dev-webpack: node_modules

**I finally made it work**
It was related to https://github.com/NativeScript/nativescript-dev-webpack/issues/177, I had the alias using something-app

I also had to add a '--' before the other parameters

**Comment by tjvantoll** [comment]
Ah! Good to hear. I know these release issues can be maddening so sorry you hit problems here.

**Comment by jogboms** [comment]
For some reason, i'm experiencing this same issues. Running a similar command to this.
`npm run ns-bundle --android --build-app --snapshot --uglify --release --key-store-path ~/Dropbox/Mobile-config/tjvantoll.jks --key-store-password myPassword --key-store-alias Pokemontypes --key-store-alias-password myPassword`

**Comment by jogboms** [comment]
@tjvantoll could there be any reasons as to why this may occur? as i have tried everything suggested already but still nothing seems to cut it.

**Comment by tjvantoll** [comment]
@jogboms With those version numbers I’m not sure. I’d recommend posting your problem to the [NativeScript community forum](https://discourse.nativescript.org/) and including a full log of the problem.

If the community can’t help you out, you could next create a new issue on this repo.

Best of luck, I know these release build issues can be super frustrating :( The more information you can provide the better chance we have to help you out.
