### ISSUE TITLE
Error Module not found: Error: Can't resolve './app.module.ngfactory'

### ISSUE THREAD

**Issue by joey0xx** [NativeScript/nativescript-dev-webpack#224]
When I run `npm run start-android-bundle` I get the following error:

```
ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'C:\Users\MyName\Documents\Project\app'
 @ ./main.aot.ts 5:29-62
```

I'm getting the error on a project that was created before aot was implemented to NS. Did what it says on this page [http://docs.nativescript.org/angular/best-practices/bundling-with-webpack#angular-and-ahead-of-time-compilation](http://docs.nativescript.org/angular/best-practices/bundling-with-webpack#angular-and-ahead-of-time-compilation) , but still getting the error. Is there something missing?

**Comment by jibon57** [comment]
I am having same problem with Lazyloading. Error:

```
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 19:49 in the original .ts file), resolving symbol appRoutes in D:/Others/Documents/My_Work/NativeScript/app/routing.ts, resolving symbol routing in D:/Others/Documents/My_Work/NativeScript/app/routing.ts, resolving symbol routing in D:/Others/Documents/My_Work/NativeScript/app/routing.ts, resolving symbol AppModule in D:/Others/Documents/My_Work/NativeScript/app/app.module.ts, resolving symbol AppModule in D:/Others/Documents/My_Work/NativeScript/app/app.module.ts

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'D:\Others\Documents\My_Work\NativeScript\app'
 @ ./main.aot.ts 4:29-62
```

**Comment by sis0k0** [comment]
Can you send the full error log?

**Comment by caferrari** [comment]
```

$ npm run start-android-bundle

> @ start-android-bundle /home/caferrari/projetos/abrafarma-mobile
> npm run ns-bundle --android --run-app


> @ ns-bundle /home/caferrari/projetos/abrafarma-mobile
> ns-bundle

Running tns prepare...
Executing before-prepare hook from /home/caferrari/projetos/abrafarma-mobile/hooks/before-prepare/nativescript-dev-sass.js
Executing before-prepare hook from /home/caferrari/projetos/abrafarma-mobile/hooks/before-prepare/nativescript-dev-typescript.js
Executing before-prepare hook from /home/caferrari/projetos/abrafarma-mobile/hooks/before-prepare/nativescript-plugin-firebase.js
Preparing project...
Project successfully prepared (android)
Executing after-prepare hook from /home/caferrari/projetos/abrafarma-mobile/hooks/after-prepare/firebase-build-gradle.js
Configure firebase
Executing after-prepare hook from /home/caferrari/projetos/abrafarma-mobile/hooks/after-prepare/firebase-copy-google-services.js
Copy /home/caferrari/projetos/abrafarma-mobile/app/App_Resources/Android/google-services.json to /home/caferrari/projetos/abrafarma-mobile/platforms/android/google-services.json.
Executing after-prepare hook from /home/caferrari/projetos/abrafarma-mobile/hooks/after-prepare/nativescript-dev-sass.js
All SASS source files removed from app package
Executing after-prepare hook from /home/caferrari/projetos/abrafarma-mobile/hooks/after-prepare/nativescript-plugin-firebase.js
Running webpack for android...
 10% building modules 0/3 modules 3 active ...etos/abrafarma-mobile/app/main.aot.ts(node:10582) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: 82a48dcb2f0643668abd                                                              
Version: webpack 3.2.0
Time: 5756ms
                  Asset       Size  Chunks                    Chunk Names
fonts/MaterialIcons.ttf     261 kB          [emitted]  [big]  
              bundle.js  881 bytes       0  [emitted]         bundle
              vendor.js    3.01 MB       2  [emitted]  [big]  vendor
                app.css    0 bytes       1  [emitted]         app.css
  fonts/FontAwesome.ttf     166 kB          [emitted]         
     fonts/OpenSans.ttf     217 kB          [emitted]         
             app.css.js  269 bytes       1  [emitted]         app.css
       fonts/Roboto.ttf     161 kB          [emitted]         
       images/apple.jpg     277 kB          [emitted]  [big]  
           package.json  149 bytes          [emitted]         
             starter.js   39 bytes          [emitted]         
    tns-java-classes.js    0 bytes          [emitted]         
 [110] .. lazy 160 bytes {2} [built]
 [158] ./main.aot.ts 465 bytes {0} [built]
 [202] ./vendor.ts 471 bytes {2} [built]
 [203] ./vendor-platform.android.ts 528 bytes {2} [built]
 [255] ./app.css 41 bytes {1} [built]
    + 252 hidden modules

ERROR in Cannot determine the module for class AppComponent in /home/caferrari/projetos/abrafarma-mobile/app/pages/app/app.ts! Add AppComponent to the NgModule to fix it.

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/home/caferrari/projetos/abrafarma-mobile/app'
 @ ./main.aot.ts 5:29-62
Child extract-text-webpack-plugin /home/caferrari/projetos/abrafarma-mobile/node_modules/extract-text-webpack-plugin/dist /home/caferrari/projetos/abrafarma-mobile/node_modules/resolve-url-loader/index.js??ref--1-1!/home/caferrari/projetos/abrafarma-mobile/node_modules/nativescript-css-loader/index.js??ref--1-2!/home/caferrari/projetos/abrafarma-mobile/node_modules/nativescript-dev-webpack/platform-css-loader.js!/home/caferrari/projetos/abrafarma-mobile/app/app.css:
       [0] ../node_modules/resolve-url-loader?{"silent":true,"absolute":false,"sourceMap":false,"fail":false,"keepQuery":false,"debug":false,"root":null,"includeRoot":false}!../node_modules/nativescript-css-loader?{"minimize":false}!../node_modules/nativescript-dev-webpack/platform-css-loader.js!./app.css 167 bytes {0} [built]
        + 1 hidden module
Webpack Bundle Analyzer saved stats file to /home/caferrari/projetos/abrafarma-mobile/report/stats.json
Webpack Bundle Analyzer saved report to /home/caferrari/projetos/abrafarma-mobile/report/report.html
child process exited with code 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ ns-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/caferrari/.npm/_logs/2017-07-17T14_11_53_852Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ start-android-bundle: `npm run ns-bundle --android --run-app`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ start-android-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/caferrari/.npm/_logs/2017-07-17T14_11_53_871Z-debug.log

```

**Comment by sis0k0** [comment]
@caferrari,

You must have declared a class named `AppComponent` with @Component decorator in that file - `/home/caferrari/projetos/abrafarma-mobile/app/pages/app/app.ts`. The Angular compiler need to know where which is the parent module of each component in the project directory at compile time. So you need to either import the above component in some NgModule, or remove it if it shouldn't be in the project.

**Comment by caferrari** [comment]
@sis0k0 

I did it... that's why i haven't mentioned this error, there are my component and module:

app.component.ts
```
import { Component, OnInit } from '@angular/core';

import { Color } from 'color';
import { Page } from 'ui/page';

@Component({
  moduleId: module.id,
  selector: 'ns-app',
  template: '<page-router-outlet></page-router-outlet>'
})
export class AppComponent implements OnInit {
  constructor(
    private page: Page
  ) {
  }

  public ngOnInit(): void {
    this.page.backgroundSpanUnderStatusBar = true;
    this.page.androidStatusBarBackground = new Color('#0972AB');
  }
}
```

app.module.ts
```
import { DatePipe } from '@angular/common';
import { LOCALE_ID } from '@angular/core';
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { NativeScriptFormsModule, NativeScriptHttpModule } from 'nativescript-angular';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app.routing';
import { ComponentsModule } from './components';
import { GuardsModule } from './guards';
import { PagesMoule } from './pages';
import { PipeModule } from './pipes';
import { ProvidersModule } from './providers';
import { ServicesModule } from './service';

@NgModule({
  bootstrap: [
    AppComponent
  ],
  declarations: [
    AppComponent
  ],
  imports: [
    NativeScriptModule,
    NativeScriptHttpModule,
    NativeScriptFormsModule,
    ReactiveFormsModule,
    AppRoutingModule,
    ComponentsModule,
    ProvidersModule,
    ServicesModule,
    PipeModule,
    PagesMoule,
    GuardsModule
  ],
  providers: [
    DatePipe,
    { provide: LOCALE_ID, useValue: "pt-BR" },
  ],
  schemas: [
    NO_ERRORS_SCHEMA
  ]
})

export class AppModule { }
```

**Comment by sis0k0** [comment]
@caferrari,

Well, that's the reason the compilation is failing. Make sure you are looking at the right file:

```
/home/caferrari/projetos/abrafarma-mobile/app/pages/app/app.ts
```

**Comment by caferrari** [comment]
Thanks, I had two app.ts in two locations. Refactoring Mistakes ><..

but not I've got another problem =/ i'll create a new issue =)

**Comment by sis0k0** [comment]
Closing this. @joey0xx, @jibon57, please post another issue with the full error logs.

**Comment by force-push-master** [comment]
Have the same problem. Check for app.ts duplicates, everything is ok. Could anybody helps me? Pinned my structure and log file:

![default](https://user-images.githubusercontent.com/34840675/34342201-0647fd30-e9b1-11e7-82f5-e819e0afd422.PNG)

$ npm run serve

> movieon@0.0.0 serve C:\dev\project\movieon
> webpack-dev-server --inline --progress

 10% building modules 1/1 modules 0 active                                      Project is running at http://localhost:8080/
webpack output is served from /       Hash: cd931f8d6e6abb24ea1e                Version: webpack 3.10.0
Time: 11596ms
        Asset       Size  Chunks                    Chunk Names
app.bundle.js    2.71 MB       0  [emitted]  [big]  main
   index.html  186 bytes          [emitted]
 [135] ./node_modules/core-js/modules/core.is-iterable.js 373 bytes {0} [built]
 [148] multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.ts 40 bytes {0} [built]
 [149] (webpack)-dev-server/client?http://localhost:8080 7.95 kB {0} [built]
 [150] ./node_modules/url/url.js 23.3 kB {0} [built]
 [157] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
 [159] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} [built]
 [160] (webpack)-dev-server/client/socket.js 1.05 kB {0} [built]
 [162] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
 [167] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
 [169] (webpack)/hot/emitter.js 77 bytes {0} [built]
 [171] ./src/main.ts 384 bytes {0} [built]
 [172] ./node_modules/core-js/index.js 640 bytes {0} [built]
 [383] ./node_modules/reflect-metadata/Reflect.js 48 kB {0} [built]
 [385] ./node_modules/zone.js/dist/zone.js 126 kB {0} [built]
 [386] ./node_modules/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js 5.88 kB {0} [built]
    + 399 hidden modules

WARNING in ./node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.ts

WARNING in ./node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.ts

ERROR in C:\dev\project\movieon\src\app\app.module.ts
[tsl] ERROR in C:\dev\project\movieon\src\app\app.module.ts(3,9)
      TS2305: Module '"C:/dev/project/movieon/src/app/app.component"' has no exported member 'AppComponent'.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/app.module' in 'C:\dev\project\movieon\src'
 @ ./src/main.ts 7:19-46
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.ts
Child html-webpack-plugin for "index.html":
     1 asset
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs 538 bytes {0} [built]
       [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Failed to compile.

**Comment by jogboms** [comment]
@force-push-master I can't help but notice this line within the error

`Module '"C:/dev/project/movieon/src/app/app.component"' has no exported member 'AppComponent'.`

Could you confirm if the component is actually being exported?

**Comment by force-push-master** [comment]
@jogboms Yep, it exported, but may be not correctly? Please see:

![default](https://user-images.githubusercontent.com/34840675/34342968-ee338a8e-e9c9-11e7-9562-767f072c53fc.PNG)

**Comment by jogboms** [comment]
Okay, I see but I'm a bit confused, is this a Nativescript project?

**Comment by force-push-master** [comment]
It's Angular 2 project with typescript on board.

**Comment by jogboms** [comment]
This is not a Nativescript project.
