### ISSUE TITLE
Taps are not fired

### ISSUE THREAD

**Issue by Johnny1102** [NativeScript/nativescript-dev-webpack#227]
I need to use nativescript-dev-webpack in my app. I have installed everything, according to the tutorial [here](https://docs.nativescript.org/best-practices/bundling-with-webpack) .

When I run the app with this command: `npm run start-ios-bundle`

The taps events doesn't works.

I have button in login.xml:
`<Button text="login" tap="loginButtonTap" />`

and function in login.ts:
```
export function loginButtonTap(args : observableModule.EventData) {
    console.log("tap");
}
```

Do you know where can be a problem?

Only issues which occurred during the compilations are these warnings:
```
WARNING in ../node_modules/everlive-sdk/dist/everlive.all.js
Module not found: Error: Can't resolve 'local-settings' in '/node_modules/everlive-sdk/dist'
 @ ../node_modules/everlive-sdk/dist/everlive.all.js 30:423-448
 @ ./app.ts

WARNING in ../node_modules/everlive-sdk/dist/everlive.all.js
Module not found: Error: Can't resolve 'nativescript-sqlite' in '/node_modules/everlive-sdk/dist'
 @ ../node_modules/everlive-sdk/dist/everlive.all.js 30:656-686
 @ ./app.ts
```

Thank you

**Comment by NickIliev** [comment]
Hey, @Johnny1102 I have created [this test project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/nativescript-dev-webpack/issue_227) and bundle it with Webpack and taps are working as expected on my side. 
PLease  provide  a sample project demonstrating your specific case so we could investigate further
