### ISSUE TITLE
gradlewClean fails if path name contains a space

### ISSUE THREAD

**Issue by rowandh** [NativeScript/nativescript-dev-webpack#228]
Windows machine, running the command:
`npm run build-android-bundle --uglify`

**Comment by NickIliev** [comment]
@rowandh can you provide more details about your environment (Windows, Mac, Linux)

**Comment by sis0k0** [comment]
Thanks for logging the problem, @rowandh. The build is failing if you are building for Android on Windows, you have spaces in your cwd and when your globally installed nativescript-cli is version 3.0.1 or below. It's because of the way node spawns new child processes.

**Comment by rowandh** [comment]
The scenario @sis0k0 describes is what I am experiencing, but I'm running nativescript-cli 3.1.2

I had success with this:
`        spawnChildProcess(escapeWithQuotes(gradlew), "-p", platformsPath, "clean")
`

But I'm not sure if it will affect other platforms

**Comment by sis0k0** [comment]
@rowandh, are you using Windows? Also this method shouldn't be called if you are using that version of the CLI and that may be a greater problem. I'll check it out.

**Comment by rowandh** [comment]
@sis0k0 Yep, using Windows. I should have mentioned that this happens when running --uglify, which seems to short circuit the version check.

**Comment by sis0k0** [comment]
We are not executing `gradlewClean` since v0.9.0. This shouldn't be a problem anymore.
