### ISSUE TITLE
[Webpack Troubleshooting] Angular's app.module.ngfactory.ts file bundle error

### ISSUE THREAD

**Issue by felipebernardes** [NativeScript/nativescript-dev-webpack#237]
Hey folks,

When running `npm run build-android-bundle` I'm getting the following error: `ERROR in /<project path>/app/app.module.ngfactory.ts (285,55): Supplied parameters do not match any signature of call target.`

I know how to so solve this signature problem, but I don't know where exactly it's happening, since there isn't any function calls in my app.module besides `NativeScriptRouterModule.forRoot(appRoutes)`.

I wish I could check the `app.module.ngfactory.ts` file, but I can't find it anywhere. Could anyone please help me?

+package info: 
`
"angular": "4.1.1",
"tns-core-modules": "3.1.0",
"nativescript-angular": "3.0.0",
`

**Comment by m-abs** [comment]
`app.module.ngfactory.ts` is generated by the angular compiler from the `app.module.ts`-file, you won't be able to find it when you're bundling with webpack.

When I encounter errors with the `app.module.ngfactory.ts` (or other .ngfactory.ts-files), I try to run `ngc` myself to get better error output.
Please note: This will generate some files in your project, these shouldn't be committed.

1. Open a terminal and go into the project folder.
2. Run: `./node_modules/.bin/ngc -p tsconfig.aot.ts`
3. You'll now have the `app.module.ngfactory.ts` so you can see the line it complained about. 
4. From here you need to figure out where it comes from? It could be something from the template or the way you configured your NgModule or something else.

I hope this points you in the right direction.
