### ISSUE TITLE
Problem with registerElement

### ISSUE THREAD

**Issue by jibon57** [NativeScript/nativescript-dev-webpack#253]
Hello,

I ain't sure how I will explain. I am facing problem when I am trying to use custom element like this:

```
import { registerElement } from "nativescript-angular/element-registry";
registerElement("Gif", () => require("nativescript-gif").Gif);
registerElement("CardView", () => require("nativescript-cardview").CardView);
```
HTML:
```
<Gif src="~/assets/icon/login_load.gif" visibility="{{ loadingImg ? 'visible' : 'collapsed' }}" height="44"></Gif>
<CardViewclass="cardStyle" margin="10" elevation="40" radius="1">
</CardView>
```

![screenshot_1502599875](https://user-images.githubusercontent.com/6080277/29246258-6ebf5b78-8026-11e7-9e29-0b33d6b134f6.png)
![screenshot_1502599898](https://user-images.githubusercontent.com/6080277/29246260-72d2734e-8026-11e7-90c3-8123ed5fdbd1.png)

But it was working just fine without webpack. During compile I ain't getting any error but when I try to access those page, it shows error like above screen short. In where I am doing wrong? Thanks in advance :)

All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.1.3           │ 3.1.3          │ Up to date    │
│ tns-core-modules │ 3.1.1           │ 3.1.1          │ Up to date    │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date    │
│ tns-ios          │                 │ 3.1.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘

**Comment by smarza** [comment]
I think you might want to take a look at this other issue.
They might be related in some way.

https://github.com/bradmartin/nativescript-cardview/issues/64#issuecomment-322032832

**Comment by jibon57** [comment]
@smarza Thank you. By removing background-color css property solve be card issue but what about Gif plugin? Have you tried it? https://github.com/bradmartin/nativescript-gif

**Comment by jibon57** [comment]
I found the problem.. For some reason during compile webpack only accepting png & jpeg images. It simply ignoring gif images. I have opened an issue here: https://github.com/NativeScript/nativescript-dev-webpack/issues/254
