### ISSUE TITLE
Failed to create folder on IOS (webpack only)

### ISSUE THREAD

**Issue by smarza** [NativeScript/nativescript-dev-webpack#256]
Hello guys!

I am trying to create a folder on my app. The code already works on my production app for a while. After added the webpack, IOS failed trying to create a folder.

**Error:**

```
CONSOLE ERROR [native code]: ERROR Error: Failed to create folder at path '/var/containers/Bundle/Application/A0A35643-5D7C-4FDA-9F06-AF07EB949B58/myappname/app/assets/test'

You don't have permission to save the file \M-b\M^@\M^\test\M-b\M^@\M^] in the folder \M-b\M^@\M^\assets\M-b\M^@\M^].
```

**Notes:**

Android works in both builds (TNS RUN or WEBPACK)
IOS only works in TNS RUN.

**Steps to reproduce:**

$ tns create my-app-name --template tns-template-hello-world-ng
$ npm install --save-dev nativescript-dev-webpack
$ npm run start-ios-bundle

```
let folder = fs.path.join(fs.knownFolders.currentApp().path, "assets", "test");
fs.Folder.fromPath(folder);
```

**Packages:**

```
  "nativescript": {
    "id": "org.nativescript.myapphelloworld",
    "tns-ios": {
      "version": "3.2.0-2017-7-5-5"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.2.0",
    "@angular/common": "~4.2.0",
    "@angular/compiler": "~4.2.0",
    "@angular/core": "~4.2.0",
    "@angular/forms": "~4.2.0",
    "@angular/http": "~4.2.0",
    "@angular/platform-browser": "~4.2.0",
    "@angular/router": "~4.2.0",
    "nativescript-angular": "~4.2.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "~3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.2.0",
    "@ngtools/webpack": "~1.5.0",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "~0.5.0",
    "nativescript-dev-webpack": "^0.7.3",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "typescript": "~2.4.2",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
```

Does webpack requires some extra settings to provide FS permission on IOS platform?

Thanks

**Comment by jibon57** [comment]
@smarza From my experience, I saw that IOS has problem if you don't use document directory. Use like this:

```
var folder = fs.path.join(fs.knownFolders.documents().path, "assets", "test");
fs.Folder.fromPath(folder);
```
I hope this will resolve permission problem :)

**Comment by smarza** [comment]
@jibon57 definitely works.

Do you know it is possible to put some files in documents during the building process?

Thanks

**Comment by jibon57** [comment]
@smarza I ain't sure your question was clear to me or not. If you want to include any other files with different extension during the build then you will need to include those in "`webpack.config.js`" file.  You read here: http://docs.nativescript.org/angular/best-practices/bundling-with-webpack.html#bundling-extra-assets

**Comment by Nahiduzzaman** [comment]
I am building a nativescript-angular app for IOS,
I am implementing custom fonts, and followed this blog https://nativescript.org/blog/using-custom-fonts-in-a-nativescript-app/
Everything works perfect when i run 'tns run ios'
But when i prepare build using Xcode in a real device.
I got error "You don’t have permission to save the file “fonts” in the folder <APP_NAME>"
