### ISSUE TITLE
Styles breaking on RadSideDrawer with template-drawer-navigation-ng

### ISSUE THREAD

**Issue by SamuelM333** [NativeScript/nativescript-dev-webpack#257]
Hi. I started using [template-drawer-navigation-ng](https://github.com/NativeScript/template-drawer-navigation-ng) as my starting point for a project. I noticed that webpack screws up the styles of GridLayout inside the side drawer. I thought it was a SASS problem so I moved the compiled css inside the component to see if that helped, but no luck. 

How can I fix it? I'm willing to submit a PR to the template's repo after finding a solution. Thanks! 

`tns run android` | `npm run start-android-bundle`
--- | ---
![tns run android](https://image.prntscr.com/image/pMon9G5NRFCmhIMhwTL5VQ.png "tns run android") | ![npm run start-android-bundle](https://image.prntscr.com/image/Rf76L6uMRr2ABwj-JsaVLQ.png "npm run start-android-bundle")

Steps to reproduce the issue:
``` 
tns create my-app-name --template https://github.com/NativeScript/template-drawer-navigation-ng 
cd my-app-name
npm install --save-dev nativescript-dev-webpack
npm install
npm run start-android-bundle
```

My environment: 
```
tns --version
3.1.3

node --version
v7.7.3

npm --version
5.3.0
```

And just in case, the `package.json` generated by the template with webpack installed: 

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.drawerwebpacktest",
    "tns-android": {
      "version": "3.1.1"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\"",
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "~3.1.0",
    "nativescript-telerik-ui": "^3.0.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.0",
    "tns-core-modules": "~3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.0",
    "@ngtools/webpack": "~1.5.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "codelyzer": "^3.0.1",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-sass": "^1.2.0",
    "nativescript-dev-typescript": "~0.5.0",
    "nativescript-dev-webpack": "^0.7.3",
    "node-sass": "*",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "tslint": "^5.4.3",
    "typescript": "~2.2.1",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  }
}
```

**Comment by michaelfalade** [comment]
I'm having exactly the same issue please help. Thank you!

**Comment by ChAraya** [comment]
same here

tns run ios

![captura de pantalla 2017-09-07 a la s 10 22 33](https://user-images.githubusercontent.com/19436477/30165561-e138e46e-93b6-11e7-93ba-100887857c6e.png)

with webpack

![captura de pantalla 2017-09-07 a la s 10 20 15](https://user-images.githubusercontent.com/19436477/30165576-eb32fb4e-93b6-11e7-9a72-e3515b065bb9.png)

**Comment by SamuelM333** [comment]
Any development on this? @sis0k0 could you give it a look please? Should I open an issue on the template repo?

**Comment by truewt** [comment]
I have the same problem - also described here: https://github.com/NativeScript/nativescript-angular/issues/984

I guess there is some problem with class names in HTML since CSS is most probably transferred along other styles.

**Comment by cmargulhano** [comment]
I have the same problem :(

**Comment by jevenson** [comment]
Hey guys! Found a resolution!

In `my-drawer.component.ts`, the class on the `GridLayout` is created using the name of the item.

```
<GridLayout columns="auto, *" rows="50"
    class="sidedrawer-list-item sidedrawer-list-item-{{item.name}}" 
    [class.selected]="isPageSelected(item.title)">
```
Changes to:

```
<GridLayout columns="auto, *" rows="50"
    class="sidedrawer-list-item" 
    [class.selected]="isPageSelected(item.title)">
```

If you're using that functionality, you can probably make use of `ngClass` and pass the item name into a function to return the class name.

**Comment by cmargulhano** [comment]
nice!!!! @jevenson

**Comment by SamuelM333** [comment]
@jevenson Hey! I'm glad that you found a solution! Many thanks. I've been very busy these days and I haven't been able to test this. Could you post a fragment of the .html and .ts files including the use of `ngClass` for `isPageSelected`? To have this a future references and close this issue. Again, thanks a lot!
