### ISSUE TITLE
Not working with Livesync with Angular Template on iOS

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/nativescript-dev-webpack#26]
It seems that bundle is not working with livesync anymore.

It refreshes the app on savings, but none of the changes is being loaded on the simulator

To reproduce, follow these steps:
1. tns create myapp --ng
2. tns platform add ios
3. tns install webpack
4. tns prepare ios
5. tns run ios --emulator
6. tns livesync ios --emulator --bundle --watch

Change anything on the "tap" app.

PS: It seems the theme is not loading as well. I'm not using atm, but we should investigate it.

PS: I haven't tested with Android yet.

* nativescript: 2.4.0
* tns-core-modules: 2.4.0
* tns-ios: 2.4.0
* Mac El Capitan 10.11.6
* XCode  8.1

**Comment by hdeshev** [comment]
Supporting livesync is outside the scope of the current implementation. We have started work on supporting webpack's hot module replacement feature, which should take care of livesync.
