### ISSUE TITLE
Introducing a param or smth else to skip Typescript errors

### ISSUE THREAD

**Issue by terreb** [NativeScript/nativescript-dev-webpack#266]
When building with tns we can easily skip Typescript errors adjusting tsconfig.json. However webpack plugin seems doesn't take that file into account and build (npm run start-ios-bundle) fails with all kind of TS errors. Would be nice if there would be a param or webpack plugin would take tsconfig.json file into account to eliminate all those errors upon building. 

Is there any workaround for this that I could use with the current webpack plugin version?

**Comment by NickIliev** [comment]
@terreb indeed you can skip TS errors on a normal build with `"noEmitOnError": false,` set in your `tsconfig.json` and the same won't work when bundling. The question is why would you want to emit the errors during build time and risk throwing an error runtime later.

**Comment by terreb** [comment]
Because TS compile typing error don't affect the app anyhow and yes, I don't want my build would fail because of them since it's irrelevant for the app.

**Comment by crutchcorn** [comment]
Why not just fix the Typescript type errors using `<any>` typing. It's still messy, but much much safer and cleaner than the idea you're suggesting

**Comment by sis0k0** [comment]
@terreb, if you are using older version (<0.9.0) of the nativescript-dev-webpack plugin, you will have to add the `"noEmitOnError": "true"` option to the `tsconfig.aot.json` file as it is the one that's used when running the app with webpack. For v0.9.0 only the `tsconfig.json` file will be used in both scenarios: with and without webpack.

**Comment by sis0k0** [comment]
@terreb, does that work for you? Can we close the issue?

**Comment by terreb** [comment]
@sis0k0, sorry haven't had time to check that yet, but please go ahead and close the issue. If building with webpack respects settings in tsconfig.json now I'm more than happy;)

**Comment by sis0k0** [comment]
Sure, feel free to reopen if you have any problems with it.
