### ISSUE TITLE
Need Help setting up the bundle-config file for a webpack build

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-dev-webpack#283]
_From @shiv19 on October 4, 2017 11:27_

I have tried to setup the bundle-config file for a webpack build. 
But it fails to find nativescript-theme-core every time, when I run `npm run start-android-bundle`

Can someone point me in the right direction to use webpack?

Here are the files. [files.zip](https://github.com/NativeScript/NativeScript/files/1355583/files.zip)

Files included:
bundle-config.js
report/stats.json
report/report.html
vendor.js
app.scss
app.css
webpack.config.js

_Copied from original issue: NativeScript/NativeScript#4914_

**Comment by NickIliev** [comment]
@shiv19  I've noticed that in your SASS file (`app.scss`) you are importing the CSS theme files instead of the SCSS files as shown [here](https://docs.nativescript.org/ui/theme#sass-usage)/ Real example can be found [here](https://github.com/NativeScript/template-drawer-navigation-ng/blob/master/app.android.scss#L5-L6)

**Comment by shiv19** [comment]
@NickIliev thank you!
about the module routes,
so if I register a module like
`global.registerModule("views/activities/activities", function () { return require("./views/activities/activities"); });`

then when navigating to it should I be doing
`framemodule.topmost().navigate("views/activities/activities")` ?

I'm getting `cannot find module ".", undefined`, after building with webpack.

**Comment by NickIliev** [comment]
@shiv19 have you added the bundle-config in your `app.ts` ('app.js' if using plain JavaScript) file 

```
require("./bundle-config");
```

**Comment by shiv19** [comment]
@NickIliev Yes, I have added. It was a part of the template created by sidekick

**Comment by NickIliev** [comment]
@shiv19 try migrating to the latest version of nativescript-dev-webpack (instructions [here](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade))

**Comment by shiv19** [comment]
Thanks @NickIliev this issue can be closed now :)
