### ISSUE TITLE
Webpack doesn't work with Uglify

### ISSUE THREAD

**Issue by alexandruantonica** [NativeScript/nativescript-dev-webpack#293]
Hi guys,

I found an issue when I try to run `npm run start/build-*-bundle --uglify`. Without `--uglify` the plugin works but when I added it, I got this error : 
```
BUILD SUCCESSFUL

Total time: 3.029 secs
Running webpack for android...
/Users/PATH/node_modules/schema-utils/dist/validateOptions.js:40
    throw new _ValidationError2.default(ajv.errors, name);
    ^

false
child process exited with code 1
```

my configuration
```
"nativescript-cli" : "3.1.3",
"tns-core-modules" : "3.1.1",
"tns-android" : "3.2.0",
"tns-ios" : "3.2.0"
```
package.json
```
"@angular/*" : "4.1.3",

...

"devDependencies": {
    "@angular/compiler-cli": "4.1.3",
    "@ngtools/webpack": "~1.6.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "0.5.0",
    "nativescript-dev-webpack": "^0.8.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "tns-platform-declarations": "3.1.1",
    "typescript": "2.4.2",
    "uglifyjs-webpack-plugin": "^1.0.0-beta.3",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
```

Thanks

**Comment by NickIliev** [comment]
@alexandruantonica 
Try to update NativeScript, tns-core-modules, all @angular dependencies and reset your `webpack-config.js` file by following the steps below
```
npm i -g nativescript@latest
tns plugin add tns-core-modules@latest
cd node_modules/nativescript-angular/bin
./update_app_ng_deps
```
then in your root directory delete `webpack.config.js` and create it again by running
```
npm i nativescript-dev-webpack --save-dev
npm install
```
and finally bundle with uglify
```
npm run start-android-bundle --uglify
```

**Comment by alexandruantonica** [comment]
Hi @NickIliev 

Thanks for your message. 
I did exactly how you told me but still nothing. I got the same error.

**Comment by gabitoesmiapodo** [comment]
There are some problems with NS plugins using ES6 code, it might have something to do with that.

Check https://github.com/NativeScript/nativescript-angular/issues/1011#issuecomment-333539020 for a workaround.

**Comment by sis0k0** [comment]
@alexandruantonica , the error:
```
BUILD SUCCESSFUL

Total time: 3.029 secs
Running webpack for android...
/Users/PATH/node_modules/schema-utils/dist/validateOptions.js:40
    throw new _ValidationError2.default(ajv.errors, name);
    ^

false
child process exited with code 1
```

means that you have wrong options for some webpack plugin. Can you share your webpack configuration?

**Comment by NickIliev** [comment]
@alexandruantonica the latest version of NativeScript and nativesript-dev-webpack has introduced a CLI flags for bundling and uglifying - migrating guide can be found [here](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade) and the set of new instructions can be found in [the updated article](https://docs.nativescript.org/best-practices/bundling-with-webpack).

Closing this one due to inactivity but do let me know if you still need assistance in resolving your issue.
