### ISSUE TITLE
App crash after web-packing

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/nativescript-dev-webpack#309]
I've got the following code segment (Android) on a Page that has a WebView and is being called on the page navigatedTo event. This code works.

```
webView.on(webViewModule.WebView.loadFinishedEvent, function (args: webViewModule.LoadEventData)
    {
        if ( platformModule.isAndroid )
        {
            class MyWebChromeClient extends android.webkit.WebChromeClient
            {
                constructor()
                {
                    super();
                    return global.__native(this);
                }
                init()
                {
                }
                onJsAlert( webview: android.webkit.WebView, url: string, msg: string, result: android.webkit.JsResult ) : boolean
                {
                    utils.errorDialog( msg, "MESSAGE" );
                    
                    result.confirm();
                    
                    return true;
                }
            }
            (<webViewModule.WebView>args.object).android.getSettings().setJavaScriptEnabled( true );

            (<webViewModule.WebView>args.object).android.setWebChromeClient( new MyWebChromeClient() );
        }

        if (args.error)
        {
            utils.toast( args.error );
        }
    });
```

But when I web-pack it - it crashes.

This is on a Mac platform with Android platform.
NS 3.3

I don't have snapshot or uglify enabled.

The error seems to be in the constructor MyWebChromeClient .
```
`System.err: TypeError: Cannot read property '__extended' of undefined 
System.err: File: "/data/data/com.myproject/files/internal/ts_helpers.js, line: 57, column: 14 
System.err: StackTrace: 

System.err: Frame: function:'extend', file:'/data/data/com.myproject/files/internal/ts_helpers.js', line: 57, column: 15 
System.err: Frame: function:'Parent.call', file:'/data/data/com.myproject/files/internal/ts_helpers.js', line: 70, column: 20 
System.err: Frame: function:'MyWebChromeClient', file:'file:///data/data/com.myproject/files/app/bundle.js', line: 15416, column: 40 
System.err: Frame: function:'', file:'file:///data/data/com.myproject/files/app/bundle.js', line: 15429, column: 52 
System.err: Frame: function:'module.exports.Observable.notify', file:'file:///data/data/com.myproject/files/app/vendor.js', line: 2053, column: 23 
System.err: Frame: function:'module.exports.WebViewBase._onLoadFinished', file:'file:///data/data/com.myproject/files/app/vendor.js', line: 21711, column: 14 
System.err: Frame: function:'WebViewClientImpl.onPageFinished', file:'file:///data/data/com.myproject/files/app/vendor.js', line: 12748, column: 23 
System.err: at com.tns.Runtime.callJSMethodNative(Native Method) 
System.err: at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088) 
System.err: at com.tns.Runtime.callJSMethodImpl(Runtime.java:970) 
System.err: at com.tns.Runtime.callJSMethod(Runtime.java:957)
```

**Comment by erjdriver** [comment]
After further investigation - this crash in happening in the super() call on the constructor.

I  tried to use the .extend suffix to the class name - got the TS error about undefined. But I overrode it - but again getting similar error message - this time no constructor but with init - but suffixing ".extend" seems to add it's awn pseudo constructor and within that there's a super call and crashes there.

**Comment by NickIliev** [comment]
Hey, @erjdriver I have tried to reproduce the issue using [this test project](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-dev-webpack/issue_309) but to no avail - the project is bundled successfully on my side with WebPack (+ uglify + snapshot).

Perhaps, you can check the versions in your package.json and reset the `webpack.config.js` file (delete it and then reinstall `nativescript-dev-webpack` to generate new config file)

You can also try my demo project on your side and compare the differences (I have used tns-platform-declarations and your exact snippet)

**Comment by erjdriver** [comment]
I'm still having this problem.

I reinstalled everything - but I have to edit a few things in webpack.config.js


How can I copy your project - I couldn't clone it.

**Comment by erjdriver** [comment]
The problem was in tsconfig.ts, I had "noEmitHelpers": false

Setting it to true - fixes the problem.
