### ISSUE TITLE
Nativescript's AOT Compilation succeeds - but still the `Compiler` package included?

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-dev-webpack#322]
I'm invoking : 

    npm run ns-bundle --android --build-app --uglify

It does succeed   (here is [*the complete log*](http://jsbin.com/cazecereco/edit?html)).

If I navigate to the `report` folder (_created by `webpack-bundle-size-analyzer`_) - I see those two files : 

[![enter image description here][1]][1]
![image|433x124](upload://2RPi3pMYbBuRK7p6ZrY1OpANqUJ.png)

Opening the `html file` shows : 

[![enter image description here][2]][2]

As you can see -  the compiler from @angular is still there !!!

**Question**

1)  Why does the compiler still there ? (AOT should remove it). How do I remove it ?  
2) If I hover the bundle.js section it shows me parsed size. so what is stat/parsed size ? 

[![https://i.imgur.com/25bRez3.jpg][3]][3]

-------
**Additional info :** 

I must say that when i search `bundle.js` in filesystem - I see two files : 

[![enter image description here][4]][4]

And a second one : 

[![enter image description here][5]][5]

------

**webpack.config.json** : http://jsbin.com/varetibaya/1/edit?html  
**package.json** : http://jsbin.com/sajifojuki/edit?html  
**main.aot.file** : http://jsbin.com/jimonurama/edit?html  
**ts.config.aot** : http://jsbin.com/tatahesoma/edit?html  

  [1]: https://i.stack.imgur.com/L1x4U.png
  [2]: https://i.stack.imgur.com/Kb4I0.jpg
  [3]: https://i.stack.imgur.com/MaXTj.jpg
  [4]: https://i.stack.imgur.com/8a6cf.jpg
  [5]: https://i.stack.imgur.com/6VptJ.jpg

**Comment by danielgek** [comment]
@RoyiNamir you got to review your imports, i had a case like this and it was a wrong import while importing something from the router package

try to analyse your stats.json with [webpack analyse](https://webpack.github.io/analyse/) there you can see what is importing the angular compiler

**Comment by RoyiNamir** [comment]
Problem was that I was importing the wrong router module

**Comment by abhayastudios** [comment]
@RoyiNamir can you elaborate a little? I have the same issue... what do you mean by wrong router module?

For example, I am using this one for my `app.routing.ts`:
```
import { NativeScriptRouterModule } from "nativescript-angular/router";
```

Then in my other components I reference these:
```
import { RouterExtensions } from "nativescript-angular/router";
```

Is this a problem?

**Comment by RoyiNamir** [comment]
Show me your apo module ts

**Comment by abhayastudios** [comment]
```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptFormsModule } from 'nativescript-angular/forms'; // needed for two-way binding in textfields
import { NativeScriptHttpModule } from "nativescript-angular/http";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { AppRoutingModule } from "./app.routing";

/*
   while NS doesn't support CSS gradients, use gradient plugin
   track progress at: https://github.com/NativeScript/NativeScript/issues/539
*/
import { registerElement } from "nativescript-angular";
registerElement("Gradient", () => require("nativescript-gradient").Gradient);

/* Components */

import { AppComponent } from "./app.component";

/* Providers */

import { ConfigProvider } from './providers/config';
import { FirebaseProvider } from './providers/firebase';
import { FacebookProvider } from './providers/facebook';
import { KeyboardProvider } from './providers/keyboard';

/* Pages */ 

import { LoginPage } from "./pages/login";

@NgModule({
  bootstrap: [
    AppComponent
  ],
  imports: [
    NativeScriptFormsModule,
    NativeScriptModule,
    NativeScriptHttpModule,
    AppRoutingModule
  ],
  declarations: [
    AppComponent,
    LoginPage
  ],
  providers: [
    ConfigProvider,
    FacebookProvider,
    FirebaseProvider,
    KeyboardProvider
  ],
  schemas: [
    NO_ERRORS_SCHEMA
  ]
})
export class AppModule {}
```

**Comment by RoyiNamir** [comment]
@danielgek  can you plz see my second question?

**Comment by RoyiNamir** [comment]
Wbwrw is the forroots  method?

**Comment by abhayastudios** [comment]
@RoyiNamir in the `app.routing.ts` file that I posted below the `app.module.ts` (this is the structure from the NativeScript default project)

**Comment by RoyiNamir** [comment]
@abhayastudios it doesn't seems the exact cause
https://stackoverflow.com/a/47265668/859154

**Comment by abhayastudios** [comment]
Too bad :) but I get the idea, I will check if there are other such cases...

Thanks!

**Comment by RoyiNamir** [comment]
@abhayastudios  try to see if this helps https://webpack.github.io/analyse/
