### ISSUE TITLE
file sqlite not found after instalasi webpack and run start-android-bundle

### ISSUE THREAD

**Issue by wiliarko** [NativeScript/nativescript-dev-webpack#324]
if run by "npm run start-android-bundle" file name_db.sqlite not found but if i run by tns run android it's running.

Can anyone help me?

**Comment by NickIliev** [comment]
@wiliarko try including the extra assets (in your case the SQLite file) as shown [in this documentation section](https://docs.nativescript.org/best-practices/bundling-with-webpack#bundling-extra-assets)

**Comment by wiliarko** [comment]
I have settings like:

new CopyWebpackPlugin([
            { from: mainSheet },
            { from: "css/**" },
            { from: "fonts/**" },
            { from: "**/*.jpg" },
            { from: "**/*.png" },
            { from: "**/*.xml" },
            { from: "**/*.sqlite" },
        ], { ignore: ["App_Resources/**"] }),

<img width="153" alt="screen shot 2017-11-15 at 10 19 43 am" src="https://user-images.githubusercontent.com/11497891/32817071-920ddbe2-c9ee-11e7-9f7b-f288d2f8e114.png">

<img width="425" alt="screen shot 2017-11-15 at 10 20 00 am" src="https://user-images.githubusercontent.com/11497891/32817082-96f4f708-c9ee-11e7-9118-2016eebff589.png">

**Comment by wiliarko** [comment]
is done by removing platform and re add

**Comment by taibuiSW** [comment]
This part: "{ from: "/*.sqlite" }" from your settings just saved my day. Thank you!
