### ISSUE TITLE
Webpack build on iOS failing since upgrade to Xcode 9.1

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/nativescript-dev-webpack#325]
Since upgrading to Xcode 9.1 (at least I think it started with this upgrade), I can't seem to create a webpack release build like this: `npm run build-ios-bundle -- --release --forDevice`. 

Since the tns CLI still mentions `$ tns build ios [--for-device] [--release] [--copy-to <File Path>]`, I also tried `npm run build-ios-bundle -- --release --for-device` which doesn't work either.

I get this error:
```
Xcode build...
2017-11-15 00:14:51.174 xcodebuild[65381:4191225] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/kt/7h9884y95pdd4zpxh2cfvhy40000gn/T/nativescript_2017-11-15_00-14-51.170.xcdistributionlogs'.
2017-11-15 00:14:52.662 xcodebuild[65381:4191225] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7ff295c71520>: Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value., NSFilePath=/var/folders/kt/7h9884y95pdd4zpxh2cfvhy40000gn/T/ipatool-json-filepath-qRzYkR}
error: exportArchive: The data couldn’t be read because it isn’t in the correct format.

Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value., NSFilePath=/var/folders/kt/7h9884y95pdd4zpxh2cfvhy40000gn/T/ipatool-json-filepath-qRzYkR}
```

Running `npm run start-ios-bundle` seems to work fine in the iOS simulator.

Any idea what might be wrong?

It is a fairly small project with this `package.json`:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.abhayastudios.testapp",
    "tns-ios": {
      "version": "3.3.0"
    },
    "tns-android": {
      "version": "3.3.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.2.0",
    "@angular/common": "~4.2.0",
    "@angular/compiler": "~4.2.0",
    "@angular/core": "~4.2.0",
    "@angular/forms": "~4.2.0",
    "@angular/http": "~4.2.0",
    "@angular/platform-browser": "~4.2.0",
    "@angular/router": "~4.2.0",
    "nativescript-angular": "~4.2.0",
    "nativescript-gradient": "^2.0.1",
    "nativescript-plugin-firebase": "^4.0.6",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "~3.3.0",
    "zone.js": "^0.8.16"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.2.0",
    "@ngtools/webpack": "~1.6.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
   "nativescript-dev-typescript": "^0.5.0",
    "nativescript-dev-webpack": "^0.8.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "typescript": "^2.4.2",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install"
  }
```

**Comment by mikaelkalt** [comment]
I'm currently struggling with the exact same problem. 

What I've figured out so far is that it was introduced in our project by adding a plugin:
https://market.nativescript.org/plugins/nativescript-loading-indicator
 
So  to easily reproduce it one could try to create a new empty project and add the loading indicator plugin to the project. It should fail with XCode 9.1 when you try to run it on the phone. It fails only when trying to run it on the phone, it works fine on the simulator. 

(But even removing the plugin didn't help in our project because in the meantime there were other plugins introduced like e.g.: 
-     "nativescript-localize": "^2.0.5",
-     "nativescript-material-icons": "^1.0.3",
-     "nativescript-ng2-fonticon": "^1.3.4",
-     "nativescript-secure-storage": "^2.2.1",
-     "nativescript-tooltip": "^2.1.2",

So it is really hard to develop without being able to run it directly on the phone. (It works if you manually open the XCode project and run it from there) 

I can't really say if it is a NativeScript or a Plugin problem. I'm new to NativeScript so I'm quite lost here.

**Comment by NickIliev** [comment]
Hey, @mikaelkalt @abhayastudios I am trying t reproduce the issue using[ this test project](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-dev-webpack/issue_325) but to no avail. I am using iPhone 6 with iOS 10 and XCode 9.1. Can you guys share more about the devices you are trying to deploy the application. 

While researching the possible reasons for this error I stun upon [this thread](https://stackoverflow.com/a/44502384/4936697) - perhaps you can try checking the info.plist files of your project for similar symbols along with the info.plist files of the plugins.

Another possible scenario would be that the generated info.plist file contains duplicate entries as discussed [here](https://stackoverflow.com/a/42469720/4936697)

**Comment by dariopellegrini** [comment]
I'm facing the same problem. Following.

**Comment by mikaelkalt** [comment]
@NickIliev I'm using an iPhone 8 with iOS 11.1.2 - I guess then it is an iOS11 problem if it's working for you on iOS 10.

**Comment by NickIliev** [comment]
@mikaelkalt can you verify that you have started your updated Xcode after the update (the XCode initial start will install some additional dependencies)

**Comment by mikaelkalt** [comment]
@NickIliev not sure if I understand you correctly but yes I have started my XCode 9.1 since the update - I even managed to run the generated XCode project from XCode itself. Do I need to reinstall the command line tools?

**Comment by abhayastudios** [comment]
@NickIliev I was able to reproduce the issue with your project after minor changes. You added the plugin but did not include it anywhere and since this is webpack I guess it didn't include the code in the bundle. Anyway once I referenced the plugin in `items.component.ts` as below, the bundling started to fail:

```
import { Component, OnInit } from "@angular/core";
import { LoadingIndicator } from "nativescript-loading-indicator";

import { Item } from "./item";
import { ItemService } from "./item.service";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {
    items: Item[];
    private indicator: LoadingIndicator;

    // This pattern makes use of Angular’s dependency injection implementation to inject an instance of the ItemService service into this class. 
    // Angular knows about this service because it is included in your app’s main NgModule, defined in app.module.ts.
    constructor(private itemService: ItemService) {
        this.indicator = new LoadingIndicator();
    }

    ngOnInit(): void {
        this.items = this.itemService.getItems();
        this.showLoader();
    }

    public showLoader() {
        this.indicator.show({ ios: { dimBackground: true } });
    }
}
```

**Comment by abhayastudios** [comment]
OK I think I found the problem:

Looking at the build pipeline (the build process outputs a dir with the logfiles), I see that while running the 
`/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool` it throws an error about the ruby gem sqlite3 missing:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sqlite3 (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:24:in `<main>'
```

Once I run below, the build finishes successfully:

```
$ sudo gem install sqlite3 -- --with-sqlite3-lib=/usr/lib
$ rvm use system
$ npm run build-ios-bundle -- --release --forDevice
```

I guess Xcode 9.1 introduced an issue with the sqlite3 gem?

**Comment by NickIliev** [comment]
@abhayastudios added the suggested code but once again everything is fine on my side. Have you tried to reset your platforms folder and rebuild your application. Another possibility is to test against the next version of NativeScript CLI and tns-ios.

Workflow to completly update nativescript-angular and nativescript-dev-webpack dependencies + install the next CLI and tns-ios
```
rm -rf node_modules platforms hooks
npm i nativescript@next
tns platform remove ios
tns platform add ios@next
npm i nativescript-angular --save
cd node_modules/nativescript-angular/bin/
./update-app-ng-deps
cd ../../../
npm i nativescript-dev-webpack --save-dev
cd node_modules/nativescript-dev-webpack/bin/
./update-ns-webpack
cd ../../../
npm i 
npm run start-ios-bundle -- --release --for-device
```

**Comment by abhayastudios** [comment]
@mikaelkalt @dariopellegrini does this solution work for you guys as well?

**Comment by abhayastudios** [comment]
Since this is not NativeScript related, I opened a [bugreport](https://bugreport.apple.com/web/?problemID=35683418) with Apple.

**Comment by mikaelkalt** [comment]
@abhayastudios yes that worked!!! thank you very much!

**Comment by dariopellegrini** [comment]
No result for me, but if it's an Apple bug I'll implement a workaround.

**Comment by madmas** [comment]
@dariopellegrini do you plan to implement that workaround for NativeScript or just for your project?

**Comment by dariopellegrini** [comment]
@madmas the workaround was on a UI plugin. I developed my own plugin using NS components instead of native ones as workaround. Sorry I can't help.
