### ISSUE TITLE
Question: how to uglify only vendor.js

### ISSUE THREAD

**Issue by terreb** [NativeScript/nativescript-dev-webpack#330]
What is the proper way to limit uglification to vendor.js only in webpack.config.js?

PS: I'm using Jscrambler to protect bundle.js. The building with that plugin is resource expensive and I would like to protect my code only. The vendor.js can be just minified with UglifyJS plugin.

**Comment by sis0k0** [comment]
Hey @terreb,

you can use the include property or the exclude property of the UglifyJS plugin. [Docs](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#include)

**Comment by terreb** [comment]
@sis0k0, thank you so much!
