### ISSUE TITLE
Cannot use "@Directive" with platform suffix ".android" and ".ios"

### ISSUE THREAD

**Issue by hosikiti** [NativeScript/nativescript-dev-webpack#332]
Use version 0.8.0 on NativeScript 3.3.
I'm facing an unkown issue on using my directive with WebPack AoT build. 

My project tree:
```
project/
    app/
        app.module.ts
        directives/
           xz-swipe-tab-view/
             xz-swipe-tab-view.d.ts
             xz-swipe-tab-view.ios.ts
             xz-swipe-tab-view.android.ts
```

There are three directive related files.

First, a TypeScript definition file to just avoid compile errors.
```ts
// xz-swipe-tab-view.d.ts
import { Directive } from "@angular/core";

@Directive({
	selector: "[xzSwipeTabView]"
})
export class XzSwipeTabViewDirective {}
```

Second, a directive for iOS platform.
```ts
// xz-swipe-tab-view.ios.ts
@Directive({
	selector: "[xzSwipeTabView]"
})
export class XzSwipeTabViewDirective implements OnInit {
 // doing directive staff
}
```

Third, a directive for Android platform.
```ts
export class XzSwipeTabViewDirective implements OnInit {
  // doing directive staff
}
```

Finally, a module loading definition.
```ts
// app.module.ts
import { XzSwipeTabViewDirective } from "./directives/xz-swipe-tab-view/xz-swipe-tab-view";
```

With JIT build ( `tns run ios`), the directive works without any problems. 
But the directive stops working completely when it is build with WebPack AoT build by `npm run build-ios-bundle --  --release --forDevice`. Build finishes with no error and my app runs. But it seems my directive is ignored. 

Does anyone have any thoughts on how to use platform specific directive on app build with WebPack AoT?

I read following issue which looks similar to my problem. I tried NathanWalker's "nativescript-webpack-import-replace" plugin but it ended up with WebPack build fails, unfortunately.
https://github.com/NativeScript/nativescript-dev-webpack/issues/200

**Comment by hosikiti** [comment]
Additional information.

If I change module load definition in `app.module.ts` from 
```
import { XzSwipeTabViewDirective } from "./directives/xz-swipe-tab-view/xz-swipe-tab-view";
```

to 
```
import { XzSwipeTabViewDirective } from "./directives/xz-swipe-tab-view/xz-swipe-tab-view.ios";
```

my directive starts working perfectly. Looks like platform specific file is not loaded when no platform suffix is specified. But platform specific files should be automatically selected and bundled by nativescript-dev-webpack plugin, right?

**Comment by PanayotCankov** [comment]
Sounds like a great test-case for the angular5 branch.

**Comment by PanayotCankov** [comment]
Works like a charm: https://github.com/NativeScript/nativescript-dev-webpack/pull/328/commits/f6ad70b8306ec4bc04474fd74d9f006044fcaa9b
The support for AngularCompilerPlugin, Angular5, and our FS abstraction will be released soon and the scenario with platform specific directive seems to work well. We will add some automated tests for it.

**Comment by PanayotCankov** [comment]
Fails with AoT:
```
ERROR in Error: Cannot determine the module for class PlayfulSpirit in /Users/cankov/git/NativeScript/nativescript-dev-webpack/demo/AngularApp/app/directive/PlayfulSpirit.android.ts! Add PlayfulSpirit to the NgModule to fix it.
Cannot determine the module for class PlayfulSpirit in /Users/cankov/git/NativeScript/nativescript-dev-webpack/demo/AngularApp/app/directive/PlayfulSpirit.ios.ts! Add PlayfulSpirit to the NgModule to fix it.
```

**Comment by PanayotCankov** [comment]
Yea it looks so.
Perhaps you can do something like:
```
if (global.ANDROID) {
// android code
} else {
// iOS code
}
```
And use some API to set the global.ANDROID to true/false in the main.ts for JIT (no web packed) scenarios and for publish have the webpack config such as:
```
            // Define useful constants like TNS_WEBPACK
            new webpack.DefinePlugin({
                "global.TNS_WEBPACK": "true",
                "global.ANDROID": platform === "android",
            }),
```
The uglification will handle dead code stripping.

I still prefer the platform specific service to work, but the errors seem to be checks in the angular compiler so they will need some extra effort to handle.

**Comment by hosikiti** [comment]
@PanayotCankov Thank you for suggesting.
I tried. But following code is not accepted by TypeScript unfortunately...

```
if( isIOS ){
	@Directive({
		selector: "[xzSwipeTabView]"
	})
	export class XzSwipeTabViewDirective implements OnInit {
```

Compiler says "TS1184: Modifiers cannot appear here". It seems @Directive should not be under `if` condition. Of course I can possibly merge two classes(.ios and .android) into one. But the class will need lots of `if` conditions and the entire code will be messy obviously...

While it's not a beautiful solution, what I'm thinking is to make a WebPack plugin which replaces all "import" definitions in file:`app.module.ts` directly according to the current platform, just before AoT plugin runs, and recover them on build finish.

**Comment by hosikiti** [comment]
I finally found a workaround about this issue.

Project tree:
```
project/
    app/
        app.module.ts
        directives/
           xz-swipe-tab-view/
             xz-swipe-tab-view.directive.ts  // <-- new!
             xz-swipe-tab-view.d.ts
             xz-swipe-tab-view.ios.ts
             xz-swipe-tab-view.android.ts
```

`xz-swipe-tab-view.directive.ts`
```
import { Directive, ElementRef, OnInit } from "@angular/core";
import { XzSwipeTabView } from "./xz-swipe-tab-view"; // <-- It loads xz-swipe-tab-view.d.ts

@Directive({
	selector: "[xzSwipeTabView]"
})
export class XzSwipeTabViewDirective implements OnInit {

	constructor(private el: ElementRef){
               // non platform specific initialization can be here!
	}

	public ngOnInit(){
		new XzSwipeTabView(this.el);
	}
}
```

`xz-swipe-tab-view.d.ts`
```
import { ElementRef } from "@angular/core";

export class XzSwipeTabView {
	constructor(el: ElementRef);
}
```

`xz-swipe-tab-view.ios.ts` or `xz-swipe-tab-view.android.ts`
```
import { Directive, ElementRef } from "@angular/core";

@Directive({
	selector: "[xzSwipeTabView]"
})
export class XzSwipeTabView {
	constructor(private el: ElementRef){
            // do any initialization for specified platform
	}
}
```

Import section in `app.module.ts`
```
import { XzSwipeTabViewDirective } from "./directives/xz-swipe-tab-view/xz-swipe-tab-view.directive";
```

Using this workaround, you can build your platform specific directive with webpack. In addition, you can keep platform specific codes clean and separate.
