### ISSUE TITLE
How to use with Nativescript 3.3

### ISSUE THREAD

**Issue by dvdbrk** [NativeScript/nativescript-dev-webpack#339]
Hi,

Looking at https://www.nativescript.org/blog/nativescript-hallow-3.3-n-release, and specifically **Webpack and CSS Improvements** section:

> First - the CSS is now applied on views a little bit before onLoaded. We used to re-apply CSS any time id or className is set on a View, including during startup. This saves 10% from the view instantiation. 

> Second, the tns-core-modules can now load CSS from modules provided by webpack either by css-loader or raw-loader, and there is a mechanism to force the parsing of that CSS before application startup. This allows us to include the CSS in the snapshot and boost startup times in apps that use the NativeScript theme in Android. 

> This is triggered by registering the stylesheets used in app.css to vendor.ts: 
```
import * as application from "application";
import "ui/styling/style-scope"; // When required, wires for application events.
global.registerModule("app.css", () => require("~/app"));
global.registerModule("app-common.css", () => require("~/app-common"));
application.loadAppCss();

```

> _You will also need to register the app.css and app-common.css to be handled by raw-loader in the webpack config, that change is currently on **PR in the nativescript-dev-webpack**, so it will soon be in the default configuration you get when you install the plugin._

So I have tried just changing vendors.ts file, in which case a webpack runs ok, but there is no styling in the app whatsoever. I understand something needs to change in **webpack.config.js** as well? I get those changes NS team mentioned in blog post did not make it to 0.8.0 - as the default configuration does not work?

**Comment by NickIliev** [comment]
@dvdbrk the latest version (3.4.0) has introduced some changes in the workflow - instructions on how to migrate the application to use Webpack with NativeScript 3.4.0 can be found [here](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade)
