### ISSUE TITLE
have to build twice on android or tns crashes

### ISSUE THREAD

**Issue by vbresults** [NativeScript/nativescript-dev-webpack#34]
Have to build first without `--bundle` and then again *with it*, otherwise it crashes.  So, building with webpack takes double the time which is a major problem.  Ping @hdeshev

```
W/System.err( 4979): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
W/System.err( 4979): Error calling module function 
W/System.err( 4979): Error: java.lang.ClassNotFoundException: com.tns.NativeScriptActivity
W/System.err( 4979):     java.lang.Class.classForName(Native Method)
W/System.err( 4979):     java.lang.Class.forName(Class.java:309)
W/System.err( 4979):     java.lang.Class.forName(Class.java:273)
W/System.err( 4979):     com.tns.Runtime.getClassForName(Runtime.java:947)
W/System.err( 4979):     com.tns.ClassResolver.resolveClass(ClassResolver.java:50)
W/System.err( 4979):     com.tns.Runtime.resolveClass(Runtime.java:565)
W/System.err( 4979):     com.tns.Runtime.runModule(Native Method)
W/System.err( 4979):     com.tns.Runtime.runModule(Runtime.java:514)
W/System.err( 4979):     com.tns.Runtime.run(Runtime.java:509)
W/System.err( 4979):     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
W/System.err( 4979):     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
W/System.err( 4979):     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
W/System.err( 4979):     android.app.ActivityThread.access$1500(ActivityThread.java:151)
W/System.err( 4979):     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
W/System.err( 4979):     android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 4979):     android.os.Looper.loop(Looper.java:135)
W/System.err( 4979):     android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 4979):     java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4979):     java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 4979):     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err( 4979):     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/System.err( 4979): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/com.example.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app-1/lib/x86, /vendor/lib, /system/lib]]
W/System.err( 4979):     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/System.err( 4979):     java.lang.ClassLoader.loadClass(ClassLoader.java:511)
W/System.err( 4979):     java.lang.ClassLoader.loadClass(ClassLoader.java:469)
W/System.err( 4979):     java.lang.Class.classForName(Native Method)
W/System.err( 4979):     java.lang.Class.forName(Class.java:309)
W/System.err( 4979):     java.lang.Class.forName(Class.java:273)
W/System.err( 4979):     com.tns.Runtime.getClassForName(Runtime.java:947)
W/System.err( 4979):     com.tns.ClassResolver.resolveClass(ClassResolver.java:50)
W/System.err( 4979):     com.tns.Runtime.resolveClass(Runtime.java:565)
W/System.err( 4979):     com.tns.Runtime.runModule(Native Method)
W/System.err( 4979):     com.tns.Runtime.runModule(Runtime.java:514)
W/System.err( 4979):     com.tns.Runtime.run(Runtime.java:509)
W/System.err( 4979):     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
W/System.err( 4979):     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
W/System.err( 4979):     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
W/System.err( 4979):     android.app.ActivityThread.access$1500(ActivityThread.java:151)
W/System.err( 4979):     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
W/System.err( 4979):     android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 4979):     android.os.Looper.loop(Looper.java:135)
W/System.err( 4979):     android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 4979):     java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4979):     java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 4979):     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err( 4979):     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by hdeshev** [comment]
I'd put a lot of effort in the latest nativescript-cli release to prevent that. Could you provide some details about your nativescript-cli version and your android runtime version.

I'd really appreciate a project that reproduces the problem.

**Comment by vbresults** [comment]
Both @latest, nativescript cli 2.4.2, android runtime 2.4.1

**Comment by vbresults** [comment]
@hdeshev Both @latest, nativescript cli 2.4.2, android runtime 2.4.1

Sample project:
```
$ git clone https://github.com/NativeScript/sample-Groceries.git
$ tns install
$ npm install nativescript-dev-webpack
$ tns emulate android --bundle
```

Noticed something off during the build process of the sample (but it didn't stop the build):
```
:asbg:generateBindings
java.io.FileNotFoundException: ../platforms/android/build-tools/android-static-binding-generator/bindings.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.nativescript.staticbindinggenerator.Generator.getRows(Generator.java:106)
	at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:45)
	at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
```

**Comment by hdeshev** [comment]
Oh, the workflow changed. You are not supposed to run `tns ... --bundle` anymore. Run `npm run start-android-bundle` instead. Check the [updated docs article](http://docs.nativescript.org/tooling/bundling-with-webpack) for details.

That said, the Groceries sample needs some additional work to get it running with webpack. We'll publish an update soon™.

**Comment by vbresults** [comment]
@hdeshev 

The only difference with `addPlatformScript(packageJson, "build-[PLATFORM]-bundle", "tns build [PLATFORM] --bundle --disable-npm-install")` is that it adds `--disable-npm-install`.

And as I said, the issue occurs with my own private project, not just the sample groceries one.

**Comment by hdeshev** [comment]
You also get a bunch of `pre*` scripts executing before the `tns...` command. Running just the command will **not** invoke the webpack or platform clean steps, and that's probably what's breaking apps on your end.

**Comment by vbresults** [comment]
Will try it out and report my findings

**Comment by vbresults** [comment]
@hdeshev There are very drastic changes between the latest webpack version and the one I am currently running -- so drastic that I cannot adopt this version due to my schedule.

Presently, I am using the uglify, and cleanup plugins, in addition to the banner + chunks plugin to split into multiple bundles (the latter two since separate bundles wasn't built in).

If the new version is able to uglify the non-vendor bundle and cleans out any bundled files while leaving the unbundled ones in place, I can switch over and test.

I need all four functions, looks like two are implemented; that said, we both have balls to juggle and if these aren't priority/workable at this time I understand and will close this ticket.

**Comment by vbresults** [comment]
@hdeshev I am using the commands that the scripts call directly (including --disable-npm-install) and the issue persists on 0.0.20

**Comment by hdeshev** [comment]
Hey, yes, the changes are drastic and backwards incompatible. We had to do it in order to make webpack configuration more flexible. As far as your requirements are concerned:

1. Split bundles should work as before. The CommonsChunkPlugin is fully supported.
2. I'm not sure what you mean by smart cleanup, but the latest nativescript-cli release introduces a `clean-app` command (e.g. `tns clean-app android`), which gets rid of build artifacts from previous non-bundle builds.
3. We are very close to getting the uglify.js plugin fully working.
    - It has a conflict with the android dex generation tool, but that should be resolved in the next release. There is a way to work around it at the cost of a slightly increased bundle size by setting `compress: false`.
    - The `mangle` option causes an issue resulting in some CSS settings not being applied correctly. I'm working on that one, and the fix will probably result in an update to the nativescript-dev-webpack config templates excluding certain symbols from mangling.

**Comment by vbresults** [comment]
@hdeshev Thank you

1. Ok
2. I mean when the final app is built, say an APK, and in the app/ folder the only things left are the bundled js files.  Presently, the unbundled non-js resources are deleted too (for example, fonts, XML view-models nested 2 levels deep) -- has this changed in the latest release?
3. I did a lot of work trying to mangle the vendor scripts, excluding different symbols, and failed.  CSS (and varying critical parts of NS) are broken by this.  But if you mangle the app bundle only, it works.  Is there a possibility of mangling only the app vendor bundle for the next release while you work out the vendor mangling?

**Comment by hdeshev** [comment]
> I mean when the final app is built, say an APK, and in the app/ folder the only things left are the bundled js files. Presently, the unbundled non-js resources are deleted too (for example, fonts, XML view-models nested 2 levels deep) -- has this changed in the latest release?

They are deleted by the clean-app command, but we now have the webpack copy plugin recopying them as needed. Of course, we can't predict all user resources in advance, but adding a new copy rule to the config is trivial.

> I did a lot of work trying to mangle the vendor scripts, excluding different symbols, and failed. CSS (and varying critical parts of NS) are broken by this. But if you mangle the app bundle only, it works. Is there a possibility of mangling only the app vendor bundle for the next release while you work out the vendor mangling?

My first reaction was "Not really", but after thinking about it for a while, it should be possible to have your app architected like a simple bootstrap shim that invokes an entrypoint in a certain module that does all the work. That module can be bundled and uglified separately. Of course, that is a pretty advanced scenario that will not be covered by the webpack plugin -- you'll have to fine tune the bundling procedure yourself.

**Comment by vbresults** [comment]
> My first reaction was "Not really", but after thinking about it for a while, it should be possible to have your app architected like a simple bootstrap shim that invokes an entrypoint in a certain module that does all the work. That module can be bundled and uglified separately. Of course, that is a pretty advanced scenario that will not be covered by the webpack plugin -- you'll have to fine tune the bundling procedure yourself.

This is exactly what I am doing now in 0.0.20.  The scenario isn't advanced, I just want to uglify my bundles; since I can't do the vendor I am settling for app-only ATM.  The _implementation_ is advanced.

Any developments on iOS font loading?

**Comment by vbresults** [comment]
Looks like a lot of refactoring is being done for 2.5.x which is why full uglificaiton may not be so far off as expected.  The issue that is the subject of this ticket remains but I will wait until 2.5 develops and see how it works if the requirements are met; closing this for now.
