### ISSUE TITLE
Misleading message on build and other tns command which do not watch for changes

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-dev-webpack#356]
`tns build android` result in:
```
Webpack compilation complete. Watching for file changes.
```

Same apply for `tns run android --justlaunch` and all commands which do not watch for changes.

**Comment by NickIliev** [comment]
Related to [https://github.com/NativeScript/nativescript-dev-webpack/pull/358](https://github.com/NativeScript/nativescript-dev-webpack/pull/358)
