### ISSUE TITLE
css not working on dynamic form with webpack

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-dev-webpack#359]
_From @Serge-SDL on December 17, 2017 11:42_

Hello,

I found somethink that looks like an issue: css is not applyed to form fields in dynamic form when using webpack:
- it works well using tns run android
- no css with npm run start-android-bundle

I have created a simple projet to reproduce the issue: https://github.com/Serge-SDL/nativescript-webpack-issue

result without webpack (tns run android):
![image](https://user-images.githubusercontent.com/1452002/34081901-4ab13246-e355-11e7-8ebe-f4ca01ba99a6.png)

result with webpack (npm run start-android-bundle):
![image](https://user-images.githubusercontent.com/1452002/34081942-09cc3482-e356-11e7-9436-cae13ada0adb.png)

Thansks!

_Copied from original issue: NativeScript/nativescript-angular#1125_

**Comment by NickIliev** [comment]
@Serge-SDL thank you for reporting this issue.
The issue is resolved with the upcoming new releases of nativescript-dev-webpack and nativescript-angular. Test project using all related dependencies (set to `next` at this very moment) can be found [here](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-dev-webpack/issue_359)

Keep in mind that with the upcoming new release, bundling the app with WebPack will be done with:
```
tns run android --bundle
```

**Comment by NickIliev** [comment]
The new version of NativeScript CLI, modules and nativesript-dev-webpack are now live so your issue should now be fixed with the official versions.

**Comment by Serge-SDL** [comment]
great, thanks! 👍
