### ISSUE TITLE
Livesync Support

### ISSUE THREAD

**Issue by jet-lee-m** [NativeScript/nativescript-dev-webpack#37]
Hi,

is it possible to include "**tns livesync --emulator --watch ios**" in **_package.json_**?

 
I included two commands, but its not really working:
`"livesync-ios": "tns livesync --emulator --watch ios --bundle --disable-npm-install",`
`"livesync-android": "tns livesync --emulator --watch android --bundle --disable-npm-install"`

**Comment by hdeshev** [comment]
Livesync isn't supported yet. This plugin is meant to be used for release builds for the time being.

We are planning on supporting the webpack hot module replacement feature in the future. Tracked in https://github.com/NativeScript/nativescript-angular/issues/570
