### ISSUE TITLE
Different relative paths for lazy route files

### ISSUE THREAD

**Issue by mxth** [NativeScript/nativescript-dev-webpack#372]
**Expected** 

Nested routes resolve child modules correctly with or without `--bundle`.

**Current**
- Without `--bundle`, the path is relative to `./app` directory.
- With `--bundle`, the path is relative to the current directory of the route file.

**Reproduce** 
- Clone https://github.com/mxth/nativescript-nested-lazy
- `tns run ios`
- `tns run ios --bundle`

**Comment by mxth** [comment]
@vchimev do you have an estimation for the fix? Our app is going to production soon, and we need it to plan accordingly.

**Comment by NickIliev** [comment]
@mxth as a temporary solution you can manually change the paths before bundling with Webpack (as done [here](https://github.com/NativeScript/nativescript-angular/issues/1200))

**Comment by Smiley01987** [comment]
@NickIliev when can we expect a fix for this?

**Comment by NickIliev** [comment]
@Smiley01987  @mxth the issue can now be resolved by providing an app alieas in tsconfig.json and using the alias to create the nested lazily loaded modules.
For example (based on [https://github.com/mxth/nativescript-nested-lazy)](https://github.com/mxth/nativescript-nested-lazy)

**tsconfig.json** (note the alias in paths `"~/*": ["app/*"],`)
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "app/*"
            ],
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

and then in the nested routing table use the alias as follows
items.module.ts
```
export const routes: Routes = [{
  path: '',
  component: ItemsComponent
}, {
  path: ':id',
  loadChildren: '~/item/item-detail/item-detail.module#ItemDetailModule'
}]

```

With the above configuration, the application will build and run as expected with and without Webpack.

**Comment by NickIliev** [comment]
The creation of the alias will be added out-of-the-box with nativescript-ev-typescript with[ this PR](https://github.com/NativeScript/nativescript-dev-typescript/pull/46)
