### ISSUE TITLE
Version 0.9.0 is not working

### ISSUE THREAD

**Issue by GrEg00z** [NativeScript/nativescript-dev-webpack#373]
While using 0.9.0, nothing works (I hate say that but it's the true)

Scripts code have been removed from package.json, and instead we have to use : 
`tns run android --bundle`

**BUT THIS LINE DO NOTHING, EXCEPT THROW NATIVESCRIPT ERROR AFTER NATIVE COMPILATION** (without perform any webpack bundling)

What the hell is that ??

**Comment by sis0k0** [comment]
@GrEg00z, have you updated the nativescript-cli as well? Also can you share your package.json?

**Comment by GrEg00z** [comment]
Ok didn't see that there is nativescript update.

I'm using ns 3.3.0, maybe it's the reason

I have already start to integrate webpack 0.8.0, so when all will be done, I will switch on 0.9.0 and nativescript 3.4.0, and keep you inform 👍

**Comment by sis0k0** [comment]
@GrEg00z, there are a few changes that you may have to do in order to migrate the project. We'll publish a blog post for the upgrade later today. You can ping me in nativescriptcommunity.slack.com or on twitter at @StanimiraVlaeva if you have any problems migrating. I'll link the blog post when it's ready.

**Comment by sis0k0** [comment]
@GrEg00z, the blog post is live: https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade.

**Comment by jeffswitzer** [comment]
Hi @sis0k0, after following the blog post instructions and running `tns run android --bundle` I'm getting the error:

```
Running webpack for android...

D:\a\webpack.config.js:164
        new nsWebpack.UrlResolvePlugin({
        ^
TypeError: nsWebpack.UrlResolvePlugin is not a constructor
    at getPlugins (D:\a\webpack.config.js:164:9)
    at module.exports.env (D:\a\webpack.config.js:31:21)
    at handleFunction (D:\a\node_modules\webpack\lib\prepareOptions.js:26:13)
    at prepareOptions (D:\a\node_modules\webpack\lib\prepareOptions.js:11:13)
    at requireConfig (D:\a\node_modules\webpack\bin\convert-argv.js:98:14)
    at D:\a\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (native)
    at module.exports (D:\a\node_modules\webpack\bin\convert-argv.js:102:15)
    at yargs.parse (D:\a\node_modules\webpack\bin\webpack.js:171:41)
    at Object.Yargs.self.parse (D:\a\node_modules\webpack\node_modules\yargs\yargs.js:533:18)
    at Object.<anonymous> (D:\a\node_modules\webpack\bin\webpack.js:152:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Executing webpack failed with exit code 1.
```

The `webpack.config.js` file didn't seem to be modified after running `./node_modules/.bin/update-ns-webpack --configs --deps` should it have been?

**Comment by sis0k0** [comment]
@jeffswitzer, you've got a typo. 
'config' should be 'configs'

**Comment by jeffswitzer** [comment]
@sis0k0 right you are, unfortunately that typo wasn't present when I actually ran it.

**Comment by sis0k0** [comment]
@jeffswitzer ,
It looks like the old webpack configuration (0.8.0). You can delete it and run `npm install nativescript-dev-webpack@0.9.0` to regenerate it.

**Comment by jeffswitzer** [comment]
@sis0k0 thank you. That solved that issue. The build is successful now, although I do get a runtime exception: 

```
System.err: TypeError: document.createElement is not a function
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ImmediateDefinition.canUseReadyStateChange', file:'file:///data/data/org.nativescript.a/files/app/tns_modules/rxjs/util/Immediate.js', line: 56, column: 69
System.err:     Frame: function:'ImmediateDefinition', file:'file:///data/data/org.nativescript.a/files/app/tns_modules/rxjs/util/Immediate.js', line: 30, column: 27
```

I don't think this is webpack related though and something else to do with the 3.4 update.

**Comment by SamuelReeder** [comment]
@jeffswitzer 

People hitting the `document.createElement`. make sure you are *not* importing from `rxjs/rx`

**Comment by sis0k0** [comment]
I'm closing this. Open another if you have issues migrating. @jeffswitzer, you can open an issue in the nativescript repo if you haven't managed to resolve the createDocument error.
