### ISSUE TITLE
Error: Can't resolve './app.module.ngfactory'

### ISSUE THREAD

**Issue by masrc** [NativeScript/nativescript-dev-webpack#379]
Hey, I having the follow erro when run tns run --bundle

` ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'C:\Users\dev16\Documents\projetos\testeAtualizacao\app'
 @ ./main.aot.ts 6:29-62

ERROR in Error: Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+
    at throwNotSupportedError (C:\Users\dev16\Documents\projetos\testeAtualizacao\packages\compiler-cli\src\ngtools_api.ts:132:9)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\Users\dev16\Documents\projetos\testeAtualizacao\packages\compiler-cli\src\ngtools
_api.ts:80:11)
    at _donePromise.Promise.resolve.then (C:\Users\dev16\Documents\projetos\testeAtualizacao\node_modules\@ngtools\webpack\src\plugin.
js:430:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

 followed some issues, but no luck. I maked a demo that can reproduce the error

[testeAtualizacao.zip](https://github.com/NativeScript/nativescript-dev-webpack/files/1587640/testeAtualizacao.zip)

**Comment by berchik** [comment]
What about adding `webpack.config.js` to your project? There are some rules and configurations you might need.

**Comment by masrc** [comment]
Actually I have it, but forgot to put it on the .zip... here it is
[webpack.config.js.zip](https://github.com/NativeScript/nativescript-dev-webpack/files/1588804/webpack.config.js.zip)

**Comment by berchik** [comment]
You are using `"nativescript-dev-webpack": "^0.9.0"` but your webpack.config is from an older version, which means you have some different rules and loaders. Use the new configuration file (since I don't see any special adjustments, you can erase the current one and re-install the plugin to create it).

**Comment by jogboms** [comment]
@masrc please follow the upgrade guide https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade

**Comment by masrc** [comment]
@berchik It works! really thanks.

@jogboms I'm was using this tutorial, but the problem was on webpack.config even
