### ISSUE TITLE
Require, function calls are not supported

### ISSUE THREAD

**Issue by jet-lee-m** [NativeScript/nativescript-dev-webpack#38]
Hi,

I try to include a template.html with require...

`@Component({`
`    moduleId: module.id,`
`    template: require("./using-camera.component.html")`
`})`

but I get following error
`
Error: Error encountered resolving symbol values statically. Calling function 'require', function calls are not supported. 
`

In NativeScript without webpack I can use **_require()_**. 
Is there a possibility to use **require**?

Thx

**Comment by hdeshev** [comment]
I think this is a limitation of the @ng-tools/webpack plugin. Why do you want to do that though? The plugin will pick up all `templateUrl` settings and autobundle them.
