### ISSUE TITLE
Error when running "tns run android --bundle"

### ISSUE THREAD

**Issue by chenshuiluke** [NativeScript/nativescript-dev-webpack#380]
As mentioned in the title, I get an error when running `tns run android --bundle`:

    tns build android --bundle
    npm WARN schema-utils@0.4.3 requires a peer of webpack@^2.0.0 || ^3.0.0 but none was installed.

    up to date in 13.219s
    Executing before-prepare hook from /home/luke/Documents/git/cortexdictionary/hooks/before-prepare/nativescript-dev-typescript.js
    Preparing project...
    Successfully prepared plugin nativescript-angular for android.
    Successfully prepared plugin nativescript-ngx-slides for android.
    Successfully prepared plugin nativescript-theme-core for android.
    Successfully prepared plugin tns-core-modules for android.
    Successfully prepared plugin nativescript-intl for android.
    Successfully prepared plugin tns-core-modules-widgets for android.
    Project successfully prepared (android)
    Executing after-prepare hook from /home/luke/Documents/git/cortexdictionary/hooks/after-prepare/nativescript-dev-webpack.js
    Building project...
    Gradle build...
            + applying user-defined configuration from /home/luke/Documents/git/cortexdictionary/app/App_Resources/Android/app.gradle
            + creating include.gradle for plugin /home/luke/Documents/git/cortexdictionary/node_modules/tns-core-modules-widgets
            + applying plugin configuration from /home/luke/Documents/git/cortexdictionary/platforms/android/build/configurations/tns-core-modules-widgets/include.gradle
            + adding nativescript runtime package dependency: nativescript-optimized
            + adding aar plugin dependency: /home/luke/Documents/git/cortexdictionary/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
    Running full build

    FAILURE: Build failed with an exception.

    * Where:
    Build file '/home/luke/Documents/git/cortexdictionary/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 276

    * What went wrong:
    Execution failed for task ':asbg:generateBindings'.
    > No /home/luke/Documents/git/cortexdictionary/platforms/android/build-tools/android-static-binding-generator/bindings.txt was found after runAstParser task was ran! Check to see if there are any .js files inside /home/luke/Documents/git/cortexdictionary/platforms/android/src/main/assets/app

Here's my package.json file:

    {
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "readme": "NativeScript Application",
    "repository": "<fill-your-repository-here>",
    "nativescript": {
        "id": "org.nativescript.CortexDictionary",
        "tns-android": {
        "version": "3.3.1"
        }
    },
    "dependencies": {
        "@angular/animations": "~4.4.1",
        "@angular/common": "~4.4.1",
        "@angular/compiler": "~4.4.1",
        "@angular/core": "~4.4.1",
        "@angular/forms": "~4.4.1",
        "@angular/http": "~4.4.1",
        "@angular/platform-browser": "~4.4.1",
        "@angular/router": "~4.4.1",
        "image-search-google": "^1.0.7",
        "nativescript-angular": "~4.4.0",
        "nativescript-ngx-slides": "^0.4.5",
        "nativescript-theme-core": "~1.0.2",
        "reflect-metadata": "~0.1.8",
        "rxjs": "~5.4.2",
        "tns-core-modules": "~3.3.0",
        "zone.js": "~0.8.2"
    },
    "devDependencies": {
        "@angular/compiler-cli": "~4.4.1",
        "@ngtools/webpack": "~1.8.2",
        "babel-traverse": "6.26.0",
        "babel-types": "6.26.0",
        "babylon": "6.18.0",
        "copy-webpack-plugin": "~4.0.1",
        "css-loader": "~0.28.7",
        "extract-text-webpack-plugin": "~3.0.0",
        "lazy": "1.0.11",
        "nativescript-dev-typescript": "~0.5.0",
        "nativescript-dev-webpack": "^0.9.0",
        "nativescript-worker-loader": "~0.8.1",
        "raw-loader": "~0.5.1",
        "resolve-url-loader": "~2.1.0",
        "typescript": "~2.4.2",
        "webpack": "~3.8.1",
        "webpack-bundle-analyzer": "^2.8.2",
        "webpack-sources": "~1.0.1"
    }
    }

**Comment by AmithRamesh** [comment]
@chenshuiluke  [This](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade) should solve your issue.

**Comment by sis0k0** [comment]
As @AmithRamesh mentioned, you need to follow the [upgrade blog post](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade) for v0.9.0 of nativescript-dev-webpack. I'll close this issue. Please open another one if you have troubles upgrading.

**Comment by chenshuiluke** [comment]
Thank you very much that seems to have worked
