### ISSUE TITLE
Snapshots not working behind corporate proxy

### ISSUE THREAD

**Issue by ticklemepierce** [NativeScript/nativescript-dev-webpack#389]
It seems that node's https module does not honor environment proxy variables (i.e. HTTPS_PROXY) so the snapshots time out with the requests in utils (getJsonFile and downloadFile).

 I'm on node 8.7.0 and nativescript 3.4.0.  I'm also using 0.9.0 for this package.

**Comment by mxth** [comment]
Our CI build breaks because of this. Any workaround?

> ERROR in NativeScriptSnapshot. Snapshot generation failed!
Cannot find suitable v8 version! Original error: connect ETIMEDOUT 151.101.64.133:443

**Comment by NickIliev** [comment]
Ping @Pip3r4o @rosen-vladimirov 

@rosen-vladimirov suggested implementing the usage of [request](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables) instead of `https.get`

**Comment by Pip3r4o** [comment]
@ticklemepierce @mxth @ajswago

I can confirm that the snapshot generation does not work while behind a proxy. The problem stems from the fact that node.js does not respect env variables and system proxies by default. The requests made at https://github.com/NativeScript/nativescript-dev-webpack/blob/3967d7961b2609cc4da5d92fa4f8cad153b64f57/snapshot/android/utils.js#L47 and https://github.com/NativeScript/nativescript-dev-webpack/blob/3967d7961b2609cc4da5d92fa4f8cad153b64f57/snapshot/android/utils.js#L15

will not be influenced by `HTTPS_PROXY` set from the NativeScript CLI, or as a node environment variable.

We are currently reviewing the best way to enable http requests behind a proxy in the snapshot scripts, and will let you know when an update with a fix is released.

As an immediate work-around the https requests can be replaced by those of the [request](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables) npm package.

```javascript
const request = require("request");

const downloadFile = (url, destinationFilePath) =>
	new Promise((resolve, reject) => {
		request
			.get(url)
			.on('response', response => 
            switch (response.statusCode) {
				case 200:
					const file = createWriteStream(destinationFilePath, { autoClose: true });
					file.on('error', function (error) {
						return reject(error);
					});
					file.on("finish", function () {
						chmodSync(destinationFilePath, 0755);
						return resolve(destinationFilePath);
					});
					response.pipe(file);
					break;
				case 301:
				case 302:
				case 303:
					const redirectUrl = response.headers.location;
					return this.downloadFile(redirectUrl, destinationFilePath);
				default:
					return reject(new Error("Unable to download file at " + url + ". Status code: " + response.statusCode));
			}
		)
			.on('error', err => {
				return reject(err);
			});
	});

const getJsonFile = url =>
	new Promise((resolve, reject) => {
		request
			.get(url)
			.on('response', res => {
				let body = "";
				res.on("data", chunk => {
					body += chunk;
				})

				res.on("end", () => {
					const data = JSON.parse(body);
					return resolve(data);
				});
			})
			.on("error", err => {
				return reject(err);
			});
	});
```
