### ISSUE TITLE
tns 3.4 release build has app.css missing

### ISSUE THREAD

**Issue by xgu01** [NativeScript/nativescript-dev-webpack#394]
After upgrade to tns 3.4.0, debug build works properly. But release build has app.css missing.

command used:

tns build android --bundle --release --env.uglify --keyStorePath ...

**Comment by berchik** [comment]
The question is - why are you looking for it? Webpack function is to bundle all files into few large ones. app.css is bundled with other scripts into `_embedded_script_.js`. Are you experiencing any problems?

**Comment by xgu01** [comment]
Thanks for your reply. I wasn’t looking for it. The whole css classes defined in it are entirely missing from the bundle release build as my page has no style vs in debug build styles are properly applied.

But I found a workaround, that is not using app.css, instead use app.android.scss and app.ios.scss which bundle release build picked up without any issues.

**Comment by berchik** [comment]
Ok, so two things. First, when importing css files in your app.css you need to use `“~”` when importing from a folder under `node_modules`, and `“~/”` when importing from the app folder. 
Second, there is an issue with the css-loader paths in `webpack.config.js`, you should use the fix mentioned here: #385 
`{ test: /[\/|\\]app\.css$/, use: "css-loader?url=false" }`

**Comment by NickIliev** [comment]
Closing as related to [https://github.com/NativeScript/nativescript-dev-webpack/issues/378](https://github.com/NativeScript/nativescript-dev-webpack/issues/378) and  and [CSS imports](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade)
