### ISSUE TITLE
Android and IOS : Css styling lost with Webpack 0.9

### ISSUE THREAD

**Issue by anuragd7** [NativeScript/nativescript-dev-webpack#396]
Hi 
I am using different styles for tablets and phones for my project using the approach suggested by Eddy in [this blog post.](https://www.nativescript.org/blog/tablet-support-for-nativescript-with-angular).

The styling approach works fine when i run the project using tns run ios/android. However when I use tns run ios --bundle or tns run android --bundle. All the styles defined in the files - phone.ios.css, tablet.ios.css, phone.android.css, phone.tablet.css are not applied.

I have created a [sample project](https://github.com/anuragd7/WebpackDemo) where this issue can be seen. 

Please let me know How I can fix this.

**Comment by berchik** [comment]
You have no `webpack.config.js` in your project. It is needed. 
Once you create it you can add your extra files to the plugin copy list, something like this:

```
new CopyWebpackPlugin([
….
   { from: "your-fuile-path/file.component.tablet.css" },
....           
 ]),
```

**Comment by anuragd7** [comment]
Hi @berchik 
Thanks for your response. Can confirm styling works after this.
