### ISSUE TITLE
 ReferenceError: webpackJsonp is not defined , when changing CommonChunkPlugin name.

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-dev-webpack#397]
Currently , When `tns create aaa --ng` , the commonchunksplugin is : 

```
  new webpack.optimize.CommonsChunkPlugin({
                name: "vendor",
            }),
```

APP works fine on device and also with build.

But if I change the name to :  ( according to the [docs](https://webpack.js.org/plugins/commons-chunk-plugin/#explicit-vendor-chunk)  - the name is just the name for common chunk)

```
  new webpack.optimize.CommonsChunkPlugin({
                name: "vendor2", //noitice 2
            }),
```

Then build does succeed : `tns build android --bundle --env.uglify --env.report --env.aot`

But when running on device  , I get this error : 

```
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err:
System.err: Error calling module function
System.err:
System.err: Error calling module function
System.err:
System.err: ReferenceError: webpackJsonp is not defined
System.err: File: "file:///data/data/org.nativescript.aaa/files/app/vendor.js, line: 1, column: 75
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.aaa/files/app/vendor.js', line: 1, column: 76
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.aaa/files/app/starter.js', line: 1, column: 61
System.err:     Frame: function:'require', file:'', line: 1, column: 266
```

full log :http://jsbin.com/yihadipowe/edit?html,output
webpack.config : https://gist.github.com/anonymous/ea9e546514965fc5b2d8e617fe47bf9a

BTW it's not related to snapshot since I don't run it with snapshot flag

**Comment by RoyiNamir** [comment]
update : 

It seems to work If I also rename in here :  
```
new nsWebpack.GenerateBundleStarterPlugin([
                "./vendor2",
                "./bundle",
            ]),
```


If that's the right( and full) solution , it should be in docs , becuase people might want to change it.

**Comment by sis0k0** [comment]
@RoyiNamir, you should modify the `filename` property instead. According to the first snippet in the linked article:
```
// ...
  new webpack.optimize.CommonsChunkPlugin({
    name: "vendor",
    // filename: "vendor.js"
    // (Give the chunk a different name)
```
