### ISSUE TITLE
WebPack Working with TNS 2.0x?

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-dev-webpack#4]
I did a 
**tns create testng --ng**
**cd testng**
**tns install webpack**
**tns platform add android**
**tns build android**

I expected webpack to shrink the file size of the apk; but it is almost as if the output of webpack wasn't used (no error messages).  The APK contained all the normal tns folders with the normal files.    Is their a trick to get this to work?

**Comment by triniwiz** [comment]
I think it you need `--bundle`

**Comment by NathanaelA** [comment]
@triniwiz Yeah, I should have come back and figured it out a couple days ago..   But yep, that is the answer.
