### ISSUE TITLE
Fail  webpack --config=webpack.android.js --progress

### ISSUE THREAD

**Issue by maabreve** [NativeScript/nativescript-dev-webpack#40]
Hi, 

I followed the instructions and Im getting an error when i run the command: 

--------------------------------------------------------------------------------------------------------------
** npm run build-android-bundle

> inealicenciamento@1.0.0 prebuild-android-bundle C:\Users\marcos.augustin\documents\inea_ns
> npm run webpack-android

> inealicenciamento@1.0.0 prewebpack-android C:\Users\marcos.augustin\documents\inea_ns
> npm run clean-android

> inealicenciamento@1.0.0 clean-android C:\Users\marcos.augustin\documents\inea_ns
> tns clean-app android

> inealicenciamento@1.0.0 webpack-android C:\Users\marcos.augustin\documents\inea_ns
> webpack --config=webpack.android.js --progress
                                                                                                                                          0% compiling
Error: AppModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (C:\Users\documents\node_modules\@ngtools\webpack\src\plugin.js:297:19)
    at AotPlugin._processNgModule (C:\Users\documents\node_modules\@ngtools\webpack\src\plugin.js:241:42)

    at C:\Users\documents\node_modules\@ngtools\webpack\src\plugin.js:217:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)    70% building modules 617/617 modules 0 active
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "web
pack-android"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! inealicenciamento@1.0.0 webpack-android: `webpack --config=webpack.android.js --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the inealicenciamento@1.0.0 webpack-android script 'webpack --config=webpack.android.js --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the inealicenciamento package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config=webpack.android.js --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs inealicenciamento
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls inealicenciamento
npm ERR! There is likely additional logging output above.

------------------------------------------------------------------------------------------------------------
My package.json:

{
  "name": "inealicenciamento",
    "version": "1.0.0",
  "description": "App",
  "repository": {
    "type": "git",
  },
  "keywords": [
    "NativeScript",
  ],
  "license": "SEE LICENSE IN <your-license-filename>",
  "homepage": "<home-page>",
  "nativescript": {
    "id": "org.nativescript.",
    "tns-ios": {
      "version": "2.3.0"
    },
    "tns-android": {
      "version": "2.5.0-next-2016-12-19-1539"
    }
  },
  "scripts": {
    "tslint": "tslint \"app/**/*.ts\"",
    "clean-android": "tns clean-app android",
    "clean-ios": "tns clean-app ios",
    "prewebpack-android": "npm run clean-android",
    "prewebpack-ios": "npm run clean-ios",
    "webpack-android": "webpack --config=webpack.android.js --progress",
    "webpack-ios": "webpack --config=webpack.ios.js --progress",
    "prestart-android-bundle": "npm run webpack-android",
    "prestart-ios-bundle": "npm run webpack-ios",
    "start-android-bundle": "tns run android --bundle --disable-npm-install",
    "start-ios-bundle": "tns run ios --bundle --disable-npm-install",
    "prebuild-android-bundle": "npm run webpack-android",
    "prebuild-ios-bundle": "npm run webpack-ios",
    "build-android-bundle": "tns build android --bundle --disable-npm-install",
    "build-ios-bundle": "tns build ios --bundle --disable-npm-install"
  },
  "dependencies": {
    "@angular/common": "~2.2.3",
    "@angular/compiler": "~2.2.3",
    "@angular/core": "~2.2.3",
    "@angular/forms": "~2.2.3",
    "@angular/http": "~2.2.3",
    "@angular/platform-browser": "~2.2.3",
    "@angular/platform-browser-dynamic": "~2.2.3",
    "@angular/router": "~3.2.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/store": "^2.2.1",
    "angulartics2": "^1.4.3",
    "email-validator": "1.0.4",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",
    "everlive-sdk": "1.7.1",
    "lodash": "^4.16.4",
    "nativescript-angular": "next",
    "nativescript-floatingactionbutton": "^2.2.6",
    "nativescript-geolocation": "0.0.15",
    "nativescript-google-maps-sdk": "^1.4.1",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-loading-indicator": "^2.2.1",
    "nativescript-maskedinput": "0.0.3",
    "nativescript-orientation": "^1.5.4",
    "nativescript-social-share": "1.3.1",
    "nativescript-telerik-ui": "^1.4.1",
    "nativescript-theme-core": "^1.0.0",
    "nativescript-unit-test-runner": "^0.3.3",
    "ng2-translate": "^4.0.0",
    "ngrx-store-freeze": "^0.1.0",
    "parse5": "1.3.2",
    "promise": "^7.1.1",
    "punycode": "1.3.2",
    "querystring": "0.2.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.4.1",
    "url": "0.10.3"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.2.1",
    "@ngrx/store-devtools": "^3.1.0",
    "@ngtools/webpack": "1.1.6",
    "@types/jasmine": "^2.5.35",
    "babel-traverse": "6.19.0",
    "babel-types": "6.19.0",
    "babylon": "6.14.1",
    "codelyzer": "0.0.28",
    "copy-webpack-plugin": "~3.0.1",
    "css-loader": "~0.26.0",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "filewalker": "0.1.2",
    "jasmine-core": "^2.4.1",
    "karma": "^1.2.0",
    "karma-jasmine": "^1.0.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.2",
    "nativescript-dev-webpack": "^0.2.15",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "shelljs": "^0.7.0",
    "tslint": "^3.14.0",
    "typescript": "^2.0.10",
    "webpack": "~2.1.0-beta.27",
    "zone.js": "~0.6.21"
  }
}

--------------------------------------------------------------------------------------------------------------
Can you help me pelase? I cant find the solution ...

Thank you!!

**Comment by m-abs** [comment]
Do you have a link to the project? It would be much easier to help if I could see the code.

One thing you could check, in `webpack.common.js` find `AotPlugin` under `plugins`, there is a param `entryModule`, this points to the `app/app.module#AppModule`.`app/app.module` is the filename (without the ext) and `AppModule` is the name of the module.
The error you're getting means that either wrong file (e.g. app/app.module) doesn't exist or it doesn't export an NgModule named `AppModule`.

**Comment by hdeshev** [comment]
I've also seen that error when the NgModule is defined in such a way that isn't supported by the AoT tools. Can't say much more without a look at the code really.

**Comment by vbresults** [comment]
@hdeshev Getting this too on a bare install.  I am not using angular.

**Comment by maabreve** [comment]
Hello,

Im sorry for the delay, I could not answer before ..

So, I just created a new NS/Angular2 application following the official documentation tutorial (http://docs.nativescript.org/angular/tutorial/ng-chapter-1.html), using the template - **_tns create HelloWorld --template nativescript-template-ng-tutorial_** -  and then I followed the steps described on **_https://medium.com /@enchev/minify-uglify-and-bundle-your-javascript-in-nativescript-angular-2-app-aabf84f47fbb#.k1x9mqxa4._**

After executing the commands, I got the following error messages:

Npm ERR! Windows_NT 10.0.14393
Npm ERR! C: \\ Program Files (x86) \\ Nodist \\ npmv \\ 4.0 \\ Nodist \\ v-x64 \\ 6.9.5 \\ node.exe. 5 \\ bin \\ npm-cli.js "
Run "" webpack-android "
Npm ERR! Node v6.9.5
Npm ERR! Npm v4.0.5
Npm ERR! Code ELIFECYCLE
Npm ERR! @ Webpack-android: `webpack --config = webpack.android.js --progress`
Npm ERR! Exit status 2
Npm ERR!
Npm ERR! Failed at the @ webpack-android script 'webpack --config = webpack.android.js --progress'.
Npm ERR! Make sure you have the latest version of node.js and npm installed.
Npm ERR! If you do, this is most likely to be a problem with the package,
Npm ERR! Not with npm itself.
Npm ERR! Tell the author that this fails on your system:
Npm ERR! Webpack --config = webpack.android.js --progress
Npm ERR! You can get information on how to open an issue for this project with:
Npm ERR! Npm bugs
Npm ERR! Or if that is not available, you can get their info via:
Npm ERR! Npm owner ls
Npm ERR! There is likely additional logging output above.

Npm ERR! Please include the following file with any support request:
Npm ERR! C: \ Users \ marcos.augustin \ documents \ pocs \ angular2 \ webpack \ helloworld \ npm-debug.log

Npm ERR! Windows_NT 10.0.14393
Npm ERR! C: \\ Program Files (x86) \\ Nodist \\ npmv \\ 4.0 \\ Nodist \\ v-x64 \\ 6.9.5 \\ node.exe. 5 \\ bin \\ npm-cli.js "
Run "" start-android-bundle "
Npm ERR! Node v6.9.5
Npm ERR! Npm v4.0.5
Npm ERR! Code ELIFECYCLE
Npm ERR! @ Prestart-android-bundle: `npm run webpack-android`
Npm ERR! Exit status 1
Npm ERR!
Npm ERR! Failed at the @ prestart-android-bundle script 'npm run webpack-android'.
Npm ERR! Make sure you have the latest version of node.js and npm installed.
Npm ERR! If you do, this is most likely to be a problem with the package,
Npm ERR! Not with npm itself.
Npm ERR! Tell the author that this fails on your system:
Npm ERR! Npm run webpack-android
Npm ERR! You can get information on how to open an issue for this project with:
Npm ERR! Npm bugs
Npm ERR! Or if that is not available, you can get their info via:
Npm ERR! Npm owner ls
Npm ERR! There is likely additional logging output above.

Npm ERR! Please include the following file with any support request:
Npm ERR! C: \ Users \ marcos.augustin \ documents \ pocs \ angular2 \ webpack \ helloworld \ npm-debug.log


Using the tns create MyApp --ng template, the process ends successfully ...

Im using Node 6.9.5 and  npm 4.0.5

I am trying to solve but I can not find the solution.

Thank you and again, sorry for the delay.
