### ISSUE TITLE
'FlexboxLayout' is not a known element

### ISSUE THREAD

**Issue by hamdiwanis** [NativeScript/nativescript-dev-webpack#417]
i get this with the aot flag
```
'FlexboxLayout' is not a known element:
1. If 'FlexboxLayout' is an Angular component, then verify that it is part of this module.

```

**Comment by NickIliev** [comment]
@hamdiwanis in the module where the flexbox layout is used make sure that you have included the `NO_ERRORS_SCHEMA` as shown [here]('FlexboxLayout' is not a known element)

**Comment by hamdiwanis** [comment]
that was indeed the problem thanks for your help.
