### ISSUE TITLE
App compiles ok with --bundle but only js in main page is executed

### ISSUE THREAD

**Issue by Andrea65** [NativeScript/nativescript-dev-webpack#427]
I get no errors with 'tns run android --bundle'
The app starts correctly and shows the first page.
If I click a button that navigates on a second page I see the second page but the associated js is never executed.
console.log in loaded function is never shown and no command is responding.
Any help?
Thanks

**Comment by sis0k0** [comment]
Hey, @Andrea65, is your app plain .js or .ts? If it is, can you please share the content of your bundle config? It should be located in `./app/bundle-config.js` (or .ts).

**Comment by Andrea65** [comment]
It is plain js
Here is the bundle-config.js

if (global.TNS_WEBPACK) {
    // registers tns-core-modules UI framework modules
    require("bundle-entry-points");

    // register application modules
    // This will register each `page` postfixed xml, css, js, ts, scss etc. in the app/ folder
    const context = require.context("~/", true, /(page|fragment)\.(xml|css|js|ts|scss|less|sass)$/);
    global.registerWebpackModules(context);
    //register application modules
    /* global.registerModule("main-page", function () { return require("./main-page"); });
    global.registerModule("classeA", function () { return require("./Pages/classeA/classeA"); });
    global.registerModule("progetto", function () { return require("./Pages/progetto/progetto"); });*/
    
}

As you can see from the commented lines I tried to register some single pages but with the same result.
Thanks for any help

**Comment by sis0k0** [comment]
You should be able to register the pages with the `global.registerModule` function. You should have the paths on the left side as well. Something like this:
``` js
global.registerModule("Pages/classeA/classeA", () => require("./Pages/classeA/classeA"));
```

The other option is to follow the convention from the regex and rename your pages to end with `page.xml`. Or you can also include all js files in the context:
```
const context = require.context("~/", true, /\.(js)$/);
```
If you don't have js files that you don't want in the final bundle, you can do it.

**Comment by Andrea65** [comment]
Thank you for your help
const context = require.context("~/", true, /\.(xml|css|js|ts|scss|less|sass)$/);
did the trick!

I always struggle with regex !

Now I'm facing some errors on specific plugins . Do you know how to exclude a plugin from webpack?

**Comment by sis0k0** [comment]
What do you mean by exclude? If you don't want it to be part of the generated bundle, you shouldn't have `require`s for it anywhere in the app.

**Comment by Andrea65** [comment]
Sorry for the bad explanation.
I have errors  such as this:

Error building UI from XML @file:///app/Pages/datiGenerali/datigenerali.xml:35,25
>module '/data/data/xxxx.xxx.xxxx/files/app/nativescript-drop-down

I have the same error in all plugins that have a UI component referenced in xml pages like
 xmlns:dd="nativescript-drop-down"

I was thinking of exluding those plugins from the bundle and leave them where they are.
I guess there is a better option though.

Thanks for the precious help

**Comment by sis0k0** [comment]
You need to register the plugins that have xml namespaces as well. Check out [this section](https://docs.nativescript.org/best-practices/bundling-with-webpack#dynamic-imports) in the docs.

**Comment by Andrea65** [comment]
I had a look at the docs but still I can't figure it out.
I put a require('nativescript-drop-down') in js code behind the xml  and the plugin is included in the bundle (I looked in the APK). Still I get this error opening the page:

module '/data/data/xxxx.xxx.xxxx/files/app/nativescript-drop-down
not found for element 'nativescript-drop-down:DropDown'

How can I register the plugins with xml namespace?

Thanks

**Comment by Andrea65** [comment]
Just put

global.registerModule("nativescript-drop-down", () => require("nativescript-drop-down"));

if bundle-config.js and it works.
Thank you
