### ISSUE TITLE
Webpack + worker: error with --env.uglify

### ISSUE THREAD

**Issue by Andrea65** [NativeScript/nativescript-dev-webpack#429]
I have a plain js app using workers.
If I webpack with --bundle the app works correctly.
if I use --env.uglify I get this error:

    ERROR in 0638725c2b2df55fbf3b.worker.js from UglifyJs
    Unexpected token: operator (>) [0638725c2b2df55fbf3b.worker.js:34967,36]

Any idea?

**Comment by NickIliev** [comment]
@Andrea65 if possible please provide a sample project reproducing the issue
