### ISSUE TITLE
How to watch changes files on device in real-time?

### ISSUE THREAD

**Issue by Symfomany** [NativeScript/nativescript-dev-webpack#43]
When I run script _npm run start-android-bundle_ & after i modify my app.component.html ,  

My App no reboot on my device for previsualtion  but in my console, there is several changes:

Transferring project files...
Successfully transferred all files.
Applying changes...

An idea please?

Thx for advance!

**Comment by Symfomany** [comment]
Hye,

Existing an Deboger on VSCOde synchronize with Webpack?

My launch.json configuration for android sync has failed :( Do you have some examples please?

Thx!!

**Comment by hdeshev** [comment]
Duplicate of #37
