### ISSUE TITLE
Webpack & NativeScript Pro UI - problems building

### ISSUE THREAD

**Issue by jorotenev** [NativeScript/nativescript-dev-webpack#432]
Hi
I tried to use webpack to build my project and got [this](https://gist.github.com/jorotenev/63ce3f7d0c19a47cbb06b9aa8400dca0)

I cloned the [nativescript-ui-samples](https://github.com/telerik/nativescript-ui-samples) repo, installed this plugin following the [steps](https://docs.nativescript.org/best-practices/bundling-with-webpack#installation-and-configuration) from the {N} site and after running `tns run android --bundle` got [this](https://gist.github.com/jorotenev/2eb21241a90ec788f2de856e3ab8e277). 

The errors seem different and I am not sure if I am missing something obvious.
My project's config:
```
"tns-android": {
      "version": "3.4.0"
    }
....
    "nativescript-pro-ui": "^3.1.4",
    "tns-core-modules": "^3.3.0",
    "webpack": "~3.10.0",
    "nativescript-dev-webpack": "^0.9.1",
    "typescript": "~2.6.2",
```

**Comment by NickIliev** [comment]
@jorotenev looking at nativescript-ui-samples application there are few things that need our consideration.
- the application uses [extended main activity](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/main-activity.android.ts). This means that we need to "introduce" this file to our webpack-config.js..

webpack.config.js as done [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/webpack.config.js#L20)
```
    const nativeClassExtenders = [
        join(__dirname, "app/main-activity.android.ts"),
    ];

    // more code follows here e.g. conts config = ....
```


Thhen in the same file (webpack.config.js) at the very bottom in the snapshot check add the extenders as done [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/webpack.config.js#L136)
```
if (snapshot) {
        config.plugins.push(new nsWebpack.NativeScriptSnapshotPlugin({
            chunk: "vendor",
            projectRoot: __dirname,
            webpackConfig: config,
            targetArchs: ["arm", "arm64", "ia32"],
            tnsJavaClassesOptions: {
                packages: ["tns-core-modules" ],
                modules: nativeClassExtenders,
            },
            useLibs: false
        }));
    }
```


Also if the snapshot is enabled you would need to explicitly register the extended activity file in the android specific vendor.ts file as done [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/vendor-platform.android.ts#L9)

vendor-platform.android.ts
```
require("application");
if (!global["__snapshot"]) {
    // In case snapshot generation is enabled these modules will get into the bundle
    // but will not be required/evaluated.
    // The snapshot webpack plugin will add them to the tns-java-classes.js bundle file.
    // This way, they will be evaluated on app start as early as possible.
    require("ui/frame");
    require("ui/frame/activity");
    require("./main-activity.android.ts");
}
```

Finally, make sure that all your XML file are using `-page` naming convention and if not add them to the bundle.ts config as shown [here](https://github.com/NativeScript/NativeScript/issues/5368#issuecomment-362519258). If your files are not following the `my-page.xml` convention you will need to add them manually to your bundle.config file
