### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by mouhsine123** [NativeScript/nativescript-dev-webpack#440]
i have installed the nativescript-gradient plugin in my project. When i run `tns run android` it works fine. But when i use `tns run android --bundle`, it seems that it does not recognise the plugin and i am getting the following error:
![image](https://user-images.githubusercontent.com/11781298/36409617-ec2f198c-1625-11e8-8e3e-bbe0f9139c27.png)

In the terminal, i could not see webpack including the plugin nativescript-gradient
![image](https://user-images.githubusercontent.com/11781298/36409650-195e445a-1626-11e8-9c11-7d9a612042e5.png)

**Versions**
nativescript-gradient: 2.0.1
nativescript-dev-webpack: 0.9.2

**Comment by NickIliev** [comment]
@mouhsine123 
Add the plugin to `vendor.ts` file like done [here](https://github.com/NativeScript/NativeScript/issues/2760#issuecomment-366719545)

In your case
```
global.registerModule("nativescript-gradient", ()=> require('../node_modules/nativescript-gradient'));
```
