### ISSUE TITLE
Webpack 4 Support

### ISSUE THREAD

**Issue by patrickpereira** [NativeScript/nativescript-dev-webpack#445]
Hi Nativescript!

Is webpack 4 supported?

**Comment by jogboms** [comment]
@patrickpereira was released just yesterday. 😁

**Comment by NickIliev** [comment]
@patrickpereira the currently supported version is 3.8.x. If unsure what version of Webpack is supported by NativeScript you can install `nativescript-dev-webpack` and then run the update script with
```
./node_modules/.bin/update-ns-webpack --deps --config
```
(Note: `--config` will recreate `webpack.config.js` so use this flag only if needed)

**Comment by vchimev** [comment]
Hey All,

the *webpack@4* support has landed in the `master` branch with this [pull request](https://github.com/NativeScript/nativescript-dev-webpack/pull/495).

It is already available with `next` tag on *npm*, however, there are a few more improvements we would like to add (e.g. https://github.com/NativeScript/nativescript-dev-webpack/pull/513), so please, follow [this](https://github.com/NativeScript/nativescript-dev-webpack/issues/492) issue for tracking our progress.
