### ISSUE TITLE
Slow startup even with webpack

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-dev-webpack#451]
_From @vahidvdn on March 1, 2018 14:15_

Hey. Of course there are some issues for this topic, but still annoying me. NativeScript is really slow on startup even with optimizations. With this command:

```
tns run android --bundle --env.uglify --env.aot --env.snapshot
```

It takes about 5 or 6 seconds on each startup. Any idea?

_Copied from original issue: NativeScript/NativeScript#5483_

**Comment by NickIliev** [comment]
@vahidvdn  without any code base that can investigate it is hard to speculate what might be causing the slow startup time on your side. Try profiling your application [using timeline-view](https://www.nativescript.org/blog/deep-dive-into-nativescript-3.1-performance-improvements) and/or the report option (``--env.report)

**Comment by vahidvdn** [comment]
@NickIliev It's an empty project. But I tested some apps that are available on google play. They run in less than 4 seconds. (about 3.5). It seems production builds are faster than dev builds.

**Comment by Nurgunkalol** [comment]
same problem, after update webpack, application its very slow on startup loading

**Comment by HoangJK** [comment]
Same probleam, I use NS 4.0 and start up very slow.

**Comment by alexma01** [comment]
it also depends on how you have structured the project.

**Comment by HoangJK** [comment]
My project is about 35MB when build with Webpack.

**Comment by Nurgunkalol** [comment]
any update about this issue?

**Comment by HoangJK** [comment]
@Nurgunkalol 
You can upgrade to NS 4+ and Webpack, app start really fast.

**Comment by vahidvdn** [comment]
@HoangJK Version 4.1 has lots of startup time improvements (more than two times faster) and much more [changes](https://github.com/NativeScript/NativeScript/blob/release/CHANGELOG.md#410-2018-05-28). Just run `tns update` .
If couldn't be able to update, reinstall nativescript cli.
