### ISSUE TITLE
Why was Snapshot disabled on debug builds?

### ISSUE THREAD

**Issue by DickSmith** [NativeScript/nativescript-dev-webpack#487]
0.10.0 removed the ability to run a snapshot build on debug, but there is no explanation of why?

In getting my repo and plugins to be able to support snapshot, I had to run dozens and dozens of builds to update plugins to be snapshot compatible, and I often still run it on debug just to check overall performance from time to time. (I almost never generate release builds on my local machine, but only via Travis CI, since the command for release is painfully long.)

I can understand if there is good reason for disabling this ability, but none is given in the PRs or the CHANGELOG, even though it is acknowledged as a breaking change.

**Comment by jogboms** [comment]
@DickSmith See [here](https://github.com/NativeScript/nativescript-dev-webpack/pull/486#discussion_r179698983) by @sis0k0 if it helps.

**Comment by DickSmith** [comment]
Can use this instead to debug:
`./node_modules/.bin/webpack --env.android --env.aot --env.uglify --env.snapshot`
