### ISSUE TITLE
ERROR in ./main.aot.ts "NativeScriptAngularCompilerPlugin." 

### ISSUE THREAD

**Issue by MuhammadTahir92** [NativeScript/nativescript-dev-webpack#491]
when i run command  

> tns build android --bundle --env.aot "
for

 production following results are shown.
```

ERROR in ./main.aot.ts
Module build failed: Error: D:\projects\troutBird\mobile-app\app\main.aot.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at NativeScriptAngularCompilerPlugin.getCompiledFile (D:\projects\troutBird\mobile-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:663:23)
    at NativeScriptAngularCompilerPlugin.getCompiledFile (D:\projects\troutBird\mobile-app\node_modules\nativescript-dev-webpack\plugins\NativeScriptAngularCompilerPlugin.ts:76:22)
    at plugin.done.then (D:\projects\troutBird\mobile-app\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
Webpack compilation complete.
Executing webpack failed with exit code 2.
```

**Comment by jogboms** [comment]
@MuhammadTahir92 did you do a cross-check with what the error message explains?

**Comment by MuhammadTahir92** [comment]
I do this but this error show's now 

> ERROR in ./main.aot.ts
> Module build failed: Error: E:\projects\troutBird\mobile-app-without-prod\mobile-app\app\main.aot.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
>     at NativeScriptAngularCompilerPlugin.getCompiledFile (E:\projects\troutBird\mobile-app-without-prod\mobile-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:643:23)
>     at NativeScriptAngularCompilerPlugin.getCompiledFile (E:\projects\troutBird\mobile-app-without-prod\mobile-app\node_modules\nativescript-dev-webpack\plugins\NativeScriptAngularCompilerPlugin.ts:75:22)
>     at plugin.done.then (E:\projects\troutBird\mobile-app-without-prod\mobile-app\node_modules\@ngtools\webpack\src\loader.js:467:39)
>     at <anonymous>
MY tsconfig.json is 
`{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ],
            "~/*": [
                "app/*"
            ]
        }
    },
    "extends": "./tsconfig.json",
    "exclude": [
        "node_modules",
        "platforms",
    ]
}
`

**Comment by MuhammadTahir92** [comment]
It works i did not updated the file correctly 
thanks friends
