### ISSUE TITLE
Error building with webpack 0.9.2

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/nativescript-dev-webpack#502]
I'm using NS 4.0 with TNS-CORE-MODULES 4.0

iOS platform 4.0.1

and using Webpack 0.9.2.

    npm install --save-dev nativescript-dev-webpack@0.9.2

Getting the following error:

/Users/asrock/Documents/publish-ios
└─┬ nativescript-dev-webpack@0.9.2 
  ├─┬ nativescript-hook@0.2.2 
  │ └── glob@6.0.4 
  │ └── ajv-keywords@2.1.1 
<snipped>
  ├── semver@5.4.1 
  ├── shelljs@0.6.0 
  └── UNMET PEER DEPENDENCY webpack@^2.0.0 || ^3.0.0

npm WARN schema-utils@0.4.3 requires a peer of webpack@^2.0.0 || ^3.0.0 but none was 

I don't get this with Webpack 0.8.0

**Comment by vchimev** [comment]
Hey @erjdriver,

After adding the `nativescript-dev-webpack@0.9.2` plugin to your project, there should be the following output:

```
A few new dependencies were added. Run "npm install" before building your project.

npm WARN nativescript-angular@5.3.0 requires a peer of typescript@~2.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN schema-utils@0.4.3 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
```

As mentioned, an additional `npm install` is required in order to install newly added dependencies - it will install the `webpack` dependency itself and address this warning.

**Comment by erjdriver** [comment]
I was doing that also - but was getting that error on the initial `npm install` - so I thought that was a problem that needed to be looked into.

I'm doing this now

` npm install --save-dev nativescript-dev-webpack@0.9.2

   npm install
   ./node_modules/.bin/update-ns-webpack --configs --deps

    npm install`

Necessary for the 2 npm installs?


Thanks.

**Comment by vchimev** [comment]
@erjdriver,

if you install the `nativescript-dev-webpack` plugin for the first time to your project, there is no need to execute the `update-ns-webpack` script as the initial installation will add required configs and dependencies to the project - this script helps to update to a higher version of the plugin as usually there are changes in the configs and dependencies, which require execution of `npm install`.
