### ISSUE TITLE
How to uninstall this plugin

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/nativescript-dev-webpack#504]
I tried

`npm uninstall --save-dev nativescript-dev-webpack`

and it still leaves a much of modules behind.

and the hooks are still set.

Thanks.

**Comment by NickIliev** [comment]
@erjdriver you could delete the `hooks` folder manually. As for the additional `devDependencies` that are left behind you should remove them by hand. Even if not removed, that shouldn't bother you much as the webpack plugin is bringing only developer dependencies (`devDependencies`) and those will not be a part of your built application file.
