### ISSUE TITLE
AOT iOS Crash

### ISSUE THREAD

**Issue by Ericky14** [NativeScript/nativescript-dev-webpack#521]
When running `tns publish ios --bundle --env.uglify --env.aot --release --for-device`, the app crashes on iOS as soon as it opens. I am not being able to identify the issue. Does anyone have any idea what it could be?

**Comment by NickIliev** [comment]
@Ericky14 the command publish expects an IPA file and not the flags for bundling. So first create your production IPA with Webpack (`tns run ios --bundle --env.uglify --env.aot --release --for-device`) and then publish the generated IPA file with
```
tns publish ios --ipa <Ipa File Path>
```

**Comment by Ericky14** [comment]
@NickIliev 
According to the docs, ```tns publish ios``` does build and upload the app if no IPA file is provided.
https://docs.nativescript.org/angular/docs-cli/publishing/publish-ios
