### ISSUE TITLE
Webpack recompile fails when using AoT with watch mode

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-dev-webpack#547]
## Issue Checklist

- [x] You are submitting: a bug report
- [x] You verified that this is a real problem by searching the [NativeScript Forum] and the other [issues] in this repo.
- [x] You checked our [demo apps] and the [documentation] for sample usage.

## Tell us about the problem
When running webpack in watch mode with Ahead-of-time compilation enabled, the first change causes the webpack compiler to throw an error and exit.

## Steps to reproduce
```
tns create someapp --ng && cd someapp
tns run android --bundle --env.aot
```

[NativeScript Forum]: http://forum.nativescript.org
[issues]: https://github.com/nativescript/nativescript-dev-webpack/issues?utf8=✓&q=is%3Aissue
[demo apps]: ../demo
[documentation]: https://docs.nativescript.org/best-practices/bundling-with-webpack

**Comment by jolafrite** [comment]
same here, I get the following error:

```
Error: ENOENT: no such file or directory, stat '/Users/user/Downloads/ns-project/app/app.component.ngfactory.js'
```
