### ISSUE TITLE
Ui elements issue

### ISSUE THREAD

**Issue by ivanpadavan** [NativeScript/nativescript-dev-webpack#55]
If HTML is provided as a template inside component decorator, then webpack doesn't include code from 'ui/...' needed for this page.

**Comment by hdeshev** [comment]
Hey @ivanpadavan, can you get me a sample project using the latest nativescript-dev-webpack plugin?

We recently added a tweak to the AoT tsconfig that maps modules like `ui/...` to `node_modules/tns-core-modules/ui/...` which might fix your problem too.

**Comment by ivanpadavan** [comment]
My last repo. It trowed "cannot reach ui/.." errors, until replacing all the "template" properties to "templateUrl"
