### ISSUE TITLE
upgrading to 0.12 breaks older projects with nativescript-ui-sidedrawer

### ISSUE THREAD

**Issue by pbgc** [NativeScript/nativescript-dev-webpack#555]
Following the instructions to upgrade an older (pre - 4.0 that was working perfectly on 4.0 and 4.1, with webpack 3) to 0.12 (https://www.nativescript.org/blog/upgrading-to-nativescript-webpack-0.12.0) and deleting bundle-config.js breaks the sidedrawer.

To get it woking I need to import a bundle-config.js with at least these lines:

if (global.TNS_WEBPACK) {
  // This will register each `page` postfixed xml, css, js, ts, scss etc. in the app/ folder
  context = require.context("~/", true, /(page|fragment)\.(xml|css|js|ts|scss|less|sass)$/);
  global.registerWebpackModules(context);
}

because older projects (created by Sidekick!) use:

app/shared/drawer-fragment.xml
app/shared/drawer-fragment.android.xml
....

and it seems that only content with suffix '-page' is processed by the new webpack.config and not the ones with '-fragment' like before using the bundle-config.js

**Comment by NickIliev** [comment]
@pbgc indeed this might happen as there are some changes in nativescript-dev-webpack@0.12.

```
Bundle config loader
The bundle-config-loader is applied to the entry module and its job is to insert a few predefined configurations. It has the following options:

registerPages <boolean>

Default: true

Registers your app’s XML, CSS and JavaScript pages with a regex. All your pages' resources should be named so that they end with either root or page. For example - main-page.xml, main-page.css, main-page.js.
```

Migration guide [here](https://www.nativescript.org/blog/upgrading-to-nativescript-webpack-0.12.0)
