### ISSUE TITLE
0.12 does not correctly include pages and the bundle fails

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-dev-webpack#556]
## Issue Checklist

- [x] You are submitting:  bug report
- [x] You verified that this is a real problem by searching the [NativeScript Forum] and the other [issues] in this repo.
- [x] You checked our [demo apps] and the [documentation] for sample usage.

## Tell us about the problem
Upgraded a projects that has a complex structure of pages/fragments. All views are located in their own subfolder under `app/views`. There are also "fragments" located in their own subfolder under `app/fragments`. Seems web pack does not include any of those because it has a hardcoded regex check here:
https://github.com/NativeScript/nativescript-dev-webpack/blob/3e0f38177574893cf964c591e2b0b4206afc4772/register-modules.js#L2

And from what I see there is no way to override this from the config file. So unless you are naming your pages with a `page` somewhere in them and/or put them in a page folder you are stuck. 
Also having the rule written like that in case you have done normal build it will double include styles as locally you have both `css` and `scss` files. 

There should be an option to specify your own regex rule. Or at least have ability to register those modules like we did in previous versions

## Local environment

- [x] Platform Mac
- [x] Node version 8.9.4
- [x] NativeScript CLI version 4.1.0

## Project data

- [x] Platform you are building the app for iOS

[webpack-ios-crash.zip](https://github.com/NativeScript/nativescript-dev-webpack/files/2073216/webpack-ios-crash.zip)

**Comment by pbgc** [comment]
@PeterStaev I filled a similar issue #555 
You can still register using the bundle-config.js aproach like before:

if (global.TNS_WEBPACK) {
// This will register each page postfixed xml, css, js, ts, scss etc. in the app/ folder
context = require.context("~/", true, /(page|fragment).(xml|css|js|ts|scss|less|sass)$/);
global.registerWebpackModules(context);
}

this (with changes for your case) works .. but there should be a option to specify this on the webpack.config

**Comment by PeterStaev** [comment]
@pbgc nice workaround! I first tried that but also had the register of the plugins in the file, so it crashed and I thought that the functions to register the modules have been removed. After I left only to register xml, ts, sass files it is working like a charm! But I also disabled the automatic registration of pages in my `webpack.config.js` so it does not do a double registration. 

Still think this should allowed as an option in the config file (if possible?) and the docs should indicate that you can still register manually your files in case they don't follow the predefined naming scheme. Otherwise from the blog article you are left with the impression that there is no way to do this.

**Comment by pbgc** [comment]
@PeterStaev 
I opted to register only the 'fragment' prefixed assets with bundle-config and leave the  automatic registration enabled in webpack.config. This way I do not have to change webpack.config on every TS update and everything still works without double registration.
