### ISSUE TITLE
Error after upgrading webpack 0.12.0

### ISSUE THREAD

**Issue by kshipraShelke** [NativeScript/nativescript-dev-webpack#560]
error: BaseAdapter_vendor_1_1638334_n is not abstract and does not override abstract method onNothingSelected(AdapterView<?>) in OnItemSelectedListener
public class BaseAdapter_vendor_1_1638334_n extends android.widget.BaseAdapter implements com.tns.NativeScriptHashCodeProvider, android.widget.AdapterView.OnItemSelectedListener {

error: Spinner_vendor_1_1637699_n is not abstract and does not override abstract method onNothingSelected(AdapterView<?>) in OnItemSelectedListener
public class Spinner_vendor_1_1637699_n extends android.widget.Spinner implements com.tns.NativeScriptHashCodeProvider, android.widget.AdapterView.OnItemSelectedListener {

Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed;

I get this error after running command with webpack
tns run android --bundle --env.uglify --env.aot --env.snapshot

upgraded recently Nativescript 4.1.0 and angular 6 
Node  v8.9.1
package.json 
 "dependencies": {
    "@angular/common": "~6.0.0",
    "@angular/compiler": "~6.0.0",
    "@angular/core": "~6.0.0",
    "@angular/forms": "~6.0.0",
    "@angular/http": "~6.0.0",
    "@angular/platform-browser": "~6.0.0",
    "@angular/platform-browser-dynamic": "~6.0.0",
    "@angular/router": "~6.0.0",
    "date-fns": "^1.28.5",
    "nativescript-angular": "^6.0.0",
    "nativescript-background-http": "3.1.0",
    "nativescript-bottombar": "3.0.7",
    "nativescript-camera": "~3.1.2",
    "nativescript-cardview": "^2.0.5",
    "nativescript-contacts-lite": "0.2.5",
    "nativescript-drop-down": "3.1.0",
    "nativescript-emoji": "^1.1.1",
    "nativescript-exoplayer": "^3.4.0",
    "nativescript-floatingactionbutton": "^4.1.0",
    "nativescript-fresco": "3.0.6",
    "nativescript-geolocation": "4.2.6",
    "nativescript-gradient": "^2.0.1",
    "nativescript-imagecropper": "0.0.7",
    "nativescript-imagepicker": "3.0.7",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-mediafilepicker": "^1.0.5",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-ngx-fonticon": "4.0.0",
    "nativescript-popup": "^1.4.0",
    "nativescript-push-notifications": "^1.1.0",
    "nativescript-ripple": "^2.0.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-autocomplete": "^3.7.1",
    "nativescript-ui-dataform": "^3.5.2",
    "nativescript-ui-gauge": "^3.5.0",
    "nativescript-ui-listview": "^3.5.7",
    "nativescript-ui-sidedrawer": "^4.0.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "~6.0.0 || >=6.1.0",
    "rxjs-compat": "^6.2.0",
    "tns-core-modules": "^4.1.0",
    "tns-platform-declarations": "^4.1.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/core": "~0.6.3",
    "@angular/compiler-cli": "~6.0.0",
    "@ngtools/webpack": "~6.0.3",
    "@types/chai": "^4.0.2",
    "@types/mocha": "^2.2.41",
    "@types/node": "^7.0.5",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "^3.0.1",
    "copy-webpack-plugin": "~4.5.1",
    "css-loader": "~0.28.11",
    "extract-text-webpack-plugin": "~3.0.2",
    "filewalker": "^0.1.3",
    "jasmine-core": "^2.6.2",
    "karma": "^1.7.0",
    "karma-jasmine": "^1.0.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-appium": "~3.2.0",
    "nativescript-dev-typescript": "^0.6.0",
    "nativescript-dev-webpack": "^0.12.0",
    "nativescript-worker-loader": "~0.9.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.3.0",
    "tslint": "^5.4.2",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.2.5",
    "webpack": "~4.6.0",
    "webpack-bundle-analyzer": "~2.13.0",
    "webpack-cli": "~2.1.3",
    "webpack-sources": "~1.1.0"
  }

**Comment by jeremypele** [comment]
Same here

``` registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
/Users/jeremypele/workspace/mobile-app/platforms/android/app/src/main/java/com/tns/gen/android/widget/BaseAdapter_script_37_2468811_r.java:8: error: BaseAdapter_script_37_2468811_r is not abstract and does not override abstract method onNothingSelected(AdapterView<?>) in OnItemSelectedListener
public class BaseAdapter_script_37_2468811_r extends android.widget.BaseAdapter implements com.tns.NativeScriptHashCodeProvider, android.widget.AdapterView.OnItemSelectedListener {
       ^
/Users/jeremypele/workspace/mobile-app/platforms/android/app/src/main/java/com/tns/gen/android/widget/Spinner_script_37_2468176_r.java:8: error: Spinner_script_37_2468176_r is not abstract and does not override abstract method onNothingSelected(AdapterView<?>) in OnItemSelectedListener
public class Spinner_script_37_2468176_r extends android.widget.Spinner implements com.tns.NativeScriptHashCodeProvider, android.widget.AdapterView.OnItemSelectedListener {
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 ```

**Comment by jeremypele** [comment]
@kshipraShelke Did you search on your code base where `android.widget.Spinner` is defined/called?

From what I see `nativescript-drop-down` is out of date and use `android.widget.Spinner`

**Comment by kshipraShelke** [comment]
@jeremypele updated nativescript-drop-down 4.0.0 but still same error.
I guess android.widget.Spinner is used for Activity Indicator.
If removed ActivityIndicator , the android.widget.Spinner error is gone but now showing baseAdapter error

error: BaseAdapter_vendor_1_1638334_n is not abstract and does not override abstract method onNothingSelected(AdapterView<?>) in OnItemSelectedListener
public class BaseAdapter_vendor_1_1638334_n extends android.widget.BaseAdapter implements com.tns.NativeScriptHashCodeProvider, android.widget.AdapterView.OnItemSelectedListener {

**Comment by NickIliev** [comment]
@kshipraShelke  @jeremypele  I've created [this demo application](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-dev-webpack/issue-560) using the latest version of the nativescript-drop-drown plugin in an Angular based application and everything is working as expected. Let me know if using the latest version of the plugin and nativescript-dev-webpack is resolving the case on your side.

One thing I've noticed is that the latest version of the plugin is automatically registering the `DropDown` element [so these lines are no longer needed](https://github.com/NickIliev/NS-Issues-2018-II/blob/master/nativescript-dev-webpack/issue-560/app/app.module.ts#L18-L19) (in fact, the build will crash if they are added).

@PeterStaev ^^^ perhaps this is a candidate for README update

**Comment by PeterStaev** [comment]
@NickIliev , note the `Remove` bullet before those lines so I think it is clear that if you are using 3.0+ version of the plugin you dont need to have that line and if you have it (in case you are upgrading from earlier versions) you have to remove it 😉
