### ISSUE TITLE
Navigatable page modules must be manually registered with webpack

### ISSUE THREAD

**Issue by Pip3r4o** [NativeScript/nativescript-dev-webpack#6]
Application cannot start up because it's `"startup"` module doesnt get packed inside the bundle.

``` javascript
var application = require("application");
application.start({ moduleName: "main-page"});
```

**Comment by Pip3r4o** [comment]
As discussed with @jasssonpet and @blagoev, a workaround, which certainly wouldn't work in all general cases, is to `global.registerModule('main-page', function() { return require('./main-page') });` for every view, and view model (XML + JS). 

The changes in https://github.com/NativeScript/NativeScript/pull/2357/files also need to be applied

**Comment by hdeshev** [comment]
We fixed a similar issue for build-in components by introducing the [bundle-entry-points](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/bundle-entry-points.ts) module, which `application` requires (to make it discoverable by webpack).

Application-level modules such as pages (e.g. `main-page`) should be manually registered using `global.registerModule`. The perfect solution here would be to introduce a build step that generates a registration module, or maybe provide a webpack plugin or loader (or both) to do the same.

**Comment by hdeshev** [comment]
The project templates now contain a sample registration for their page, and the documentation covers how to register new modules. I'll reopen or reference this issue, if we decide to add a build tool that would generate registrations automatically.
