### ISSUE TITLE
Typescript compilation fails when building an angular app with a linked module

### ISSUE THREAD

**Issue by lini** [NativeScript/nativescript-dev-webpack#612]
## Issue Checklist

- [x] You are submitting: a bug report. 
- [x] You verified that this is a real problem by searching the [NativeScript Forum] and the other [issues] in this repo.
- [x] You checked our [demo apps] and the [documentation] for sample usage.

## Tell us about the problem
When building an app with a linked plugin source, TS compilation fails with:
```
ERROR in C:/nativescript-fresco/src/nativescript-fresco.ts
Module build failed: Error: C:\nativescript-fresco\src\nativescript-fresco.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\nativescript-fresco\demo-angular\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:951:15)
    at plugin.done.then (C:\nativescript-fresco\demo-angular\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ C:/nativescript-fresco/src/angular/nativescript-fresco.module.ts 16:53-67
 @ C:/nativescript-fresco/src/angular/index.ts
 @ ./app.module.ts
 @ ./main.ts
Webpack compilation complete.
Executing webpack failed with exit code 2.
```

## Local environment

- [x] Platform Windows
- [x] Node version v8.9.1 NPM version 6.1.0
- [x] NativeScript CLI version 4.1.1
- [x] nativescript-dev-webpack 0.14.4

## Project data

- [x] Platform you are building the app for Android 
- [x] Node dependencies:
https://github.com/NativeScript/nativescript-fresco/tree/579156f0f899a498b3ac3330c7ca6836582f4226/demo-angular

**Comment by elena-p** [comment]
The issue also happens on macOS.
https://github.com/NativeScript/nativescript-camera/tree/master/demo-angular 
adding "../src" or "../src/**/*" in the 'include' property of the tsconfig file doesn't help.
