### ISSUE TITLE
Unable to webpack ts app. Can't resolve 'navigation/example-page'

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/nativescript-dev-webpack#627]
Using this app https://github.com/NativeScript/nativescript-ui-autocomplete/tree/master/demo and "nativescript-dev-webpack": "~0.15.0" we are unable to build with _tns run ios --bundle --env.uglify --for-device --release_ . Same happens for android. It throws separate error for each xml : 
..
ERROR in ./examples/completion-mode/autocomplete-startswith-page.xml
Module not found: Error: Can't resolve 'navigation/example-page' in '/Users/branzov/Git/nativescript-ui-autocomplete/demo/app/examples/completion-mode'
 @ ./examples/completion-mode/autocomplete-startswith-page.xml 1:69-103 1:189-223
 @ . sync (root|page)\.(xml|css|js|ts|scss)$
 @ ./app.ts

ERROR in ./examples/completion-mode/autocomplete-contains-page.xml
Module not found: Error: Can't resolve 'navigation/example-page' in '/Users/branzov/Git/nativescript-ui-autocomplete/demo/app/examples/completion-mode'
 @ ./examples/completion-mode/autocomplete-contains-page.xml 1:69-103 1:189-223
 @ . sync (root|page)\.(xml|css|js|ts|scss)$
 @ ./app.ts
..

**Comment by NickIliev** [comment]
Related to using [a code-behind created page](https://github.com/NativeScript/nativescript-ui-autocomplete/blob/master/demo/app/navigation/example-page.ts) via [XML namespace ](https://github.com/NativeScript/nativescript-ui-autocomplete/blob/master/demo/app/examples/completion-mode/autocomplete-contains-page.xml#L1)

**Comment by manoldonev** [comment]
@zbranzov @NickIliev I tested this again with latest dts changes (still on PR 
https://github.com/NativeScript/nativescript-ui-autocomplete/pull/41) and everything works as expected on both iOS and Android (with and without webpack, uglify) with no need to define custom bundle-config.

**Comment by sis0k0** [comment]
The fix will be released with 0.18.4.
