### ISSUE TITLE
Exclude Comments/Filenames When Uglifying

### ISSUE THREAD

**Issue by vbresults** [NativeScript/nativescript-dev-webpack#68]
@hdeshev At this time, script paths are reserved when uglifying in the form of comments

**Comment by hdeshev** [comment]
Is this really an issue? Comment output is controlled by an UglifyJSPlugin option. Anyone bothered by it, can turn it off in his/her config.

https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#options
