### ISSUE TITLE
ENOENT: no such file or directory, open '../project/platforms/android/app/src/main/assets/app/tns_modules/npm/node_modules/node-gyp/node_modules/.bin/package.json'

### ISSUE THREAD

**Issue by luisalcarasr** [NativeScript/nativescript-dev-webpack#709]
**Environment**
 - CLI: 5.0
 - Cross-platform modules: ^5.0.2
 - Android Runtime: 5.0.0 - API 27
 - Plugin(s):
      - "nativescript-angular": "~6.1.0",
      - "nativescript-cardview": "^3.1.1",
      - "nativescript-feedback": "^1.2.0",
      - "nativescript-floatingactionbutton": "^4.1.3",
      - "nativescript-geolocation": "^4.3.0",
      - "nativescript-loading-indicator": "^2.4.0",
      - "nativescript-modal-datetimepicker": "^1.1.3",
      - "nativescript-ng-shadow": "^2.1.0",
      - "nativescript-ngx-slides": "^6.0.0",
      - "nativescript-oauth": "^2.1.7",
      - "nativescript-phone": "^1.3.1",
      - "nativescript-plugin-firebase": "^6.5.0",
      - "nativescript-pulltorefresh": "^2.1.1",
      - "nativescript-snackbar": "^3.2.0",
      - "nativescript-theme-core": "~1.0.4",
      - "nativescript-toast": "^1.4.6",
      - "nativescript-ui-sidedrawer": "^4.2.1",

**Describe the bug**
When I tried to run the project after cloning in a new computer with NativeScript 5.0 installed this message is shown, yet. I have upgraded the project but this message is shown.

**To Reproduce**
Yo need to clone a project with an old project and run with the new NativeScript CLI (5.0.0).
`tns run android`

**Expected behaviour**
The application is compiled and executed correctly.

**Comment by NickIliev** [comment]
@luisalcarasr can you clarify which project are you trying to build? Is this something related to webpack (as I am not seeing the `--bundle` flag in your description but still the issue is logged in the webpack repository) Try to reset your` platforms` and `node_modules` folders and rebuild the project

**Comment by luisalcarasr** [comment]
Using NativeScript CLI 4.2.4 works!

`sudo npm install nativescript@4.2.4 -g --unsafe-perm`

**Comment by Jmchemama** [comment]
Hi, i have a same issue.

Using NativeScript CLI 4.2.4 is not a solution because i need to upgrade 5.0 nativescript.

`Processing node_modules failed. Error: ENOENT: no such file or directory, open '/Users/******/Documents/*****/platforms/android/app/src/main/assets/app/tns_modules/nativescript/node_modules/ios-device-lib/node_modules/.bin/package.json'`

if i look to /Users/******/Documents/*****/platforms/android/app/src/main/assets/ i just have one folder `internal`.

**Comment by marcuschoong** [comment]
i having this problem. how to resolve this in nativescript 5 without downgrade the nativescript version to 4.2.4.

**Comment by ryanlangton** [comment]
why is the fix to use an older version of Nativescript??

**Comment by Fatme** [comment]
```
rm -rf platforms
npm un npm --save
tns run android
```

**Comment by jibon57** [comment]
@Fatme I have almost similar problem after update to NativeScript `5.1.1`.

`Unable to apply changes on device: D7437733-7F30-4690-B238-26B5C9F2B39E. Error is: Processing node_modules failed. Error: ENOENT: no such file or directory, open '/Users/jibon/openroadenglish/platforms/ios/openroadenglish/app/tns_modules/npm/node_modules/request/node_modules/.bin/package.json'.`

I ran npm un npm --save but still error. Please give me suggestion.

**Comment by Fatme** [comment]
@jibon57,
you need to delete `platforms` folder as well.

**Comment by jibon57** [comment]
@Fatme I ran `rm -rf hooks node_modules platforms package-lock.json` but still same problem. I am also discussing here: https://github.com/NativeScript/nativescript-cli/issues/3864

**Comment by glorious73** [comment]
The solution that worked for me in nativescript 6.5.0 is composed of the following commands:
```
rm -rf platforms package-lock.json node_modules
npm i
tns run android --env.uglify --bundle --clean 
```
