### ISSUE TITLE
Usage with `tns test`

### ISSUE THREAD

**Issue by Fedelaus** [NativeScript/nativescript-dev-webpack#715]
I'm currently relying on this to build my Angular 6 application as we utilize tsconfig paths and those are unavailable without nativescript-dev-webpack currently.

I've noticed running `tns test android --bundle` executes webpack but instead of running tests just executes the application.

Is it possible to utilize this with the testing suite provided by NativeScript?

**Comment by nkalscheuer** [comment]
Any answer for this?

**Comment by Fedelaus** [comment]
Is there any sort of update for this?

**Comment by Fatme** [comment]
@Fedelaus,

We've already implemented this feature - https://github.com/NativeScript/nativescript-cli/issues/4392.
```
npm i -g nativescript@latest
tns create myTestApp --js
cd myTestApp
tns test android --bundle
```

I'm closing this as a duplicate to https://github.com/NativeScript/nativescript-cli/issues/4392
