### ISSUE TITLE
Entry module not found [app.css]

### ISSUE THREAD

**Issue by triniwiz** [NativeScript/nativescript-dev-webpack#73]
Bundling fails if i only use platform specific stylesheets e.g `app.android.css`

```
ERROR in Entry module not found: Error: Can't resolve './app.css' in '/Users/triniwiz/WebstormProjects/theApp/app'
```

**Comment by hdeshev** [comment]
You need a different approach here. Have app.css import a platform-specific app-platform.*.css file, and have webpack autoresolve it through its extension matching mechanism.

Here's how I did it in another project:

https://github.com/NativeScript/nativescript-marketplace-demo/pull/252/commits/76313995d06780b8035562023fcd040c9d0c9aaf
