### ISSUE TITLE
Problem when use template tutorial NS/Angular (nativescript-template-ng-tutorial)

### ISSUE THREAD

**Issue by maabreve** [NativeScript/nativescript-dev-webpack#74]
Hi,

My application was created using the Angular tutorial template ** _ nativescript-template-ng-tutorial _ ** and when I try to minify the project I'm getting an error.

I tried with a new application using the template and got the same error.

- tns create HelloWorld --template nativescript-template-ng-tutorial
- cd HelloWorld
- npm install --save-dev nativescript-dev-webpack
- npm run start -android-bundle
 
I am trying to verify what is happening but I am not having success. Can you guys help me, please?

Thank you so much!!

node  - 6.9.4
npm  - 4.1.2
nativescript  - 2.4.2

**Error:**
Hash: 4ed05f4b3014c94d8500
Version: webpack 2.2.0
Time: 30632ms
           Asset       Size  Chunks                    Chunk Names
       bundle.js    1.95 MB       0  [emitted]  [big]  bundle
      app.css.js  268 bytes       1  [emitted]         app.css
       vendor.js    3.29 MB       2  [emitted]  [big]  vendor
         app.css    13.7 kB       1  [emitted]         app.css
images/apple.jpg     277 kB          [emitted]  [big]
    package.json    2.39 kB          [emitted]
      starter.js   41 bytes          [emitted]
   [0] ../~/@angular/core/index.js 2.5 kB {2} [built]
 [150] ../~/nativescript-angular/nativescript.module.js 2.12 kB {2} [built]
 [151] ../~/reflect-metadata/Reflect.js 48.2 kB {2} [built]
 [369] ../~/@angular/http/index.js 734 bytes {2} [built]
 [370] ../~/nativescript-angular/forms.js 1.46 kB {2} [built]
 [371] ../~/nativescript-angular/platform-static.js 787 bytes {2} [built]
 [372] ../~/nativescript-angular/platform.js 1.77 kB {0} [built]
 [373] ../~/nativescript-angular/router.js 3.06 kB {2} [built]
 [374] ./app.component.ts 1.01 kB {0} [built]
 [375] ./vendor-platform.android.ts 1.08 kB {2} [built]
 [582] ./app.css 41 bytes {1} [built]
 [583] ./main.ts 1.27 kB {0} [built]
 [584] ./vendor.ts 405 bytes {2} [built]
 [585] ../~/nativescript-css-loader!../~/nativescript-theme-core/css/core.light.android.css 13.9 kB [built]
 [586] ../~/nativescript-css-loader/lib/css-base.js 1.51 kB [built]
    + 572 hidden modules

WARNING in ./app.css
  resolve-url-loader cannot operate: CSS error
  C:\Users\marcos\documents\visionnaire\helloworld\app\app.css:9:1: missing '{'
  at error (C:\Users\marcos\documents\visionnaire\helloworld\node_modules\css\lib\parse\index.js:62:15)

ERROR in Could not resolve "C:\Users\marcos\documents\visionnaire\helloworld\app\app.module" from "C:\Users\marcos\documents\visionnaire\helloworld\app\app.module".
Child extract-text-webpack-plugin:
       [0] ../~/nativescript-css-loader/lib/css-base.js 1.51 kB {0} [built]
       [1] ../~/nativescript-css-loader!../~/nativescript-theme-core/css/core.light.android.css 13.9 kB {0} [built]
       [2] ../~/resolve-url-loader!../~/nativescript-css-loader!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css 289 bytes {0} [built] [1 warning]

    WARNING in ../~/resolve-url-loader!../~/nativescript-css-loader!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css
      resolve-url-loader cannot operate: CSS error
      C:\Users\marcos\documents\visionnaire\helloworld\app\app.css:9:1: missing '{'
      at error (C:\Users\marcos\documents\visionnaire\helloworld\node_modules\css\lib\parse\index.js:62:15)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "webpack-android"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ webpack-android: `webpack --config=webpack.android.js --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ webpack-android script 'webpack --config=webpack.android.js --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config=webpack.android.js --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\marcos\documents\visionnaire\helloworld\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-android-bundle"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ prestart-android-bundle: `npm run webpack-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prestart-android-bundle script 'npm run webpack-android'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run webpack-android
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\marcos\documents\visionnaire\helloworld\npm-debug.log

**Comment by sis0k0** [comment]
Hi @maabreve,

The problem is that the default `webpack.config` expects to find the root `AppModule` in the file `app/app.module.js`. However, the template defines the above module in the file `main.ts`. Luckily, it's easy to split the two files:

``` ts
// app/app.module.ts
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";

import { AppComponent } from "./app.component";

@NgModule({
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  imports: [NativeScriptModule],
  schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule {}
```

``` ts
// app/main.ts
import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import { AppModule } from "./app.module";

platformNativeScriptDynamic().bootstrapModule(AppModule);
```

Also for generating ahead-of-time compiled bundle with webpack you'll need to bootstrap your root module with the static platform instead of the dynamic one. The default place to do that is the `app/main.aot.ts` file. It usually looks like:

``` ts
import { platformNativeScript } from "nativescript-angular/platform-static";
import { AppModuleNgFactory } from "./app.module.ngfactory";

platformNativeScript().bootstrapModuleFactory(AppModuleNgFactory);
```

Let us know if that helped!

**Comment by maabreve** [comment]
Hi, 

Thank you very much for your quick response.

Worked perfectly, thank you

**Comment by patrickpereira** [comment]
I get the same error on fresh nativescript typescript template:

WARNING in ./app.css
  resolve-url-loader cannot operate: CSS error
  /Users/patrickpereira/nativescript/Kcal/app/app.css:9:1: missing '{'
  at error (/Users/patrickpereira/nativescript/Kcal/node_modules/css/lib/parse/index.js:62:15)

How is that fixable?

**Comment by sis0k0** [comment]
Don't worry, @patrickpereira. It's just a warning.

**Comment by URvesh109** [comment]
npm run start-android-bundle --uglify

ERROR in bundle.js from UglifyJs
Unexpected token: punc ()) [bundle.js:6432,16]

**Comment by CoericK** [comment]
Same error that @URvesh109 ! cant build using --uglify on ios
