### ISSUE TITLE
Static binding generator failing in webpack build

### ISSUE THREAD

**Issue by Liooo** [NativeScript/nativescript-dev-webpack#749]
**Environment**

```
$ tns info
✔ Component nativescript has 5.1.0 version and is up to date.
✔ Component tns-core-modules has 5.1.0 version and is up to date.
✔ Component tns-android has 5.1.0 version and is up to date.
✔ Component tns-ios has 5.1.0 version and is up to date.

$ node --version
v10.8.0

$ cat package.json
...
"dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/http": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "nativescript-angular": "~7.1.0",
    "nativescript-background-geolocation-lt": "^1.9.0-beta.4",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.3.0",
    "tns-core-modules": "~5.1.0",
    "zone.js": "~0.8.18"
},
"devDependencies": {
    "@nativescript/schematics": "~0.4.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.18.0",
    "@angular/compiler-cli": "~7.1.0",
    "@ngtools/webpack": "~7.1.0"
},
```
- [x] Plugins: [nativescript-background-geolocation-lt](https://github.com/transistorsoft/nativescript-background-geolocation-lt)

- [x] Please, attach your package.json and webpack.config.js as these configurations are usually critical for investigating issues with webpack:

Here's the issue reproducible repo. Basically made from `tns-template-blank-ng` and configured plugin to work in minimum way.

https://github.com/Liooo/geo-loc-test
 

**Describe the bug**

There's something called `headless mode` in the plugin which lets the app access GPS after the activity is killed, utilizing android BroadcastReceiver.
This feature works well for non-webpack built app, but the same code fails on webpack built app raising the following error 

```
System.err: java.lang.RuntimeException: Unable to instantiate service com.transistorsoft.backgroundgeolocation.HeadlessJobService: java.lang.ClassNotFoundException: Didn't find class "com.transistorsoft.backgroundgeolocation.HeadlessJobService" on path: DexPathList[[zip file "/data/app/com.myapp/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp/lib/x86, /data/app/com.myapp/base.apk!/lib/x86, /system/lib, /vendor/lib]]
System.err: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3147)
System.err: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.transistorsoft.backgroundgeolocation.HeadlessJobService" on path: DexPathList[[zip file "/data/app/com.myapp/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp/lib/x86, /data/app/com.myapp/base.apk!/lib/x86, /system/lib, /vendor/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3144)
System.err: 	... 8 more
```

The static binding is made like this:

https://github.com/transistorsoft/nativescript-background-geolocation-lt/issues/136#issuecomment-447903075

**To Reproduce**

1. Start the app 
2. Click android hardware `Overview button` and show the list of apps running
3. kill the app, and app throws exception soon afterwards

**Expected behavior**

The app does not raise the error

**Sample project**

https://github.com/Liooo/geo-loc-test

**Additional context**

Here's the original issue in the plugin repo

https://github.com/transistorsoft/nativescript-background-geolocation-lt/issues/136

**Comment by NickIliev** [comment]
@Liooo the issue happens because with Webpack builds the HeadlessJonService is not included in the vendor.js file. The best approach would be to explciitly import the file in the plugin (e.g. in the file where it is needed) and this way it will always be part of the `vendor.js` file after bundling.

As a temporary workaround you could manually import the file (and this way it will be included in the vendor.js)

For example:
```TypeScript
// in app.component.ts
import "nativescript-background-geolocation-lt/HeadlessJobService";
```

**Comment by Liooo** [comment]
@NickIliev 	You're the best, thanks so much.
