### ISSUE TITLE
Not able to load core.light.css with WebPack

### ISSUE THREAD

**Issue by dlucidone** [NativeScript/nativescript-dev-webpack#76]
I'm Not able to use this import with webpack
    `@import 'nativescript-theme-core/css/core.light.css';`

**Comment by sis0k0** [comment]
Hey, @dlucidone,
Can you share the error you get? It works fine with the default template.

**Comment by dlucidone** [comment]
Yeah its working fine with the sample app .Anyway close the issue i might be be messing up with dependencies.
