### ISSUE TITLE
Error if no "app.css" file

### ISSUE THREAD

**Issue by joshcomley** [NativeScript/nativescript-dev-webpack#766]
If I don't have an empty `app.css` file in my project's code subfolder, I get the following error:

	ERROR in ../node_modules/nativescript-dev-webpack/load-application-css-angular.js
	Module not found: Error: Can't resolve '~/app' in 'D:\Code\Playgrounds\login-tab-navigation-ng-2\node_modules\nativescript-dev-webpack'
	 @ ../node_modules/nativescript-dev-webpack/load-application-css-angular.js 5:49-65
	 @ ./main.ts

I don't really understand why but `load-application-css-angular.js` is simply requiring an `app.css` file.

If I create a blank `app.css` file, the error goes away. I'm guessing an assumption is made that apps will always have this file, but it's not particularly safe and the error isn't immediately giving away the reason for itself.

Hope this helps.

**Comment by miroslavaivanova** [comment]
This issue is not reproducible. I'm closing it.
