### ISSUE TITLE
Support for background services

### ISSUE THREAD

**Issue by dzfweb** [NativeScript/nativescript-dev-webpack#87]
I've created a background service similar with the sample-android-background-services, when executing with bundle commands, the app crash while loading the custom service.

Steps to reproduce the error:
git clone https://github.com/NativeScript/sample-android-background-services
cd sample-android-background-services
npm install --save-dev nativescript-dev-webpack
npm run start-android-bundle

`Error: com.tns.NativeScriptException: Failed to find module: "./broadcastreceivers/NotificationEventReceiver.js", relative to: app//`

![screenshot_60](https://cloud.githubusercontent.com/assets/10212321/23363860/71b9ad5c-fcdb-11e6-8eb7-10f4a82c36ac.png)

**Comment by sis0k0** [comment]
You'll have to require the file containing the service explicitly. For example, in the above app you should add the following lines to `app/vendor.js`:
``` ts
require("./broadcastreceivers/NotificationEventReceiver.js")
require("./broadcastreceivers/NotificationServiceStarterReceiver.js")
```

**Comment by dzfweb** [comment]
After added those lines into vendor.js i got other error.
```

Unable to create application com.tns.NativeScriptApplication: com.tns.nativeScritpException:

Error calling module function

Error: java.lang.ClassNotFoundException: com.tns.notifications.NotificationintentService
java.langClass.classForName(NathiveMethod) 
...
```

even adding the line `require("./notifications/NotificationIntentService.js");` into vendor.js

**Comment by dzfweb** [comment]
Interestingly, after i run the command `tns run android` and then run bundle commands, the app works fine.
I believe to be on the compilation of some files skipped by bundle script.
Which files, i don't know.

**Comment by sis0k0** [comment]
Hey, there.

I just tested it on my machine and it works fine. Try to run it with `npm run start-android-bundle` from [this](https://github.com/NativeScript/sample-android-background-services/tree/webpack) branch and let me know if there's still a problem.

**Comment by dzfweb** [comment]
Work with caveats. As i said previously, I needed to run `tns run android` first, and then `npm run start-android-bundle` works.
