### ISSUE TITLE
[0.3.4?] Cannot find module "ui/layouts/stack-layout"

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/nativescript-dev-webpack#88]
After running `rm -rf node_modules && npm install` today I started getting all kinds of errors, e.g.:

```
StackLayout.Error: Cannot find module "ui/layouts/stack-layout"
```

I think it is related to the release of v0.3.4? Any idea how I can fix it? I already deleted the plugin and everything related to webpack and re-installed.

Thanks!

**Comment by abhayastudios** [comment]
Maybe related to #79?

**Comment by sis0k0** [comment]
Hey there,

Can you share a reproduction of the problem?

**Comment by abhayastudios** [comment]
@sis0k0  yes upgrading to `0.3.5` and updating the `webpack.common.js` according to instructions solved the issue!

Thanks again :)
