### ISSUE TITLE
npm audit says that webpack-bundle-analyzer prior to 3.3.2 are vulnerable to Cross-Site Scripting

### ISSUE THREAD

**Issue by yahyaKacem** [NativeScript/nativescript-dev-webpack#890]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.0
 - Cross-platform modules: I don't think this relevant
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.0
 - Plugin(s): I don't think this relevant
 - Node.js: v11.15.0 (nvm installed)
 
 - [ ] Please, attach your package.json and webpack.config.js as these configurations are usually critical for investigating issues with webpack
**package.json and webpack.config.js are the same as generated.**

**Describe the bug**
webpack-bundle-analyzer prior to 3.3.2 are vulnerable to Cross-Site Scripting as described [here](https://www.npmjs.com/advisories/826)

**To Reproduce**
tns create new-project
npm audit

**Expected behavior**
should not depend on a package version that is vulnerable to Cross-Site Scripting.

**Sample project**
just generate a new project with tns

**Additional context**

![Screen Shot 2019-05-15 at 5 52 58 PM](https://user-images.githubusercontent.com/844900/57797344-2099ad80-7742-11e9-87fb-089e7b33fb24.png)

**Comment by JarriddW** [comment]
I have the same issue after fixing "Vulnerability in `tar`" in issue #2625

**Comment by SDotTatum** [comment]
Same issue...

**Comment by jocafi** [comment]
me too

**Comment by Sartori-RIA** [comment]
Same issue :/
