### ISSUE TITLE
Updating to 0.22 from 0.21 leaves webpack in a broken state

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-dev-webpack#897]
**Environment**
 - CLI: 5.4.0
 - Cross-platform modules:
 - Android Runtime: 5.40
 - iOS Runtime: 5.4.0
 
**Describe the bug**
I did a `tns update` on two of my projects that were 5.3 apps.   Both of them had 0.21 of the webpack installed.  So if you recall; the webpack.config file references "uglify" instead of "terser".  

1. On initial run the 5.4, it asked to switch to the new workflow.  This new workflow broke my app under v0.21.   I realized from the package.json that I was still on 0.21 (even though I did a `tns update`).   So I manually installed 0.22 (`npm i nativescript-dev-webpack@latest --save-dev`)

2. Tns now crashes because the missing uglify plugin; because the webpack config wasn't upgraded either.   Manually upgrading the webpack config fixes the issue.

**To Reproduce**
Take a 5.3 app with 0.21 webpack; do a `tns update`

**Expected behavior**
1. tns update -> should have installed 0.22 of webpack
2. tns update -> should have replaced the webpack config file

**Comment by DimitarTachev** [comment]
Hi @NathanaelA,

Thanks for the feedback.

`nativescript-dev-webpack@0.21` is the first version of this plugin with **HMR out of beta support**.

Accepting the workflow switch or executing `tns update --workflow` will backup your current `webpack.config.js` and install `nativescript-dev-webpack@latest` only if the current version is less than `0.21`.

In other words, the webpack plugin dependency of your apps is passing the minimum requirement for the workflow switch and that's the reason why we are not updating your plugin out of the box. 

However, if you need some fixes from some of the latest plugin versions, you can always follow its update procedure executing `npm i nativescript-dev-webpack@latest --save-dev` and `./node_modules/.bin/update-ns-webpack --configs` (**that's the missing part from your update flow**).

Bear in mind that the above-mentioned update flow will override your `webpack.config.js` file and if you have some custom configurations there, you need to apply them once again after the update (this is the main reason why we are not always forcing the latest plugin version for all apps). We are working on a better way of extending the `webpack config` files for our 6.0.0 release and most probably this update process will become much easier in a few months.

**Comment by NathanaelA** [comment]
Well unfortunately; 0.21 wasn't fully out of beta ready, despite it claiming to be.  :grinning:      I wouldn't have had to upgrade to 0.22 if 0.21 had actually worked properly...  :grinning:

As long as the 5.5(?) and 6.00 will actually rename the old webpack config and put the latest webpack-dev; we should be good.    IMHO, the solution of renaming the old webpack to .old and replacing it on the upgrade I think is acceptable; it is way worse imho when everything becomes broken because you accept the "default" choice of allowing the new workflow...

**Comment by DimitarTachev** [comment]
Thanks for the feedback.

We are already installing the latest `nativescript-dev-webpack` version and [renaming the old webpack config to `webpack.config.js.bak`](https://github.com/NativeScript/nativescript-cli/blob/a4cb42ccc8a2f33dcc4fd893f65ffcba7255e6af/lib/services/workflow-service.ts#L104) during the workflow switch when the plugin is older than `0.21`. 

Maybe we've made the wrong assumption that `>=0.21` is good enough for the new workflow. We assumed that in most of the cases you won't need the overhead of getting `.bak` file and reading a warning for re-applying custom config changes when you are already using a  `nativescript-dev-webpack` version with an official HMR support.

I suppose that the `6.0.0` update flow will always force the latest `nativescript-dev-webpack` and generate the `.bak` file and it won't be possible to get your app in such state.
