### ISSUE TITLE
tns debuig ios --bundle --emulator --debug-brk crashes the debugger

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-dev-webpack#9]
Bundling a ng2 app most the time will crash the debugger.  Not sure if the bundle is too big or what; but the debugger doesn't like it and blows up.

**Comment by hdeshev** [comment]
Bundling currently works only for release builds and integrating debugger support will be a part of the hot module replacement effort. Closing this issue for now.

**Comment by NathanaelA** [comment]
@hdeshev - I disagree with you closing this; until you actually fix it.    It is a valid issue, and so closing it means when people search OPEN issues they won't find it.
