### ISSUE TITLE
iOS bundle failing with webpack

### ISSUE THREAD

**Issue by gowthamcodingmart** [NativeScript/nativescript-dev-webpack#93]
This is the I'm getting
`> npm run ns-bundle --ios --start-app

> @ ns-bundle /Users/Supervalu/Documents/Backup/my-project
> ns-bundle

Running webpack for ios...
Hash: e69f0135d6c5c0e40dc4                                                    / Version: webpack 2.2.0
Time: 32247ms
                                 Asset       Size  Chunks                    Chunk Names
             images/icons/png/like.png  867 bytes          [emitted]         
                             bundle.js    3.03 MB       0  [emitted]  [big]  bundle
                             vendor.js    5.42 MB       2  [emitted]  [big]  vendor
                               app.css    15.9 kB       1  [emitted]         app.css
          images/appointment-large.jpg    4.12 MB          [emitted]  [big]  
                images/appointment.png       7 kB          [emitted]         
                   images/bg-image.png  281 bytes          [emitted]         
                       images/Blue.png    5.49 kB          [emitted]         
                      images/close.png    6.96 kB          [emitted]         
                   images/dropdown.png    2.72 kB          [emitted]         
                    images/forward.png  765 bytes          [emitted]         
                   images/gradient.png    3.76 kB          [emitted]         
        images/icons/png/agreement.png    1.31 kB          [emitted]         
             images/icons/png/bell.png  612 bytes          [emitted]         
             images/icons/png/bird.png  892 bytes          [emitted]         
     images/icons/png/birdand fish.png    1.37 kB          [emitted]         
      images/icons/png/businessmen.png    1.39 kB          [emitted]         
         images/icons/png/calendar.png  686 bytes          [emitted]         
           images/icons/png/camera.png  956 bytes          [emitted]         
             images/icons/png/cat1.png    1.03 kB          [emitted]         
             images/icons/png/cat2.png    1.27 kB          [emitted]         
             images/icons/png/dog1.png    1.17 kB          [emitted]         
             images/icons/png/dog2.png  982 bytes          [emitted]         
             images/icons/png/fish.png    1.19 kB          [emitted]         
            images/icons/png/heart.png  922 bytes          [emitted]         
             images/icons/png/home.png    14.5 kB          [emitted]         
           images/icons/png/images.png    1.52 kB          [emitted]         
              images/icons/png/key.png  953 bytes          [emitted]         
                            app.css.js  270 bytes       1  [emitted]         app.css
         images/icons/png/location.png     208 kB          [emitted]         
        images/icons/png/lock open.png  549 bytes          [emitted]         
             images/icons/png/lock.png  583 bytes          [emitted]         
           images/icons/png/logout.png  678 bytes          [emitted]         
images/icons/png/manwalkingwithdog.png     6.9 kB          [emitted]         
            images/icons/png/money.png    1.07 kB          [emitted]         
         images/icons/png/moneybag.png  979 bytes          [emitted]         
             images/icons/png/note.png  746 bytes          [emitted]         
         images/icons/png/pet bowl.png    4.41 kB          [emitted]         
   images/icons/png/pet with owner.png     1.3 kB          [emitted]         
             images/icons/png/pets.png     1.1 kB          [emitted]         
            images/icons/png/phone.png    1.03 kB          [emitted]         
         images/icons/png/pricetag.png     1.2 kB          [emitted]         
           images/icons/png/rabbit.png  806 bytes          [emitted]         
              images/icons/png/rat.png    1.34 kB          [emitted]         
        images/icons/png/sandclock.png    1.11 kB          [emitted]         
         images/icons/png/settings.png     1.1 kB          [emitted]         
           images/icons/png/spider.png    1.57 kB          [emitted]         
    images/icons/png/successfulman.png    1.36 kB          [emitted]         
          images/icons/png/turtles.png    1.96 kB          [emitted]         
             images/icons/png/user.png    1.34 kB          [emitted]         
              images/icons/png/vet.png    1.29 kB          [emitted]         
             images/icons/png/wifi.png    1.38 kB          [emitted]         
                     images/pet-bg.png    16.2 kB          [emitted]         
                   images/star-512.png    13.1 kB          [emitted]         
                          package.json  101 bytes          [emitted]         
                            starter.js   41 bytes          [emitted]         
   [2] ../~/@angular/core/index.js 2.54 kB {2} [built]
 [126] ../~/@angular/common/index.js 793 bytes {2} [built]
 [127] ../~/nativescript-angular/element-registry.js 5.51 kB {2} [built]
 [177] ../~/@angular/http/index.js 734 bytes {2} [built]
 [677] ../~/@angular/forms/index.js 1.04 kB {2} [built]
 [678] ../~/@angular/router/index.js 909 bytes {2} [built]
 [679] ../~/nativescript-angular/platform-static.js 787 bytes {2} [built]
 [680] ./modules/app.module.ts 4.72 kB {0} [built]
 [681] ./vendor-platform.ios.ts 61 bytes {2} [built]
 [682] ../~/nativescript-drop-down/drop-down.ios.js 16.9 kB {0} [built]
[1271] ./app.css 41 bytes {1} [built]
[1272] ./main.ts 473 bytes {0} [built]
[1273] ./vendor.ts 408 bytes {2} [built]
[1274] ../~/nativescript-css-loader!../~/nativescript-theme-core/css/core.light.ios.css 13.5 kB [built]
[1275] ../~/nativescript-css-loader/lib/css-base.js 1.51 kB [built]
    + 1261 hidden modules

ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/Supervalu/Documents/Backup/my-project/node_modules/nativescript-angular/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/Supervalu/Documents/Backup/my-project/node_modules/nativescript-angular/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Users/Supervalu/Documents/Backup/my-project/node_modules/nativescript-angular/node_modules/@angular/core/src/di/opaque_token.d.ts

ERROR in ../~/nativescript-angular/router/ns-module-factory-loader.js
Module not found: TypeError: Cannot convert undefined or null to object
 @ ../~/nativescript-angular/router/ns-module-factory-loader.js 23:15-40
 @ ../~/nativescript-angular/router.js
 @ ./vendor.ts

ERROR in ../~/nativescript-angular/router/ns-module-factory-loader.js
Module not found: TypeError: Cannot convert undefined or null to object
 @ ../~/nativescript-angular/router/ns-module-factory-loader.js 29:27-46
 @ ../~/nativescript-angular/router.js
 @ ./vendor.ts
Child extract-text-webpack-plugin:
       [0] ../~/nativescript-css-loader/lib/css-base.js 1.51 kB {0} [built]
       [1] ../~/nativescript-css-loader!../~/nativescript-theme-core/css/core.light.ios.css 13.5 kB {0} [built]
       [2] ../~/nativescript-css-loader!../~/resolve-url-loader!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css 2.98 kB {0} [built]
child process exited with code 2

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ns-bundle" "--ios" "--start-app"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ ns-bundle script 'ns-bundle'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ns-bundle
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Supervalu/Documents/Backup/my-project/npm-debug.log

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-ios-bundle"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ start-ios-bundle: `npm run ns-bundle --ios --start-app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start-ios-bundle script 'npm run ns-bundle --ios --start-app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run ns-bundle --ios --start-app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Supervalu/Documents/Backup/my-project/npm-debug.log`

And My package.json is 

`{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.roverhealth",
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/router": "3.4.8",
    "email-validator": "^1.0.7",
    "nativescript-angular": "1.3.0",
    "nativescript-checkbox": "^1.2.5",
    "nativescript-drop-down": "^1.5.1",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-oauth": "^1.3.0",
    "nativescript-telerik-ui": "^1.6.1",
    "nativescript-theme-core": "1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.1",
    "tns-android": "^2.5.0",
    "tns-core-modules": "^2.5.1"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0-rc.0",
    "@angular/compiler-cli": "2.4.8",
    "@ngtools/webpack": "1.2.4",
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13.1",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "^0.3.2",
    "nativescript-dev-webpack": "^0.3.5",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "typescript": "~2.1.0",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3",
    "zone.js": "~0.7.2"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
`
Even I've changed the version of webpack to recent. I'm still having the issue.

**Comment by sis0k0** [comment]
Update your version of `nativescript-angular` to the latest one - 1.4.1, which supports angular ~2.4.

**Comment by unclekitty** [comment]
@sis0k0 , Hi 
angular version 4.0.1 and   nativescript-angular@1.5.1

> npm run ns-bundle --ios --start-app


> @ ns-bundle /Users/wujun/workspace/NativeScript/HelloWorld
> ns-bundle

Running webpack for ios...
/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:14552
            var sourceFile = new SourceFileConstructor(261 /* SourceFile */, /*pos*/ 0, /* end */ sourceText.length);
                                                                                                            ^

TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:14552:109)
    at parseSourceFileWorker (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:14484:26)
    at Object.parseSourceFile (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:14433:26)
    at Object.createSourceFile (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:14288:29)
    at WebpackCompilerHost.getSourceFile (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/@ngtools/webpack/src/compiler_host.js:210:27)
    at findSourceFile (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:63453:29)
    at processSourceFile (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:63384:27)
    at /Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:63494:17
    at Object.forEach (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:1293:30)
    at processReferencedFiles (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:63492:16)
    at findSourceFile (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:63477:21)
    at processSourceFile (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:63384:27)
    at processRootFile (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:63271:13)
    at /Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:62620:60
    at Object.forEach (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:1293:30)
    at Object.createProgram (/Users/wujun/workspace/NativeScript/HelloWorld/node_modules/typescript/lib/typescript.js:62620:16)
child process exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ ns-bundle script 'ns-bundle'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ns-bundle
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wujun/.npm/_logs/2017-04-06T07_31_19_459Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start-ios-bundle: `npm run ns-bundle --ios --start-app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start-ios-bundle script 'npm run ns-bundle --ios --start-app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run ns-bundle --ios --start-app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wujun/.npm/_logs/2017-04-06T07_31_19_472Z-debug.log

**Comment by Yamilquery** [comment]
Nativescript epic fail ... 👎

**Comment by SamuelGRwebfab** [comment]
any update on this?

**Comment by Yamilquery** [comment]
This is the solution.

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.dtech.levenmasdev",
    "tns-ios": {
      "version": "2.5.0"
    },
    "tns-android": {
      "version": "3.0.0-next-2017-03-27-1727"
    }
  },
  "dependencies": {
    "@angular/animations": "4.0.2",
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@angular/router": "4.0.2",
    "email-validator": "^1.0.7",
    "moment": "^2.18.1",
    "nativescript-angular": "1.5.1",
    "nativescript-gif": "^1.0.9",
    "nativescript-imagepicker": "^2.5.1",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-phone": "^1.2.4",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-webview-interface": "^1.4.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "2.5.2",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.0.2",
    "@ngtools/webpack": "1.2.13",
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "nativescript-dev-webpack": "^0.3.7",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "typescript": "~2.1.0",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
```
Then run:

`rm -rf platforms/ node_modules/ hooks/`

`tns run ios --bundle`

`npm run build-ios-bundle -- --release --for-device --teamId VPQB954B68`

Enjoy!

**Comment by Yamilquery** [comment]
This is the solution.

package.json
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.dtech.levenmasdev",
    "tns-ios": {
      "version": "2.5.0"
    },
    "tns-android": {
      "version": "3.0.0-next-2017-03-27-1727"
    }
  },
  "dependencies": {
    "@angular/animations": "4.0.2",
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@angular/router": "4.0.2",
    "email-validator": "^1.0.7",
    "moment": "^2.18.1",
    "nativescript-angular": "1.5.1",
    "nativescript-gif": "^1.0.9",
    "nativescript-imagepicker": "^2.5.1",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-phone": "^1.2.4",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-webview-interface": "^1.4.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "2.5.2",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.0.2",
    "@ngtools/webpack": "1.2.13",
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "nativescript-dev-webpack": "^0.3.7",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "typescript": "~2.1.0",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
```
Then run:

`rm -rf platforms/ node_modules/ hooks/`

`tns run ios --bundle`

`npm run build-ios-bundle -- --release --for-device --teamId VPQ666DIABLO`

Enjoy!

**Comment by SamuelGRwebfab** [comment]
@Yamilquery this did get me past my previous error, Thanks! However it is now throwing 

`cp: no such file or directory: /Users/sam/bitbucket/myApp/myAppName/platforms/ios/myAppName/app/*`
