### ISSUE TITLE
tsconfig paths resolution

### ISSUE THREAD

**Issue by Jonatthu** [NativeScript/nativescript-dev-webpack#94]
Is this supporting the next example on tsconfig?

```
base:"",
paths: {
  "Store": ["../shared/store/index"]
}
```

**Comment by sis0k0** [comment]
Yes, the default webpack configuration provided by the plugin supports the `paths` property if you are using TypeScript 2.1. Note that if you're using Angular, the plugin will use the `tsconfig.aot.ts` file.

**Comment by Jonatthu** [comment]
@sis0k0  Thanks I will try again

**Comment by sis0k0** [comment]
Do you still have problems with the paths option?

**Comment by Jonatthu** [comment]
@sis0k0 I am it is a little tricky compare it with ng cli or other webpack configurations, this is a work in progress anyway, but I can not get this easily, I will close this for now and opened again when I get a real error thanks!
