### ISSUE TITLE
Webpack doesn't copy all pages(files) in App folder

### ISSUE THREAD

**Issue by devyaz** [NativeScript/nativescript-dev-webpack#944]
**Environment**
``tns info ✔ Getting NativeScript components versions information... ✔ Component nativescript has 5.4.0 version and is up to date. ✔ Component tns-core-modules has 5.4.1 version and is up to date. ✔ Component tns-android has 5.4.0 version and is up to date. ⚠ Update available for component tns-ios. Your current version is 5.1.1 and the latest available version is 5.4.0.``

**Describe the bug**
After upgrading to 5.4 am asked to use webpack, which I accepted, after ``tns tun android --bundle`` all goes well till its deployed to device/emulator
The very first page load app crashes
![IMG_20190620_203515](https://user-images.githubusercontent.com/20435017/59872846-f3709880-939a-11e9-84dc-fb11d6c46489.jpg)
Exploring ``platforms/android/app/src/main/assets/app/bundle.js`` shows it only copies 8 of 33 files and folders! No matter what I try it's sticks to the 8 files& folders hence during loading it can't find ``account/account.xml and account/account.js`` but it can find ``home/home-page.xml/js`` because that's in the webpack map!
**To Reproduce**
Create an app 
enable webpack workflow,
Add 3 or more pages some in folders
Then run build then run bundle!

**Expected behavior**
It shouldn't copy the new file's and folders over to src folder and won't be listed in the ``bundle.js``!!
**Sample project**
Won't run in playground because it has plugins that aren't supported

**Additional context**
How do I setup webpack to copy everything over? Am new to webpack I've never used it before ,can webpack be used in apps with more than 8 pages/file's?

**Comment by NickIliev** [comment]
@devyaz the thing is that the default configuration from `nativescript-dev-webpack` will bundle only pages which file names are ending in `-page` or in `-root`.  It will also bundle all images and fonts.

So to resolve your issue 
rename **_accounts.xml_** and **_accounts.js_** 
to **accounts-page.xml** and **accounts-page.js**

Following this naming convention, rename all other custom pages.

Any other custom files should be explicitly added to `CopyWebpackPlugin`

```JavaScript
new CopyWebpackPlugin([
                { from: { glob: "fonts/**" } },
                { from: { glob: "**/*.jpg" } },
                { from: { glob: "**/*.png" } },
            ]
```

For example, if you have  a custom HTML file to load in Webview,
```JavaScript
new CopyWebpackPlugin([
                { from: { glob: "fonts/**" } },
                { from: { glob: "**/*.jpg" } },
                { from: { glob: "**/*.png" } },
                { from: { glob: "index.html" } }
            ]
```

**Comment by devyaz** [comment]
Thanks @Nick lliev, now if I want a folder like where my html and
associated files are how do I add that, should I just add the html file to
the plugin? I mean is it in ,``webpak.config.js`` ? Thanks in advance for
your help bear with me webpack isn't my cup of tea 😂

**Comment by devyaz** [comment]
@Nicklliev it's sorted! Thanks to you before I was about to downgrade 😂
