### ISSUE TITLE
crash with source-map instead of inline-source-map

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-dev-webpack#968]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  6.0.0 rc
 - plugins:  nativescript-dev-webpack 1.0.0 rc
 - Android Runtime: 6.0.0 rc
- vue project

 I have an issue with source maps and the latest versions of ```nativescript-dev-webpack```
Using the template webpack config file it works. 
However i use mine which uses ```source-map``` instead of ```inline-source-map```, my app crashes saying it cant require ```runtime.js.map```
I think the issue comes from ```GenerateNativeScriptEntryPointsPlugin```.
It was working before the RC, and now it does not.
What's bugging me is that i think it should work. The file ```runtime.js.map``` exists and is part of the APK in the assets/app folder.
the ```require('./runtime.js.map')``` is done in the ```runtime.js```, so it should work just fine.

By the way it's kind of a requirement for me to use ```source-map```. I use Bugsnag where map files are uploaded using ```.map``` files (i then filter with gradle so that map files are not included in the apk for size reasons).

Anyone has any idea why it could fail to require the ```.map``` file?

**Comment by DimitarTachev** [comment]
Hi @farfromrefug,

Thanks for reporting that!

As `devtool: "source-map"` is not officially supported, the code didn't expect file extensions different than `.js`. I've opened [a pull request](https://github.com/NativeScript/nativescript-dev-webpack/pull/976) with a fix and most probably it will be released in `nativescript-dev-webpack@1.0.1` as the development for `1.0.0` is already frozen.

**Comment by farfromrefug** [comment]
@miroslavaivanova @Fatme @DimitarTachev this is not fixed. The generated source map is wrong.
It seems like you add ```require("./snapshot-entry.js");require("./vendor.js");``` at the start of the file  which makes the source map not work. Can we re open this?

**Comment by DimitarTachev** [comment]
Hi @farfromrefug,

Thanks for reporting back. We've fixed the app crash but we've missed the `.map` files content.

You are right about the fix. I've just opened [a PR with it](https://github.com/NativeScript/nativescript-dev-webpack/pull/1008).

P.S. Feel free to directly open PRs with such fixes.

**Comment by farfromrefug** [comment]
@DimitarTachev Thanks! Sorry for not creating the PR, Did not really have time to create one (lazy me!)
