### ISSUE TITLE
dynamic import support

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-dev-webpack#990]
@Serge-SDL commented on [Tue Jul 16 2019](https://github.com/NativeScript/NativeScript/issues/7524)

Hi,

I need to use some dynamic import in my app (importing js module from http or local device file), but it doesn't work.

I tried :
`import(/* webpackIgnore: true */ file.path)` -> got the error "Not supported"

and
`System.import(file.path)` -> got the error "Cannot find module '/path/to/file'" even if the file exists.

Is this situation expected? Is there an other way?
thanks for your help!

**Comment by Serge-SDL** [comment]
Hi @NickIliev ,
I think you can close this issue, I already opened a other on this nativescript-dev-webpack topic.
thanks

**Comment by sis0k0** [comment]
Hi @Serge-SDL, could you please verify that the file is actually present in the built application? The webpack compilation includes only files that are explicitly required in the source code or included by some webpack plugin. An easy way to copy static assets is by using the `CopyWebpackPlugin`:

https://github.com/NativeScript/nativescript-dev-webpack/blob/3b120da6a201337682aef2351c90abe53bac50e0/demo/TypeScriptApp/webpack.config.js#L237-L241

**Comment by Serge-SDL** [comment]
@sis0k0 
Thank you for your quick answer!
Actually for my test I create a file at runtime and try to import this file so I'm sure the file exists.
more details here: https://github.com/NativeScript/nativescript-dev-webpack/issues/989

**Comment by NickIliev** [comment]
Closing as a duplicate to https://github.com/NativeScript/nativescript-dev-webpack/issues/990 - please continue the discussion in the linked issue.

**Comment by rynop** [comment]
I think ^ meant https://github.com/NativeScript/nativescript-dev-webpack/issues/989 not 990
