### ISSUE TITLE
Webpack doesn't update the view on save - after updated to NS6

### ISSUE THREAD

**Issue by dudipsh** [NativeScript/nativescript-dev-webpack#999]
Hi,
After i updated the project from v5 to v6 the Webpack not update the ui when i save the files, 

I try to reinstall the node_module + platform 

`tns run android --bundle`
Same issue whit the sidekick

ng --version

Angular CLI: 8.1.2
Node: 10.16.0
OS: win32 x64
Angular: 8.1.2

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/compiler-cli             8.0.0
@angular/http                     7.2.15
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.5.2
typescript                        3.4.5

- CLI: 
√ Getting NativeScript components versions information...
√ Component nativescript has 6.0.2 version and is up to date.
√ Component tns-core-modules has 6.0.1 version and is up to date.
√ Component tns-android has 6.0.0 version and is up to date.
√ Component tns-ios has 6.0.1 version and is up to date.

```json
{
  "name": "timeTablePlus",
  "nativescript": {
    "id": "il.co.timetable.timeTablePlus",
    "tns-ios": {
      "version": "6.0.1"
    },
    "tns-android": {
      "version": "6.0.0"
    }
  },
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "debug": "tns prepare android && tns run android --bundle --env.uglify",
    "android": "tns run android --bundle",
    "ios": "tns run ios --bundle",
    "mobile": "tns run --bundle",
    "preview": "tns preview --bundle"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "8.1.2",
    "@angular/common": "8.1.2",
    "@angular/compiler": "8.1.2",
    "@angular/core": "8.1.2",
    "@angular/forms": "8.1.2",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "8.1.2",
    "@angular/platform-browser-dynamic": "8.1.2",
    "@angular/router": "8.1.2",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "blueimp-md5": "^2.10.0",
    "core-js": "^3.1.4",
    "lodash": "^4.17.11",
    "nativescript-angular": "8.0.2",
    "nativescript-appversion": "^1.4.2",
    "nativescript-background-http": "^3.4.1",
    "nativescript-email": "^1.5.4",
    "nativescript-imagepicker": "^6.2.0",
    "nativescript-localstorage": "^2.0.0",
    "nativescript-ng-ripple": "^2.0.1",
    "nativescript-phone": "^1.4.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-calendar": "5.0.0",
    "nativescript-ui-sidedrawer": "7.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.2",
    "tns-core-modules": "^6.0.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular/cli": "^8.1.2",
    "@angular/compiler-cli": "8.0.0",
    "@nativescript/schematics": "~0.6.0",
    "@types/jasmine": "3.3.14",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~12.6.8",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.2.0",
    "karma-chrome-launcher": "~3.0.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "moment": "^2.24.0",
    "nativescript-dev-webpack": "^1.0.1",
    "nativescript-geolocation": "5.1.0",
    "node-sass": "4.12.0",
    "protractor": "~5.4.2",
    "tns-platform-declarations": "6.0.1",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "^3.4.5",
    "webpack": "^4.36.1"
  }
}

```

**Comment by dudipsh** [comment]
its working fine with
`tns run android --no-hmr`

**Comment by Fatme** [comment]
@dudipsh,

Thank you for reporting this issue!

We're not aware for such problems with HMR feature. However, passing `--no-hmr` is not a solution, as it leads to worst development experience. We'd like to figure out the root cause of the problem. Can you please tell us the exact steps you're executing so we're able to reproduce the problem on our side?

**Comment by dudipsh** [comment]
@Fatme 
Thank you for the responce. 

![alt text](https://i.ibb.co/cyPpRdM/tabs.png)

I was creating custom tabs with a dynamic component
that gives me the ability to inject view when I switch tabs
example of a dynamic component
https://stackblitz.com/edit/dynamic-com

in version 5.4 it worked without any issues!
when I try to debug the app any time I make a change the screen freezes

**Comment by Fatme** [comment]
@dudipsh,

Thank you for information!

Can you please send us a sample demo project demonstrating the problem so we can be sure that we investigate exactly your scenario?

**Comment by dudipsh** [comment]
@Fatme 
I created a new project and copy all the files, 
now on save the application closed and open with my changes it's not freezing anymore,
it's good enough for me
I am closing this bug.
Thanks for your help.
